## Cleaning and processing datasets

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
project_path = Path.cwd().parent
raw_data_path = project_path/"Data"/"Raw"

# print(raw_data_path)

metadata = pd.read_parquet(
    raw_data_path/"Raw_meta_Amazon_Cellphones.parquet"
    
)

print("Metadata Loaded Successfully!")

reviews = pd.read_parquet(
    raw_data_path/"Raw_review_Amazon_Cellphones.parquet"
    
)

print("Reviews Loaded Successfully!")

print(metadata.shape)
print(reviews.shape)

Metadata Loaded Successfully!
Reviews Loaded Successfully!
(184070, 16)
(1486639, 10)

In [3]:
metadata_clean = metadata.copy()
reviews_clean = reviews.copy()

In [4]:
print(metadata_clean.shape)
print(reviews_clean.shape)

(184070, 16)
(1486639, 10)

In [5]:
metadata_clean.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Cell Phones & Accessories,ARAREE Slim Diary Cell Phone Case for Samsung ...,3.8,5,"[Genuine Cow leather with 6 different colors, ...","[JUST LOOK, You can tell the difference. Make ...",None,"{'hi_res': [None, None, None, None, None, None...","{'title': [], 'url': [], 'user_id': []}",araree,"[Cell Phones & Accessories, Cases, Holsters & ...","{""Product Dimensions"": ""3.35 x 0.59 x 6.18 inc...",B013SK1JTY,None,None,None
1,Cell Phones & Accessories,Bastmei for OnePlus 7T Case Extremely Light Ul...,4.4,177,[Ultra-thin & Ultra-light: The ultra slim fit ...,[],11.98,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Bastmei,"[Cell Phones & Accessories, Cases, Holsters & ...","{""Package Dimensions"": ""7.6 x 4.29 x 0.75 inch...",B07ZPSG8P5,None,None,None
2,Cell Phones & Accessories,Wireless Fones Branded New Iphone 5C/LITE Hot ...,4.0,2,[],[],None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",WIRELESS FONES,"[Cell Phones & Accessories, iPhone Accessories]","{""Item model number"": ""Apple Iphone 5C"", ""Othe...",B00GKR3L12,None,None,None
3,Cell Phones & Accessories,"iPhone 6 Plus + Case, DandyCase Perfect PATTER...",4.0,15,"[Slim-Fit design for the iPhone 6 Plus (5.5"" s...",[Case does not need to be removed for charging...,None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",DandyCase,"[Cell Phones & Accessories, iPhone Accessories]","{""Product Dimensions"": ""5.43 x 0.28 x 2.64 inc...",B00PB8U8BW,None,None,None
4,Cell Phones & Accessories,"Case for Galaxy S6/S6 Edge, Thin Translucent V...",4.0,1,[],[],None,"{'hi_res': [None, None], 'large': ['https://m....","{'title': [], 'url': [], 'user_id': []}",7Pite,"[Cell Phones & Accessories, Cases, Holsters & ...","{""Package Dimensions"": ""8.31 x 3.74 x 0.55 inc...",B07D3RHSRV,None,None,None

Understanding missing values

In [6]:
metadata_clean.isnull().sum().sort_values(ascending=False)

bought_together    184070
author             184068
subtitle           183880
store                2105
main_category         344
title                   0
average_rating          0
rating_number           0
images                  0
price                   0
description             0
features                0
details                 0
categories              0
videos                  0
parent_asin             0
dtype: int64

In [7]:
reviews_clean.isnull().sum().sort_values(ascending=False)

rating               0
title                0
text                 0
images               0
asin                 0
parent_asin          0
user_id              0
timestamp            0
helpful_vote         0
verified_purchase    0
dtype: int64

-- Metadata has bought_together, author, subtitle, store and main_category nulls value columns.
-- Ratings has no null value column

In [8]:
# Droping unneeded columns 

metadata_clean = metadata_clean.drop (
    columns = ["bought_together",
        "author",
        "subtitle",
        ]
)

In [9]:
#filling missing values

metadata_clean["store"]=metadata_clean["store"].fillna("Unknown")
metadata_clean["main_category"] = metadata_clean["main_category"].fillna("Cell Phones & Accessories")

In [10]:

metadata_clean.shape

(184070, 13)

In [11]:
metadata_clean.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin
0,Cell Phones & Accessories,ARAREE Slim Diary Cell Phone Case for Samsung ...,3.8,5,"[Genuine Cow leather with 6 different colors, ...","[JUST LOOK, You can tell the difference. Make ...",None,"{'hi_res': [None, None, None, None, None, None...","{'title': [], 'url': [], 'user_id': []}",araree,"[Cell Phones & Accessories, Cases, Holsters & ...","{""Product Dimensions"": ""3.35 x 0.59 x 6.18 inc...",B013SK1JTY
1,Cell Phones & Accessories,Bastmei for OnePlus 7T Case Extremely Light Ul...,4.4,177,[Ultra-thin & Ultra-light: The ultra slim fit ...,[],11.98,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Bastmei,"[Cell Phones & Accessories, Cases, Holsters & ...","{""Package Dimensions"": ""7.6 x 4.29 x 0.75 inch...",B07ZPSG8P5
2,Cell Phones & Accessories,Wireless Fones Branded New Iphone 5C/LITE Hot ...,4.0,2,[],[],None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",WIRELESS FONES,"[Cell Phones & Accessories, iPhone Accessories]","{""Item model number"": ""Apple Iphone 5C"", ""Othe...",B00GKR3L12
3,Cell Phones & Accessories,"iPhone 6 Plus + Case, DandyCase Perfect PATTER...",4.0,15,"[Slim-Fit design for the iPhone 6 Plus (5.5"" s...",[Case does not need to be removed for charging...,None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",DandyCase,"[Cell Phones & Accessories, iPhone Accessories]","{""Product Dimensions"": ""5.43 x 0.28 x 2.64 inc...",B00PB8U8BW
4,Cell Phones & Accessories,"Case for Galaxy S6/S6 Edge, Thin Translucent V...",4.0,1,[],[],None,"{'hi_res': [None, None], 'large': ['https://m....","{'title': [], 'url': [], 'user_id': []}",7Pite,"[Cell Phones & Accessories, Cases, Holsters & ...","{""Package Dimensions"": ""8.31 x 3.74 x 0.55 inc...",B07D3RHSRV

In [12]:
metadata_clean.isnull().sum().sort_values(ascending=False)

main_category     0
title             0
average_rating    0
rating_number     0
features          0
description       0
price             0
images            0
videos            0
store             0
categories        0
details           0
parent_asin       0
dtype: int64

Removing duplicates

In [13]:
##Checking duplicates
metadata_duplicates = metadata_clean["parent_asin"].duplicated().sum()
print(f"Duplicate parent_asin in Metdata: {metadata_duplicates}")

Duplicate parent_asin in Metdata: 0

In [14]:
review_duplicates = reviews_clean.duplicated(
    subset=[
        "parent_asin",
        "user_id",
        "timestamp",
        "text"
    ]
).sum()

print(f"Duplicate Review Records Before Removal: {review_duplicates}")

Duplicate Review Records Before Removal: 4471

In [15]:
reviews_clean = reviews_clean.drop_duplicates(
    subset=[
        "parent_asin",
        "user_id",
        "timestamp",
        "text"
    ]
).reset_index(drop=True)

In [16]:
review_duplicates_after = reviews_clean.duplicated(
    subset=[
        "parent_asin",
        "user_id",
        "timestamp",
        "text"
    ]
).sum()

print(f"Duplicate Review Records After Removal: {review_duplicates_after}")

Duplicate Review Records After Removal: 0

In [17]:
reviews_clean.shape

(1482168, 10)

In [18]:
#checking data types

metadata_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184070 entries, 0 to 184069
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   main_category   184070 non-null  object
 1   title           184070 non-null  object
 2   average_rating  184070 non-null  float64
 3   rating_number   184070 non-null  int64
 4   features        184070 non-null  object
 5   description     184070 non-null  object
 6   price           184070 non-null  object
 7   images          184070 non-null  object
 8   videos          184070 non-null  object
 9   store           184070 non-null  object
 10  categories      184070 non-null  object
 11  details         184070 non-null  object
 12  parent_asin     184070 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 18.3+ MB

In [19]:
#checking datatypes of description 

print(type(metadata_clean.loc[0, "description"]))
print(type(metadata_clean.loc[0, "features"]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [20]:
#converting the columns datatypes:

metadata_clean["description"] = metadata_clean["description"].apply(lambda x: " ".join(x.tolist()) if isinstance(x,np.ndarray)else"")

In [21]:
metadata_clean["features"] = metadata_clean["features"].apply(
    lambda x: " ".join(x.tolist()) if isinstance(x, np.ndarray) else ""
)

In [22]:
print(type(metadata_clean.loc[0, "description"]))
print(type(metadata_clean.loc[0, "features"]))

<class 'str'>
<class 'str'>

In [23]:
print(type(metadata_clean.loc[0, "categories"]))

<class 'numpy.ndarray'>

In [24]:
metadata_clean["categories"] = metadata_clean["categories"].apply(
    lambda x: " > ".join(x.tolist()) if isinstance(x, np.ndarray) else ""
)

In [25]:
print(type(metadata_clean.loc[1, "description"]))
print(type(metadata_clean.loc[1, "features"]))
print(metadata_clean.loc[1, "description"])

<class 'str'>
<class 'str'>

In [26]:
metadata_summary = []

for col in metadata_clean.columns:
    metadata_summary.append({
        "Column": col,
        "Pandas dtype": metadata_clean[col].dtype,
        "Python type": type(metadata_clean[col].iloc[0]).__name__
    })

import pandas as pd

pd.DataFrame(metadata_summary)

            Column Pandas dtype Python type
0    main_category       object         str
1            title       object         str
2   average_rating      float64     float64
3    rating_number        int64       int64
4         features       object         str
5      description       object         str
6            price       object         str
7           images       object        dict
8           videos       object        dict
9            store       object         str
10      categories       object         str
11         details       object         str
12     parent_asin       object         str

In [27]:
review_summary = []

for col in reviews_clean.columns:
    review_summary.append({
        "Column": col,
        "Pandas dtype": reviews_clean[col].dtype,
        "Python type": type(reviews_clean[col].iloc[0]).__name__
    })

pd.DataFrame(review_summary)

              Column Pandas dtype Python type
0             rating      float64     float64
1              title       object         str
2               text       object         str
3             images       object     ndarray
4               asin       object         str
5        parent_asin       object         str
6            user_id       object         str
7          timestamp        int64       int64
8       helpful_vote        int64       int64
9  verified_purchase         bool        bool

In [28]:
#converting metadata price to float

metadata_clean["price"] = (
    metadata_clean["price"]
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

metadata_clean["price"] = pd.to_numeric(
    metadata_clean["price"],
    errors="coerce"
)

In [29]:
#converting reviews timestamp to datetime


reviews_clean["review_date"] = pd.to_datetime(
    reviews_clean["timestamp"],
    unit="ms"
)

In [30]:

# print(reviews_clean["images"].iloc[0])
# print(type(reviews_clean["images"].iloc[0]))

#converting ireview images to python list


reviews_clean["images"] = reviews_clean["images"].apply(
    lambda x: x.tolist() if isinstance(x, np.ndarray) else x
)

In [31]:
print(reviews_clean["images"].iloc[0])
print(type(reviews_clean["images"].iloc[0]))

[{'attachment_type': 'IMAGE', 'large_image_url': 'https://images-na.ssl-images-amazon.com/images/I/B1PrCo7ZjXS._SL1600_.jpg', 'medium_image_url': 'https://images-na.ssl-images-amazon.com/images/I/B1PrCo7ZjXS._SL800_.jpg', 'small_image_url': 'https://images-na.ssl-images-amazon.com/images/I/B1PrCo7ZjXS._SL256_.jpg'}]
<class 'list'>

In [32]:
#converting metadata images and videos

print(type(metadata_clean["images"].iloc[0]))
print(metadata_clean["images"].iloc[0])

print(type(metadata_clean["videos"].iloc[0]))
print(metadata_clean["videos"].iloc[0])

<class 'dict'>
{'hi_res': array([None, None, None, None, None, None, None], dtype=object), 'large': array(['https://m.media-amazon.com/images/I/51Q9w96zIQL._AC_.jpg',
       'https://m.media-amazon.com/images/I/313l+o9yq4L._AC_.jpg',
       'https://m.media-amazon.com/images/I/31dB-5tjhbL._AC_.jpg',
       'https://m.media-amazon.com/images/I/51EQ5aGITZL._AC_.jpg',
       'https://m.media-amazon.com/images/I/51f+krWe67L._AC_.jpg',
       'https://m.media-amazon.com/images/I/51XUQoEKNDL._AC_.jpg',
       'https://m.media-amazon.com/images/I/51VNEfu9LSL._AC_.jpg'],
      dtype=object), 'thumb': array(['https://m.media-amazon.com/images/I/51Q9w96zIQL._AC_SR38,50_.jpg',
       'https://m.media-amazon.com/images/I/313l+o9yq4L._AC_SR38,50_.jpg',
       'https://m.media-amazon.com/images/I/31dB-5tjhbL._AC_SR38,50_.jpg',
       'https://m.media-amazon.com/images/I/51EQ5aGITZL._AC_SR38,50_.jpg',
       'https://m.media-amazon.com/images/I/51f+krWe67L._AC_SR38,50_.jpg',
       'https://m.media-amazon.com/images/I/51XUQoEKNDL._AC_SR38,50_.jpg',
       'https://m.media-amazon.com/images/I/51VNEfu9LSL._AC_SR38,50_.jpg'],
      dtype=object), 'variant': array(['MAIN', 'PT01', 'PT02', 'PT03', 'PT04', 'PT05', 'PT06'],
      dtype=object)}
<class 'dict'>
{'title': array([], dtype=object), 'url': array([], dtype=object), 'user_id': array([], dtype=object)}

In [33]:
#converting dictionaries to python lists for better processing

def convert_nested(obj):
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, dict):
        return {k: convert_nested(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [convert_nested(v) for v in obj]
    else:
        return obj

metadata_clean["images"] = metadata_clean["images"].apply(convert_nested)
metadata_clean["videos"] = metadata_clean["videos"].apply(convert_nested)

In [34]:
print(type(metadata_clean["images"].iloc[0]))
print(type(metadata_clean["videos"].iloc[0]))

<class 'dict'>
<class 'dict'>

In [35]:
metadata_summary = []

for col in metadata_clean.columns:
    metadata_summary.append({
        "Column": col,
        "Pandas dtype": metadata_clean[col].dtype,
        "Python type": type(metadata_clean[col].iloc[0]).__name__
    })

import pandas as pd

pd.DataFrame(metadata_summary)

            Column Pandas dtype Python type
0    main_category       object         str
1            title       object         str
2   average_rating      float64     float64
3    rating_number        int64       int64
4         features       object         str
5      description       object         str
6            price      float64     float64
7           images       object        dict
8           videos       object        dict
9            store       object         str
10      categories       object         str
11         details       object         str
12     parent_asin       object         str

In [36]:
review_summary = []

for col in reviews_clean.columns:
    review_summary.append({
        "Column": col,
        "Pandas dtype": reviews_clean[col].dtype,
        "Python type": type(reviews_clean[col].iloc[0]).__name__
    })

pd.DataFrame(review_summary)

               Column    Pandas dtype Python type
0              rating         float64     float64
1               title          object         str
2                text          object         str
3              images          object        list
4                asin          object         str
5         parent_asin          object         str
6             user_id          object         str
7           timestamp           int64       int64
8        helpful_vote           int64       int64
9   verified_purchase            bool        bool
10        review_date  datetime64[ns]   Timestamp

In [37]:
metadata_clean.isnull().sum().sort_values(ascending=False)

price             127513
title                  0
average_rating         0
rating_number          0
main_category          0
features               0
description            0
images                 0
videos                 0
store                  0
categories             0
details                0
parent_asin            0
dtype: int64

In [38]:
# for null pricing : 

title_price_counts = (
    metadata_clean.groupby("title")["price"]
    .nunique(dropna=True)
)

consistent_titles = title_price_counts[title_price_counts == 1].index

In [39]:
price_lookup = (
    metadata_clean[metadata_clean["title"].isin(consistent_titles)]
    .groupby("title")["price"]
    .first()
)

mask = metadata_clean["price"].isna()

metadata_clean.loc[mask, "price"] = (
    metadata_clean.loc[mask, "title"]
    .map(price_lookup)
)

In [40]:
print("Total Products:", len(metadata_clean))
print("Unique Products:", metadata_clean["parent_asin"].nunique())

Total Products: 184070
Unique Products: 184070

In [41]:
# List of all unique product titles
unique_products = (
    metadata_clean["title"]
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

unique_products

0
1         " Kiss me I'm Vegan "Cute Custom boutique Baby...
2                                      "Arrowhead" Necklace
3         "Best Dad" Snap-On Cover Hard Carrying Case fo...
4         "Buckeye Nation" Chevron Sports Hard Black Glo...
                                ...
181831    𝟮𝟬𝟮𝟯 𝐔𝐩𝐠𝐫𝐚𝐝𝐞𝐝 for Apple Watch Charger Magnetic...
181832    𝟮𝟬𝟮𝟯 𝐔𝐩𝐠𝐫𝐚𝐝𝐞𝐝 for Apple Watch Charger Magnetic...
181833    𝟮𝟬𝟮𝟯 𝗡𝗲𝘄 Wireless Charger 3 in 1,Wireless Char...
181834    𝟮𝟬𝟮𝟯 𝗡𝗲𝘄 Wireless Charging Station 3 in 1 Wire...
181835    🏆 Premium Pack Neti Pot Complete Sinus Cleansi...
Name: title, Length: 181836, dtype: object

In [42]:
reviews_clean.isnull().sum().sort_values(ascending=False)

rating               0
title                0
text                 0
images               0
asin                 0
parent_asin          0
user_id              0
timestamp            0
helpful_vote         0
verified_purchase    0
review_date          0
dtype: int64

In [43]:
text_cols = [
    "title",
    "description",
    "features",
    "categories",
    "details"
]

for col in text_cols:
    metadata_clean[col] = metadata_clean[col].str.strip()

In [44]:
text_cols = ["title", "text"]

for col in text_cols:
    reviews_clean[col] = reviews_clean[col].str.strip()

creating a product_text column in metadata which the Retrieval Agent will embedd during FAISS

In [45]:
metadata_clean["product_text"] = (
    "Title: " + metadata_clean["title"].fillna("") +
    "\n\nDescription: " + metadata_clean["description"].fillna("") +
    "\n\nFeatures: " + metadata_clean["features"].fillna("") +
    "\n\nCategory: " + metadata_clean["categories"].fillna("") +
    "\n\nDetails: " + metadata_clean["details"].fillna("")
)

Saving the cleaned datasets

In [46]:
from pathlib import Path

# Create Processed folder if it doesn't exist
processed_path = Path("../Data/Cleaned")
processed_path.mkdir(parents=True, exist_ok=True)

# Save datasets
metadata_clean.to_parquet(
    processed_path / "metadata_clean.parquet",
    index=False
)

reviews_clean.to_parquet(
    processed_path / "reviews_clean.parquet",
    index=False
)

print("Datasets saved successfully!")

Datasets saved successfully!

In [47]:
metadata_clean.columns

Index(['main_category', 'title', 'average_rating', 'rating_number', 'features',
       'description', 'price', 'images', 'videos', 'store', 'categories',
       'details', 'parent_asin', 'product_text'],
      dtype='object')

In [48]:
reviews_clean.columns

Index(['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id',
       'timestamp', 'helpful_vote', 'verified_purchase', 'review_date'],
      dtype='object')

In [50]:
metadata_clean.head(2)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,product_text
0,Cell Phones & Accessories,ARAREE Slim Diary Cell Phone Case for Samsung ...,3.8,5,Genuine Cow leather with 6 different colors 3 ...,"JUST LOOK, You can tell the difference. Make e...",NaN,"{'hi_res': [None, None, None, None, None, None...","{'title': [], 'url': [], 'user_id': []}",araree,"Cell Phones & Accessories > Cases, Holsters & ...","{""Product Dimensions"": ""3.35 x 0.59 x 6.18 inc...",B013SK1JTY,Title: ARAREE Slim Diary Cell Phone Case for S...
1,Cell Phones & Accessories,Bastmei for OnePlus 7T Case Extremely Light Ul...,4.4,177,Ultra-thin & Ultra-light: The ultra slim fit p...,,11.98,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Bastmei,"Cell Phones & Accessories > Cases, Holsters & ...","{""Package Dimensions"": ""7.6 x 4.29 x 0.75 inch...",B07ZPSG8P5,Title: Bastmei for OnePlus 7T Case Extremely L...