In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
from dotenv import load_dotenv

In [3]:
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
import os

C:\Users\srush\AppData\Local\Temp\ipykernel_44424\1796376872.py:2: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.vectorstores import FAISS

In [4]:
load_dotenv()

True

In [5]:
print(os.getenv("OPENAI_API_KEY"))

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

In [7]:
#loading the cleaned datasets

metadata = pd.read_parquet(
    "../Data/Cleaned/metadata_clean.parquet"
)

reviews = pd.read_parquet(
    "../Data/Cleaned/reviews_clean.parquet"

)

In [8]:
metadata.columns

Index(['main_category', 'title', 'average_rating', 'rating_number', 'features',
       'description', 'price', 'images', 'videos', 'store', 'categories',
       'details', 'parent_asin', 'product_text'],
      dtype='object')

In [9]:
reviews.columns

Index(['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id',
       'timestamp', 'helpful_vote', 'verified_purchase', 'review_date'],
      dtype='object')

In [10]:
metadata.shape

(184070, 14)

Creating a sample with lesser data and products for faster processing

In [11]:
metadata_sample = metadata.sample(
    n=10000,
    random_state=42
).reset_index(drop=True)

In [12]:
reviews_sample = reviews[
    reviews["parent_asin"].isin(metadata_sample["parent_asin"])
].reset_index(drop=True)

In [13]:
metadata_sample.head(10)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,product_text
0,Cell Phones & Accessories,Njjex Case Compatible with Samsung Galaxy Note...,3.8,323,✦Njjex Heavy Duty Defender Combo Tank Clip Bel...,Features: 1.100% Brand New and good quality 2....,12.99,{'hi_res': ['https://m.media-amazon.com/images...,{'title': ['WallSkiN Turtle Series - Installat...,NJJEX,"Cell Phones & Accessories > Cases, Holsters & ...","{""Product Dimensions"": ""6.7 x 3.3 x 0.6 inches...",B07H919WPD,Title: Njjex Case Compatible with Samsung Gala...
1,Cell Phones & Accessories,Piano Purple Skin Soft Gel Case For Apple iPho...,5.0,1,,,NaN,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",NEXTKIN,Cell Phones & Accessories > iPhone Accessories,"{""Other display features"": ""Wireless"", ""Color""...",B00AV4NG5Q,Title: Piano Purple Skin Soft Gel Case For App...
2,Cell Phones & Accessories,"LG K20 Plus Case, LG K20 V Case, LG Harmony Ca...",4.1,68,,,NaN,"{'hi_res': [None, None, None], 'large': ['http...","{'title': [], 'url': [], 'user_id': []}",TJS,,"{""Product Dimensions"": ""9.09 x 5.79 x 1.1 inch...",B071463M7G,"Title: LG K20 Plus Case, LG K20 V Case, LG Har..."
3,AMAZON FASHION,"Aukvite Gizmo Watch Band Replacement for Kids,...",4.4,71,【Compatible Models】- Aukvite 20mm width classi...,★Know before buying: ★ ★1. Due to the elastici...,12.99,{'hi_res': ['https://m.media-amazon.com/images...,{'title': ['Gizmo Watch Replacement Bands for ...,Aukvite,Cell Phones & Accessories > Accessories > Smar...,"{""Department"": ""Boys"", ""Date First Available"":...",B0936GCLBQ,Title: Aukvite Gizmo Watch Band Replacement fo...
4,Cell Phones & Accessories,4-Piece Reversible Comforter Set Dots Giraffe ...,5.0,2,,,NaN,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Tiamat+,"Cell Phones & Accessories > Cases, Holsters & ...","{""Item model number"": ""Bedding Collections Dot...",B00KMCZ2QS,Title: 4-Piece Reversible Comforter Set Dots G...
5,All Electronics,"GORWRICH Mobile Phone Stand, Phone Tablet Hold...",3.6,8,【Universal &Compatibility】Universal Use: GORWR...,,7.99,{'hi_res': ['https://m.media-amazon.com/images...,{'title': ['Works only with small phones becau...,GORWRICH,Cell Phones & Accessories > Accessories > Stands,"{""Package Dimensions"": ""6.34 x 3.7 x 1.57 inch...",B08CZJ3919,"Title: GORWRICH Mobile Phone Stand, Phone Tabl..."
6,Cell Phones & Accessories,"Rui Yang Designed for iPhone 11 Case, Tempered...",3.5,6,Specially Designed for the iPhone 11 Pro (5.8 ...,,NaN,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Green Hills,"Cell Phones & Accessories > Cases, Holsters & ...","{""Product Dimensions"": ""5.65 x 2.8 x 0.3 inche...",B09BFNL6WL,"Title: Rui Yang Designed for iPhone 11 Case, T..."
7,Cell Phones & Accessories,"Galaxy S5 Case, NSSTAR Galaxy S5 [Liquid Bling...",3.9,18,,,NaN,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",ikasus,"Cell Phones & Accessories > Cases, Holsters & ...","{""Package Dimensions"": ""8.4 x 8.3 x 0.7 inches...",B015OBVCC4,"Title: Galaxy S5 Case, NSSTAR Galaxy S5 [Liqui..."
8,Cell Phones & Accessories,"caseen Note 4 Case, Note 4 Wallet Case, Ottimo...",3.8,74,Samsung Galaxy Note 4 wallet case has 3 credit...,Turquoise mint Note 4 case by caseen follows t...,NaN,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",caseen,,"{""Package Dimensions"": ""6.5 x 3.8 x 0.8 inches...",B00O4H2CC4,"Title: caseen Note 4 Case, Note 4 Wallet Case,..."
9,Cell Phones & Accessories,iPhone 7 Plus Phone Case - Encased [SlimShield...,4.3,3,,,NaN,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Encased,,"{""Package Dimensions"": ""3.1 x 0.8 x 0.2 inches...",B01LYK9SET,Title: iPhone 7 Plus Phone Case - Encased [Sli...

In [27]:
reviews_sample = reviews_sample.merge(
    metadata_sample[
        [
            "parent_asin",
            "title",
            "price",
            "average_rating",
            "rating_number"
        ]
    ],
    on="parent_asin",
    how="left"
)

In [30]:
reviews_sample.rename(
    columns={
        "title_x": "review_title",
        "title_y": "product_title"
    },
    inplace=True
)

In [32]:
# Put product_title as the second column
cols = reviews_sample.columns.tolist()

cols.remove("product_title")
cols.insert(1, "product_title")

reviews_sample = reviews_sample[cols]

In [36]:
reviews_sample.head(5)

,rating,product_title,review_title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,review_date,price,average_rating,rating_number
0,4.0,"Honsky Thumbs-up Phone Stand for Tablets, E-re...",Four Stars,Stocking stuffers for my boys & they liked them.,[],B00UKXP6Y2,B07CKPPSB4,AGXVBIUFLFGMVLATYXHJYL4A5Q7Q,1485870336000,0,True,2017-01-31 13:45:36.000,19.99,4.4,4307
1,5.0,Bling Diamond Case for Samsung Galaxy S10 Plus...,"Love, love and I get so many compliments!",Love this.....it's amazing and haven't lost an...,[],B07P9544RP,B09JSXJ7X3,AGBUJDDLRJIUJFTKPABJT6CJTHRQ,1576168322121,1,True,2019-12-12 16:32:02.121,11.98,4.3,1478
2,4.0,"SHENMZ LG V20 Battery,6800mAh (More Than 2X Ex...",Seein is believing that's only proof by one yo...,Really nothing I don't have to charge in a cou...,[],B07MW7ZQVN,B07MW7ZQVN,AFUZ5E7QAHSVTLIY253GFAYZPN2Q,1611422480932,0,True,2021-01-23 17:21:20.932,25.95,4.3,1109
3,5.0,Unov Pixel 3 Case Clear Soft TPU Shock Absorpt...,More durable than expected,Beautiful paint and stays on very well. Seems ...,[],B07XF34VRB,B07XH1QWJ7,AEVPPTMG43C6GWSR7I2UGRQN7WFQ,1611191271232,0,True,2021-01-21 01:07:51.232,8.39,4.5,1807
4,5.0,"USB Plug, USB Wall Charger 3 Pack, GiGreen Dua...",Does the job,Works fine.,[],B077B8D1S6,B0B5XKXVDZ,AE3Q6AEWP7Y7CH4N6IWEP4YBNP2A,1646078603429,0,True,2022-02-28 20:03:23.429,10.99,4.7,4536

In [37]:
#saving the sample datasets:

metadata_sample.to_parquet(
    "../Data/Cleaned/metadata_sample.parquet",
    index=False
)

reviews_sample.to_parquet(
    "../Data/Cleaned/reviews_sample.parquet",
    index=False
)

In [38]:
reviews_sample.head(5)

,rating,product_title,review_title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,review_date,price,average_rating,rating_number
0,4.0,"Honsky Thumbs-up Phone Stand for Tablets, E-re...",Four Stars,Stocking stuffers for my boys & they liked them.,[],B00UKXP6Y2,B07CKPPSB4,AGXVBIUFLFGMVLATYXHJYL4A5Q7Q,1485870336000,0,True,2017-01-31 13:45:36.000,19.99,4.4,4307
1,5.0,Bling Diamond Case for Samsung Galaxy S10 Plus...,"Love, love and I get so many compliments!",Love this.....it's amazing and haven't lost an...,[],B07P9544RP,B09JSXJ7X3,AGBUJDDLRJIUJFTKPABJT6CJTHRQ,1576168322121,1,True,2019-12-12 16:32:02.121,11.98,4.3,1478
2,4.0,"SHENMZ LG V20 Battery,6800mAh (More Than 2X Ex...",Seein is believing that's only proof by one yo...,Really nothing I don't have to charge in a cou...,[],B07MW7ZQVN,B07MW7ZQVN,AFUZ5E7QAHSVTLIY253GFAYZPN2Q,1611422480932,0,True,2021-01-23 17:21:20.932,25.95,4.3,1109
3,5.0,Unov Pixel 3 Case Clear Soft TPU Shock Absorpt...,More durable than expected,Beautiful paint and stays on very well. Seems ...,[],B07XF34VRB,B07XH1QWJ7,AEVPPTMG43C6GWSR7I2UGRQN7WFQ,1611191271232,0,True,2021-01-21 01:07:51.232,8.39,4.5,1807
4,5.0,"USB Plug, USB Wall Charger 3 Pack, GiGreen Dua...",Does the job,Works fine.,[],B077B8D1S6,B0B5XKXVDZ,AE3Q6AEWP7Y7CH4N6IWEP4YBNP2A,1646078603429,0,True,2022-02-28 20:03:23.429,10.99,4.7,4536

In [39]:
metadata_sample.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,product_text
0,Cell Phones & Accessories,Njjex Case Compatible with Samsung Galaxy Note...,3.8,323,✦Njjex Heavy Duty Defender Combo Tank Clip Bel...,Features: 1.100% Brand New and good quality 2....,12.99,{'hi_res': ['https://m.media-amazon.com/images...,{'title': ['WallSkiN Turtle Series - Installat...,NJJEX,"Cell Phones & Accessories > Cases, Holsters & ...","{""Product Dimensions"": ""6.7 x 3.3 x 0.6 inches...",B07H919WPD,Title: Njjex Case Compatible with Samsung Gala...
1,Cell Phones & Accessories,Piano Purple Skin Soft Gel Case For Apple iPho...,5.0,1,,,NaN,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",NEXTKIN,Cell Phones & Accessories > iPhone Accessories,"{""Other display features"": ""Wireless"", ""Color""...",B00AV4NG5Q,Title: Piano Purple Skin Soft Gel Case For App...
2,Cell Phones & Accessories,"LG K20 Plus Case, LG K20 V Case, LG Harmony Ca...",4.1,68,,,NaN,"{'hi_res': [None, None, None], 'large': ['http...","{'title': [], 'url': [], 'user_id': []}",TJS,,"{""Product Dimensions"": ""9.09 x 5.79 x 1.1 inch...",B071463M7G,"Title: LG K20 Plus Case, LG K20 V Case, LG Har..."
3,AMAZON FASHION,"Aukvite Gizmo Watch Band Replacement for Kids,...",4.4,71,【Compatible Models】- Aukvite 20mm width classi...,★Know before buying: ★ ★1. Due to the elastici...,12.99,{'hi_res': ['https://m.media-amazon.com/images...,{'title': ['Gizmo Watch Replacement Bands for ...,Aukvite,Cell Phones & Accessories > Accessories > Smar...,"{""Department"": ""Boys"", ""Date First Available"":...",B0936GCLBQ,Title: Aukvite Gizmo Watch Band Replacement fo...
4,Cell Phones & Accessories,4-Piece Reversible Comforter Set Dots Giraffe ...,5.0,2,,,NaN,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",Tiamat+,"Cell Phones & Accessories > Cases, Holsters & ...","{""Item model number"": ""Bedding Collections Dot...",B00KMCZ2QS,Title: 4-Piece Reversible Comforter Set Dots G...

In [40]:
metadata_sample[["title", "product_text"]].head()

,title,product_text
0,Njjex Case Compatible with Samsung Galaxy Note...,Title: Njjex Case Compatible with Samsung Gala...
1,Piano Purple Skin Soft Gel Case For Apple iPho...,Title: Piano Purple Skin Soft Gel Case For App...
2,"LG K20 Plus Case, LG K20 V Case, LG Harmony Ca...","Title: LG K20 Plus Case, LG K20 V Case, LG Har..."
3,"Aukvite Gizmo Watch Band Replacement for Kids,...",Title: Aukvite Gizmo Watch Band Replacement fo...
4,4-Piece Reversible Comforter Set Dots Giraffe ...,Title: 4-Piece Reversible Comforter Set Dots G...

Creating Langchain documents

In [41]:
documents = []

for _, row in metadata_sample.iterrows(): 
    documents.append(
        Document( 
            page_content=row["product_text"],
            
            metadata={
                "parent_asin": row["parent_asin"],
                "title" : row["title"],
                "price" : row["price"],
                "average_rating" : row["average_rating"],
                "rating_number" : row["rating_number"],
                "categories" : row["categories"]


            }
        )
    )

In [42]:
#checking documents

len(documents)

10000

In [43]:
print(documents[0].metadata)

{'parent_asin': 'B07H919WPD', 'title': 'Njjex Case Compatible with Samsung Galaxy Note 9, [Nbeck] Shockproof Heavy Duty Rugged Locking Swivel Holster Belt Clip Kickstand Full Body Hard Shell Phone Cover Case for Samsung Note 9 [Black]', 'price': 12.99, 'average_rating': 3.8, 'rating_number': 323, 'categories': 'Cell Phones & Accessories > Cases, Holsters & Sleeves > Holsters'}

Creating Embedding Model

In [44]:
embedding_model = OpenAIEmbeddings(
    model="text-embedding-3-small",
    
)

Generating FAISS Database

In [45]:
vector_db = FAISS.from_documents(
    documents,
    embedding_model
)

In [46]:
vector_db.save_local(
    "../Data/Cleaned/faiss_index"
)

In [47]:
vector_db = FAISS.load_local(
    "../Data/Cleaned/faiss_index",

    embedding_model,

    allow_dangerous_deserialization=True
)

In [48]:
query = " C type charger"

results = vector_db.similarity_search(

    query,

    k=5
)

In [49]:
for doc in results:

    print("="*80)

    print(doc.metadata["title"])

    print(doc.metadata["average_rating"])

    print(doc.metadata["price"])

    print()

================================================================================
Type C Charger, 2 Pack 25W PD USB C Wall Charger Super Fast Charging Block & 6ft Android Phone Charger Cable for Samsung Galaxy S23 S22 S21 S20 Plus Ultra, Note 20 10 9 8/ S10 S9 S8 Pixel 6 5 4 Pro XL
4.5
16.99

================================================================================
C3-Wireless-Car-Charger-SZSAGO 15W Fast Car Charging Auto Clamping Mount Windscreen Air Vent Mobile Phone Holder for iPhone 14/13/12/12 Pro Max/11/X/8, Note 10, Galaxy S20/S10/S9(Black)
3.3
26.99

================================================================================
Adaptive Fast Type C Charger Compatible Samsung Galaxy S21+ S21 Ultra 5G S9 S8 Plus S10 S10e S20 FE Note 8 9 10 20 Plus, 2 Pack Charging Adapter + 2 Pack 6.6ft USB-C Cables
4.4
12.98

================================================================================
Charger Cable Cord Compatible with Samsung Galaxy S8 S9 S10 Active Edge Plus Star Note 8/9,A3 A5 2017 A8 2018 Sony Xperia XZ XZ1 XZ2 Compact Premium XA1 XA2 Ultra L1 L2,5A Fast Charge/Charging Wire
3.8
nan

================================================================================
Android Charger
4.4
nan

Testing -->

In [50]:
results =vector_db.similarity_search_with_score(

    query,
    k=5,
)

for doc, score in results:
    
    print(doc.metadata["title"])

    print(score)

Type C Charger, 2 Pack 25W PD USB C Wall Charger Super Fast Charging Block & 6ft Android Phone Charger Cable for Samsung Galaxy S23 S22 S21 S20 Plus Ultra, Note 20 10 9 8/ S10 S9 S8 Pixel 6 5 4 Pro XL
0.9746913
C3-Wireless-Car-Charger-SZSAGO 15W Fast Car Charging Auto Clamping Mount Windscreen Air Vent Mobile Phone Holder for iPhone 14/13/12/12 Pro Max/11/X/8, Note 10, Galaxy S20/S10/S9(Black)
0.9813341
Adaptive Fast Type C Charger Compatible Samsung Galaxy S21+ S21 Ultra 5G S9 S8 Plus S10 S10e S20 FE Note 8 9 10 20 Plus, 2 Pack Charging Adapter + 2 Pack 6.6ft USB-C Cables
1.0009975
Charger Cable Cord Compatible with Samsung Galaxy S8 S9 S10 Active Edge Plus Star Note 8/9,A3 A5 2017 A8 2018 Sony Xperia XZ XZ1 XZ2 Compact Premium XA1 XA2 Ultra L1 L2,5A Fast Charge/Charging Wire
1.0032517
Android Charger
1.0095392

In [51]:
test_queries = [
    "Samsung phone with good camera",
    "Phone with long battery life",
    "Affordable smartphone under 20000",
    "Gaming phone with fast processor",
    "Phone with AMOLED display",
    "Samsung S24 protective case",
    "USB C charging cable",
    "Wireless Bluetooth earbuds"
]

for query in test_queries:

    print("=" * 100)
    print("QUERY:", query)

    results = vector_db.similarity_search_with_score(query, k=3)

    for doc, score in results:

        print("-" * 80)
        print("Title :", doc.metadata["title"])
        print("Rating:", doc.metadata["average_rating"])
        print("Price :", doc.metadata["price"])
        print("Score :", score)

====================================================================================================
QUERY: Samsung phone with good camera
--------------------------------------------------------------------------------
Title : Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 256GB, 8K Camera & Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom White (Renewed)
Rating: 4.1
Price : 470.0
Score : 1.0017588
--------------------------------------------------------------------------------
Title : SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G LTE Phone w/ 12MP Camera - Midnight Black
Rating: 4.0
Price : 279.99
Score : 1.0065277
--------------------------------------------------------------------------------
Title : Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black
Rating: 4.2
Price : nan
Score : 1.0076612
====================================================================================================
QUERY: Phone with long battery life
--------------------------------------------------------------------------------
Title : OUKITEL 8000mAh Large Battery 18W Flash Charge Outdoor Phone Android 10 4G 6+128GB Dual SIM Smartphone WP7 IP68 Rugged Cell Phone 6.56" FHD+ Display Unlocked Phone NFC OTG GPS Mobile Phone (Orange)
Rating: 3.8
Price : nan
Score : 1.0413024
--------------------------------------------------------------------------------
Title : HTC 74H01885-00M Thunderbolt 6400 Extended Battery with Door - 2750 MaH - Non-Retail Packaging - Black
Rating: 3.7
Price : 14.99
Score : 1.0559264
--------------------------------------------------------------------------------
Title : SHENMZ LG V20 Battery,6800mAh (More Than 2X Extra Battery Power) Replacement LG V20 Extended Battery BL-44E1F with Black TPU Case for LG H910 H918 VS995 LS997 Phone | LG V20 Battery Case
Rating: 4.3
Price : 25.95
Score : 1.0607767
====================================================================================================
QUERY: Affordable smartphone under 20000
--------------------------------------------------------------------------------
Title : POSH Revel S500a - 5.0", 4G, Android 4.4 Kit Kat, Dual-core, 4GB, 8MP Camera, Dual Sim Smartphone (Black)
Rating: 3.9
Price : nan
Score : 1.1373093
--------------------------------------------------------------------------------
Title : Huawei U8833/Y300 Android 4.1 Dual Core 1.0GHz 4.0 inch WVGA
Rating: 3.7
Price : nan
Score : 1.1400025
--------------------------------------------------------------------------------
Title : OUKITEL OK6000 Plus Unlocked Smartphones, 5.5inch, 4GB RAM 64GB ROM
Rating: 3.5
Price : nan
Score : 1.1454809
====================================================================================================
QUERY: Gaming phone with fast processor
--------------------------------------------------------------------------------
Title : Black Shark 4 Unlocked Phone, 5G Gaming Phone, Fast Charging 120W Cell Phone 12+256GB, 144Hz Snapdragon 870 Android Phone, 6.67" 48MP 4500mAh NFC Mobile Phone Global Version -Frost Grey
Rating: 4.4
Price : nan
Score : 0.94573295
--------------------------------------------------------------------------------
Title : Xiaomi Poco M4 PRO 5G + 4G Volte Global Unlocked GSM 6.6" Octa Core 50mp Camera (Not Verizon/Boost/Cricket CDMA) + Car Fast Car Charger Bundle (128GB+6GB, Yellow)
Rating: 4.4
Price : nan
Score : 1.1510506
--------------------------------------------------------------------------------
Title : Semiconductor Phone Cooler, Phone Cooling Case with Temperature Display&Adjustment, Mobile Phone Radiator with Dual Cooling Chips, 2.63-3.46 Inches Clip for Gaming, Livestreaming (Silver)
Rating: 3.2
Price : 9.75
Score : 1.1742511
====================================================================================================
QUERY: Phone with AMOLED display
--------------------------------------------------------------------------------
Title : OUKITEL 8000mAh Large Battery 18W Flash Charge Outdoor Phone Android 10 4G 6+128GB Dual SIM Smartphone WP7 IP68 Rugged Cell Phone 6.56" FHD+ Display Unlocked Phone NFC OTG GPS Mobile Phone (Orange)
Rating: 3.8
Price : nan
Score : 0.9609575
--------------------------------------------------------------------------------
Title : OUKITEL-WP8-Pro Smartphone Fingerprint Rugged Phones - 6.49”Display, 4/64GB Dual SIM IP68 Waterproof Unlocked Cell Phones, 16MP Triple Camera Face ID GPS NFC,US Version,AT&T,Orange
Rating: 3.7
Price : nan
Score : 0.998662
--------------------------------------------------------------------------------
Title : OUKITEL OK6000 Plus Unlocked Smartphones, 5.5inch, 4GB RAM 64GB ROM
Rating: 3.5
Price : nan
Score : 1.0018668
====================================================================================================
QUERY: Samsung S24 protective case
--------------------------------------------------------------------------------
Title : Samsung Electronics Galaxy S22 Clear Standing Cover, Protective Phone Case, Corner TPU Bumpers, PC Back Protection, Adjustable Viewing Angle, US Version, Transparent, (EF-JS901CTEGUS)
Rating: 4.6
Price : 19.95
Score : 0.780874
--------------------------------------------------------------------------------
Title : Samsung Galaxy S22 Ultra Phone Case, Anti-Scratch, Transparent Back Cover,High-Efficiency Buffer Material for Edge Protection.
Rating: 4.1
Price : nan
Score : 0.8124094
--------------------------------------------------------------------------------
Title : NN for Samsung Galaxy S20 Case, Built-in Screen Protector Full Body Waterproof Shockproof Case Support Wireless Charging with Transparent Hard PC + Soft TPU Silicone Protective Cover(S20 Blue)
Rating: 3.4
Price : nan
Score : 0.8165798
====================================================================================================
QUERY: USB C charging cable
--------------------------------------------------------------------------------
Title : USB C to USB Male Cable (2 Pack), Acessorz USB C (Type-C) to USB A (Type-A) Fast Charging Sync Connector OTG Adapter for Laptop/Wall Car Charger - Silver
Rating: 4.4
Price : nan
Score : 0.79624104
--------------------------------------------------------------------------------
Title : Huawei 1 Meter USB-C 5V2A Charging Data Cable (White)
Rating: 4.1
Price : nan
Score : 0.79709244
--------------------------------------------------------------------------------
Title : Charger Cable Cord Compatible with Samsung Galaxy S8 S9 S10 Active Edge Plus Star Note 8/9,A3 A5 2017 A8 2018 Sony Xperia XZ XZ1 XZ2 Compact Premium XA1 XA2 Ultra L1 L2,5A Fast Charge/Charging Wire
Rating: 3.8
Price : nan
Score : 0.82054293
====================================================================================================
QUERY: Wireless Bluetooth earbuds
--------------------------------------------------------------------------------
Title : Bluetooth Earpiece Wireless Headset with Microphone Hands-Free Earphones Headphones Noise Canceling Earbud Long Standby Time for Smart Mobile Phone Tablet PC Laptop Business Office Car Driver Trucker
Rating: 3.6
Price : nan
Score : 0.89293337
--------------------------------------------------------------------------------
Title : Bluetooth Headset,Wireless Earpiece Hands Free Stereo Headphones Business Earphones in-Ear Earbuds with Noise Canceling Mic for Business/Office/Driving Call, Work for iPhone/Samsung/Android
Rating: 3.7
Price : 13.99
Score : 0.9469148
--------------------------------------------------------------------------------
Title : Bluetooth Headset, Wireless Bluetooth Hands Free Earpiece with Noise Canceling Mic, LED Battery Display Case, Single Handsfree Earphones for Driving/Office, Compatible with iPhone, Android Cell Phone
Rating: 4.2
Price : 23.29
Score : 0.9505501