# Coordinated Multi-Agent Recommendation System

This notebook integrates:

1. Query Agent
2. Retrieval Agent
3. Review Agent
4. Ranking Agent
5. Verifier Agent

Pipeline:

User Query → Query Agent → Retrieval Agent → Review Agent →
Ranking Agent → Verifier Agent → Final Recommendations

In [1]:
import os
import sys
import time
import pandas as pd

from pathlib import Path
from dotenv import load_dotenv

from langchain_openai import (
    ChatOpenAI,
    OpenAIEmbeddings
)

from langchain_community.vectorstores import FAISS

C:\Users\srush\AppData\Local\Temp\ipykernel_21376\1471384404.py:14: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.vectorstores import FAISS

In [2]:
load_dotenv()

True

In [3]:
PROJECT_ROOT = Path("..").resolve()

In [4]:
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print("Project root:", PROJECT_ROOT)

Project root: C:\Users\srush\Desktop\Multi agent coordination

In [5]:
import Agents.verifier_agent as verifier_module

print(verifier_module.__file__)
print(
    [
        name
        for name in dir(verifier_module)
        if "Verifier" in name
    ]
)

C:\Users\srush\Desktop\Multi agent coordination\Agents\verifier_agent.py
['VerifierAgent', 'VerifierOutput']

In [6]:
from Agents.query_agent import QueryAgent
from Agents.review_agent import ReviewAgent
from Agents.ranking_agent import RankingAgent
from Agents.verifier_agent import VerifierAgent
from Agents.retrieval_agent import (
    RetrievalAgent,
    build_search_query,
    filter_products
)

print("All agent classes imported successfully.")

All agent classes imported successfully.

In [7]:
llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)

print("LLM initialised successfully.")

LLM initialised successfully.

In [8]:
reviews_path = (
    PROJECT_ROOT
    / "Data"
    / "Cleaned"
    / "reviews_sample.parquet"
)

if not reviews_path.exists():
    raise FileNotFoundError(
        f"Reviews file not found at: {reviews_path}"
    )

reviews_df = pd.read_parquet(reviews_path)

print("Reviews shape:", reviews_df.shape)
print("Review columns:", reviews_df.columns.tolist())

Reviews shape: (26031, 15)
Review columns: ['rating', 'product_title', 'review_title', 'text', 'images', 'asin', 'parent_asin', 'user_id', 'timestamp', 'helpful_vote', 'verified_purchase', 'review_date', 'price', 'average_rating', 'rating_number']

In [9]:
required_review_columns = {
    "parent_asin",
    "rating",
    "text"
}

missing_columns = (
    required_review_columns
    - set(reviews_df.columns)
)

if missing_columns:
    raise ValueError(
        f"Missing review columns: {missing_columns}"
    )

print("Required review columns are available.")

Required review columns are available.

In [10]:
embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small"
)

print("Embeddings initialised.")

Embeddings initialised.

In [11]:
faiss_path = (
    PROJECT_ROOT
    / "Data"
    / "Cleaned"
    / "faiss_index"
)

if not faiss_path.exists():
    raise FileNotFoundError(
        f"FAISS index not found at: {faiss_path}"
    )

vector_db = FAISS.load_local(
    folder_path=str(faiss_path),
    embeddings=embeddings,
    allow_dangerous_deserialization=True
)

print("FAISS vector database loaded.")

FAISS vector database loaded.

In [12]:
query_agent = QueryAgent()

retrieval_agent = RetrievalAgent(
    vector_db=vector_db
)

review_agent = ReviewAgent(
    llm=llm,
    reviews_df=reviews_df
)

ranking_agent = RankingAgent(
    llm=llm,
    explanation_limit=2,
    use_llm_explanations=True
)

verifier_agent = VerifierAgent(
    llm=llm,
    use_llm_summary=False
)

print("All five agents initialised successfully.")

All five agents initialised successfully.

In [13]:
#testing query agent: 

user_query = (
    "Recommend an Apple headphone with a good sound quality "
    "and long battery life."
)

structured_query = query_agent.parse(
    user_query
)

print(structured_query)

product_type='headset' brand='Apple' budget=None features=['good sound quality', 'long battery life']

In [14]:
#testing retrieval agent

retrieved_products = retrieval_agent.retrieve(
    query=structured_query,
    k=50
)

print(
    "Number of retrieved products:",
    len(retrieved_products)
)

Number of retrieved products: 3

In [15]:
#display results: 
for index, (document, score) in enumerate(
    retrieved_products,
    start=1
):
    print("=" * 80)
    print("Result:", index)
    print("Title:", document.metadata.get("title"))
    print(
        "Parent ASIN:",
        document.metadata.get("parent_asin")
    )
    print("Brand:", document.metadata.get("brand"))
    print("Price:", document.metadata.get("price"))
    print(
        "Average rating:",
        document.metadata.get("average_rating")
    )
    print("Retrieval score:", round(float(score), 4))

================================================================================
Result: 1
Title: vodbov Bluetooth Headset, Wireless earpiece for Business/Sport/Driver Noise Cancelling Mic Black Bluetooth Headphones Compatible with Apple Android Cell Phones,MacBook and Compatible with Alexa
Parent ASIN: B07GP25L9F
Brand: apple
Price: nan
Average rating: 3.9
Retrieval score: 0.4752
================================================================================
Result: 2
Title: Travel 3 in 1 Magsafe Wireless Charger, Foldable Wireless Charging Station for Apple, Wireless Charging Pad Compatible with iPhone 14 13 12 11/Pro/XS/XR,AirPods 3/2/Pro, iWatch 7/6/5/4/3/2
Parent ASIN: B0BLRVWPF2
Brand: apple
Price: 25.99
Average rating: 4.6
Retrieval score: 0.4546
================================================================================
Result: 3
Title: Foldable Wireless Charging Station for Multiple Devices Apple, 3 in 1 Wireless Charger for iPhone 13/12/11 Pro Max/X/Xs Max/8/8 Plus,for iWatch 7/6/5/4/3/2/se, AirPods 3/2/pro (Switchable Light)
Parent ASIN: B0BN5838R7
Brand: apple
Price: 21.99
Average rating: 4.1
Retrieval score: 0.4535

In [16]:
def enrich_products_with_reviews(
    retrieved_products: list,
    review_agent: ReviewAgent,
    max_reviews: int = 10
) -> list[dict]:

    enriched_products = []

    for document, retrieval_score in retrieved_products:

        metadata = document.metadata.copy()

        parent_asin = metadata.get("parent_asin")

        if not parent_asin:
            continue

        review_result = (
            review_agent.summarize_reviews(
                parent_asin=parent_asin,
                max_reviews=max_reviews
            )
        )

        enriched_product = {
            # Product identity
            "parent_asin": str(parent_asin),
            "title": str(
                metadata.get(
                    "title",
                    review_result.get(
                        "title",
                        "Unknown Product"
                    )
                )
            ),

            # Product metadata
            "brand": metadata.get("brand"),
            "product_type": metadata.get(
                "product_type"
            ),
            "price": metadata.get("price"),
            "categories": metadata.get(
                "categories"
            ),
            "product_text": document.page_content,

            # Retrieval evidence
            "retrieval_score": float(
                retrieval_score
            ),
            "similarity": metadata.get(
                "similarity",
                0
            ),

            # Product-level rating information
            "average_rating": float(
                metadata.get(
                    "average_rating",
                    review_result.get(
                        "average_rating",
                        0
                    )
                )
                or 0
            ),
            "rating_number": float(
                metadata.get(
                    "rating_number",
                    0
                )
                or 0
            ),

            # Review Agent output
            "review_count": review_result.get(
                "review_count",
                0
            ),
            "pros": review_result.get(
                "pros",
                []
            ),
            "cons": review_result.get(
                "cons",
                []
            ),
            "overall_sentiment": (
                review_result.get(
                    "overall_sentiment",
                    "Unknown"
                )
            ),
            "recommended_for": (
                review_result.get(
                    "recommended_for",
                    ""
                )
            ),
            "avoid_if": review_result.get(
                "avoid_if",
                ""
            ),
            "review_summary": review_result.get(
                "summary",
                ""
            ),
            "sample_reviews": review_result.get(
                "sample_reviews",
                ""
            )
        }

        enriched_products.append(
            enriched_product
        )

    return enriched_products

In [17]:
enriched_products = enrich_products_with_reviews(
    retrieved_products=retrieved_products,
    review_agent=review_agent,
    max_reviews=5
)

print(
    "Number of enriched products:",
    len(enriched_products)
)

Number of enriched products: 3

In [18]:
for index, product in enumerate(
    enriched_products,
    start=1
):
    print("=" * 80)
    print("Product:", index)
    print("Title:", product["title"])
    print(
        "Parent ASIN:",
        product["parent_asin"]
    )
    print(
        "Retrieval score:",
        round(product["retrieval_score"], 4)
    )
    print(
        "Average rating:",
        product["average_rating"]
    )
    print(
        "Review count:",
        product["review_count"]
    )
    print(
        "Sentiment:",
        product["overall_sentiment"]
    )
    print("Pros:", product["pros"])
    print("Cons:", product["cons"])
    print(
        "Review summary:",
        product["review_summary"]
    )

================================================================================
Product: 1
Title: vodbov Bluetooth Headset, Wireless earpiece for Business/Sport/Driver Noise Cancelling Mic Black Bluetooth Headphones Compatible with Apple Android Cell Phones,MacBook and Compatible with Alexa
Parent ASIN: B07GP25L9F
Retrieval score: 0.4752
Average rating: 3.9
Review count: 2
Sentiment: Mixed
Pros: ['Great backup option for other Bluetooth devices']
Cons: ['Poor sound quality with incorrect spoken English', 'Limited range', 'Overall cheap build quality']
Review summary: The vodbov Bluetooth Headset serves as a budget-friendly backup option but suffers from poor sound quality and limited range, making it less suitable for serious use.
================================================================================
Product: 2
Title: Travel 3 in 1 Magsafe Wireless Charger, Foldable Wireless Charging Station for Apple, Wireless Charging Pad Compatible with iPhone 14 13 12 11/Pro/XS/XR,AirPods 3/2/Pro, iWatch 7/6/5/4/3/2
Parent ASIN: B0BLRVWPF2
Retrieval score: 0.4546
Average rating: 4.6
Review count: 5
Sentiment: Positive
Pros: ['Compact and portable design', 'Ability to charge multiple devices simultaneously', 'Includes a power adapter and supports USB-C', 'Strong magnets keep devices securely in place', 'Good customer service experience']
Cons: ['Issues with activating the lifetime warranty', 'Some users experienced product failure within a month', 'Limited return window for defective products']
Review summary: The Travel 3 in 1 MagSafe Wireless Charger is a highly rated, compact charging solution ideal for Apple users. It allows simultaneous charging of multiple devices and is perfect for travel. However, some users have reported issues with durability and warranty activation.
================================================================================
Product: 3
Title: Foldable Wireless Charging Station for Multiple Devices Apple, 3 in 1 Wireless Charger for iPhone 13/12/11 Pro Max/X/Xs Max/8/8 Plus,for iWatch 7/6/5/4/3/2/se, AirPods 3/2/pro (Switchable Light)
Parent ASIN: B0BN5838R7
Retrieval score: 0.4535
Average rating: 4.1
Review count: 3
Sentiment: Mixed
Pros: ['Good for the money', 'Easy for travel']
Cons: ['Charges extremely slow', 'Watch and phone do not sit properly in the holder', 'Unreliable charging experience']
Review summary: The Foldable Wireless Charging Station offers portability and affordability but suffers from slow charging speeds and issues with device stability, making it less reliable for everyday use.

In [19]:
#running ranking agent

ranking_output = ranking_agent.rank_products(
    query=structured_query,
    products=enriched_products
)

print(ranking_output)

products=[RankedProduct(rank=1, parent_asin='B0BLRVWPF2', title='Travel 3 in 1 Magsafe Wireless Charger, Foldable Wireless Charging Station for Apple, Wireless Charging Pad Compatible with iPhone 14 13 12 11/Pro/XS/XR,AirPods 3/2/Pro, iWatch 7/6/5/4/3/2', average_rating=4.6, retrieval_score=0.45460320505695495, final_score=0.46124, reason='The Travel 3 in 1 MagSafe Wireless Charger is ranked first due to its compact design and ability to charge multiple devices simultaneously, which supports the requested feature of good sound quality indirectly by enhancing user experience with Apple devices. However, long battery life could not be verified from the available evidence.'), RankedProduct(rank=2, parent_asin='B0BN5838R7', title='Foldable Wireless Charging Station for Multiple Devices Apple, 3 in 1 Wireless Charger for iPhone 13/12/11 Pro Max/X/Xs Max/8/8 Plus,for iWatch 7/6/5/4/3/2/se, AirPods 3/2/pro (Switchable Light)', average_rating=4.1, retrieval_score=0.45353601702949853, final_score=0.413512, reason='The Foldable Wireless Charging Station is ranked second as it is noted for being good for the money and easy for travel, which may appeal to users looking for convenience. However, it charges extremely slow, and long battery life could not be verified from the available evidence.'), RankedProduct(rank=3, parent_asin='B07GP25L9F', title='vodbov Bluetooth Headset, Wireless earpiece for Business/Sport/Driver Noise Cancelling Mic Black Bluetooth Headphones Compatible with Apple Android Cell Phones,MacBook and Compatible with Alexa', average_rating=3.9, retrieval_score=0.475169034091271, final_score=0.409612, reason='Ranked using retrieval relevance, requested-feature evidence, customer sentiment, average rating and rating-volume popularity. Could not verify from the available evidence: good sound quality, long battery life. Available customer-review sentiment was mixed. The average rating was 3.9 out of 5.')]

In [20]:
for product in ranking_output.products:

    print("=" * 80)
    print("Rank:", product.rank)
    print("Title:", product.title)
    print(
        "Parent ASIN:",
        product.parent_asin
    )
    print(
        "Average rating:",
        product.average_rating
    )
    print(
        "Retrieval score:",
        round(product.retrieval_score, 4)
    )
    print(
        "Final score:",
        round(product.final_score, 4)
    )
    print("Reason:", product.reason)

================================================================================
Rank: 1
Title: Travel 3 in 1 Magsafe Wireless Charger, Foldable Wireless Charging Station for Apple, Wireless Charging Pad Compatible with iPhone 14 13 12 11/Pro/XS/XR,AirPods 3/2/Pro, iWatch 7/6/5/4/3/2
Parent ASIN: B0BLRVWPF2
Average rating: 4.6
Retrieval score: 0.4546
Final score: 0.4612
Reason: The Travel 3 in 1 MagSafe Wireless Charger is ranked first due to its compact design and ability to charge multiple devices simultaneously, which supports the requested feature of good sound quality indirectly by enhancing user experience with Apple devices. However, long battery life could not be verified from the available evidence.
================================================================================
Rank: 2
Title: Foldable Wireless Charging Station for Multiple Devices Apple, 3 in 1 Wireless Charger for iPhone 13/12/11 Pro Max/X/Xs Max/8/8 Plus,for iWatch 7/6/5/4/3/2/se, AirPods 3/2/pro (Switchable Light)
Parent ASIN: B0BN5838R7
Average rating: 4.1
Retrieval score: 0.4535
Final score: 0.4135
Reason: The Foldable Wireless Charging Station is ranked second as it is noted for being good for the money and easy for travel, which may appeal to users looking for convenience. However, it charges extremely slow, and long battery life could not be verified from the available evidence.
================================================================================
Rank: 3
Title: vodbov Bluetooth Headset, Wireless earpiece for Business/Sport/Driver Noise Cancelling Mic Black Bluetooth Headphones Compatible with Apple Android Cell Phones,MacBook and Compatible with Alexa
Parent ASIN: B07GP25L9F
Average rating: 3.9
Retrieval score: 0.4752
Final score: 0.4096
Reason: Ranked using retrieval relevance, requested-feature evidence, customer sentiment, average rating and rating-volume popularity. Could not verify from the available evidence: good sound quality, long battery life. Available customer-review sentiment was mixed. The average rating was 3.9 out of 5.

In [21]:
#running verifier agent:

verification_output = verifier_agent.verify(
    query=structured_query,
    ranking_output=ranking_output,
    original_products=enriched_products
)

print(verification_output)

overall_status='failed' confidence='low' verified_products=[ProductVerification(rank=1, parent_asin='B0BLRVWPF2', title='Travel 3 in 1 Magsafe Wireless Charger, Foldable Wireless Charging Station for Apple, Wireless Charging Pad Compatible with iPhone 14 13 12 11/Pro/XS/XR,AirPods 3/2/Pro, iWatch 7/6/5/4/3/2', status='failed', brand_match=True, product_type_match=False, feature_status='no_match', feature_match_ratio=0.0, matched_features=[], missing_features=['good sound quality', 'long battery life'], budget_verifiable=False, budget_match=None, evidence_strength='moderate', warnings=['The product may not match the requested product type or may be an accessory.', 'None of the requested features could be verified from the available evidence.', 'Missing feature evidence: good sound quality, long battery life'], verification_reason='Brand match: True. Product type match: False. Feature status: no_match. Feature match ratio: 0.00. Evidence strength: moderate. Price available: True. Budget requested: False. Budget match: None.'), ProductVerification(rank=2, parent_asin='B0BN5838R7', title='Foldable Wireless Charging Station for Multiple Devices Apple, 3 in 1 Wireless Charger for iPhone 13/12/11 Pro Max/X/Xs Max/8/8 Plus,for iWatch 7/6/5/4/3/2/se, AirPods 3/2/pro (Switchable Light)', status='failed', brand_match=True, product_type_match=False, feature_status='no_match', feature_match_ratio=0.0, matched_features=[], missing_features=['good sound quality', 'long battery life'], budget_verifiable=False, budget_match=None, evidence_strength='moderate', warnings=['The product may not match the requested product type or may be an accessory.', 'None of the requested features could be verified from the available evidence.', 'Missing feature evidence: good sound quality, long battery life'], verification_reason='Brand match: True. Product type match: False. Feature status: no_match. Feature match ratio: 0.00. Evidence strength: moderate. Price available: True. Budget requested: False. Budget match: None.'), ProductVerification(rank=3, parent_asin='B07GP25L9F', title='vodbov Bluetooth Headset, Wireless earpiece for Business/Sport/Driver Noise Cancelling Mic Black Bluetooth Headphones Compatible with Apple Android Cell Phones,MacBook and Compatible with Alexa', status='failed', brand_match=True, product_type_match=False, feature_status='partial_match', feature_match_ratio=0.5, matched_features=['good sound quality'], missing_features=['long battery life'], budget_verifiable=False, budget_match=None, evidence_strength='weak', warnings=['The product may not match the requested product type or may be an accessory.', 'Only some of the requested features were supported by the available evidence.', 'Missing feature evidence: long battery life', 'The recommendation has limited review evidence.'], verification_reason='Brand match: True. Product type match: False. Feature status: partial_match. Feature match ratio: 0.50. Evidence strength: weak. Price available: False. Budget requested: False. Budget match: None.')] recommended_product_asin=None recommended_product_title=None summary="Verification finished with status 'failed' and low confidence. All 3 products failed one or more critical checks, so no product could be recommended."

In [22]:
print(
    "Overall status:",
    verification_output.overall_status
)

print(
    "Confidence:",
    verification_output.confidence
)

print(
    "Recommended product:",
    verification_output.recommended_product_title
)

print(
    "Recommended ASIN:",
    verification_output.recommended_product_asin
)

print("\nSummary:")
print(verification_output.summary)

Overall status: failed
Confidence: low
Recommended product: None
Recommended ASIN: None

Summary:
Verification finished with status 'failed' and low confidence. All 3 products failed one or more critical checks, so no product could be recommended.

In [23]:
for product in verification_output.verified_products:

    print("=" * 80)
    print("Rank:", product.rank)
    print("Title:", product.title)
    print("Status:", product.status)
    print("Brand match:", product.brand_match)
    print(
        "Product type match:",
        product.product_type_match
    )
    print(
        "Feature status:",
        product.feature_status
    )
    print(
        "Feature match ratio:",
        product.feature_match_ratio
    )
    print(
        "Evidence strength:",
        product.evidence_strength
    )
    print("Warnings:", product.warnings)

================================================================================
Rank: 1
Title: Travel 3 in 1 Magsafe Wireless Charger, Foldable Wireless Charging Station for Apple, Wireless Charging Pad Compatible with iPhone 14 13 12 11/Pro/XS/XR,AirPods 3/2/Pro, iWatch 7/6/5/4/3/2
Status: failed
Brand match: True
Product type match: False
Feature status: no_match
Feature match ratio: 0.0
Evidence strength: moderate
Warnings: ['The product may not match the requested product type or may be an accessory.', 'None of the requested features could be verified from the available evidence.', 'Missing feature evidence: good sound quality, long battery life']
================================================================================
Rank: 2
Title: Foldable Wireless Charging Station for Multiple Devices Apple, 3 in 1 Wireless Charger for iPhone 13/12/11 Pro Max/X/Xs Max/8/8 Plus,for iWatch 7/6/5/4/3/2/se, AirPods 3/2/pro (Switchable Light)
Status: failed
Brand match: True
Product type match: False
Feature status: no_match
Feature match ratio: 0.0
Evidence strength: moderate
Warnings: ['The product may not match the requested product type or may be an accessory.', 'None of the requested features could be verified from the available evidence.', 'Missing feature evidence: good sound quality, long battery life']
================================================================================
Rank: 3
Title: vodbov Bluetooth Headset, Wireless earpiece for Business/Sport/Driver Noise Cancelling Mic Black Bluetooth Headphones Compatible with Apple Android Cell Phones,MacBook and Compatible with Alexa
Status: failed
Brand match: True
Product type match: False
Feature status: partial_match
Feature match ratio: 0.5
Evidence strength: weak
Warnings: ['The product may not match the requested product type or may be an accessory.', 'Only some of the requested features were supported by the available evidence.', 'Missing feature evidence: long battery life', 'The recommendation has limited review evidence.']

In [24]:
#making coordinated pipeline:

def run_coordinated_system(
    user_query: str,
    retrieval_k: int = 15,
    max_reviews: int = 3,
    verbose: bool = True
) -> dict:

    if not user_query or not user_query.strip():
        raise ValueError(
            "User query cannot be empty."
        )

    pipeline_start = time.perf_counter()

    # ============================================
    # 1. Query Agent
    # ============================================

    query_start = time.perf_counter()

    structured_query = query_agent.parse(
        user_query
    )

    query_latency = (
        time.perf_counter()
        - query_start
    )

    if verbose:
        print("=" * 100)
        print("1. QUERY AGENT")
        print("=" * 100)
        print(structured_query)
        print()

    # ============================================
    # 2. Retrieval Agent
    # ============================================

    retrieval_start = time.perf_counter()

    retrieved_products = (
        retrieval_agent.retrieve(
            query=structured_query,
            k=retrieval_k
        )
    )

    retrieval_latency = (
        time.perf_counter()
        - retrieval_start
    )

    if verbose:
        print("=" * 100)
        print("2. RETRIEVAL AGENT")
        print("=" * 100)
        print(
            "Retrieved products:",
            len(retrieved_products)
        )

        for document, score in retrieved_products:
            print(
                "-",
                document.metadata.get("title"),
                "| Score:",
                round(float(score), 4)
            )

        print()

    # ============================================
    # 3. Review Agent
    # ============================================

    review_start = time.perf_counter()

    enriched_products = (
        enrich_products_with_reviews(
            retrieved_products=(
                retrieved_products
            ),
            review_agent=review_agent,
            max_reviews=max_reviews
        )
    )

    review_latency = (
        time.perf_counter()
        - review_start
    )

    if verbose:
        print("=" * 100)
        print("3. REVIEW AGENT")
        print("=" * 100)
        print(
            "Products enriched:",
            len(enriched_products)
        )

        for product in enriched_products:
            print(
                "-",
                product["title"],
                "| Sentiment:",
                product["overall_sentiment"]
            )

        print()

    # Stop safely if retrieval produced no valid products
    if not enriched_products:

        total_latency = (
            time.perf_counter()
            - pipeline_start
        )

        return {
            "system": "coordinated_multi_agent",
            "user_query": user_query,
            "structured_query": structured_query,
            "retrieved_products": [],
            "enriched_products": [],
            "ranking_output": None,
            "verification_output": None,
            "latency": {
                "query_agent": round(
                    query_latency,
                    4
                ),
                "retrieval_agent": round(
                    retrieval_latency,
                    4
                ),
                "review_agent": round(
                    review_latency,
                    4
                ),
                "ranking_agent": 0,
                "verifier_agent": 0,
                "total": round(
                    total_latency,
                    4
                )
            },
            "error": (
                "No valid products were available "
                "after retrieval and review enrichment."
            )
        }

    # ============================================
    # 4. Ranking Agent
    # ============================================

    ranking_start = time.perf_counter()

    ranking_output = (
        ranking_agent.rank_products(
            query=structured_query,
            products=enriched_products
        )
    )

    ranking_latency = (
        time.perf_counter()
        - ranking_start
    )

    if verbose:
        print("=" * 100)
        print("4. RANKING AGENT")
        print("=" * 100)

        for product in ranking_output.products:
            print(
                f"{product.rank}. "
                f"{product.title} "
                f"| Final score: "
                f"{product.final_score:.4f}"
            )

        print()

    # ============================================
    # 5. Verifier Agent
    # ============================================

    verifier_start = time.perf_counter()

    verification_output = (
        verifier_agent.verify(
            query=structured_query,
            ranking_output=ranking_output,
            original_products=enriched_products
        )
    )

    verifier_latency = (
        time.perf_counter()
        - verifier_start
    )

    total_latency = (
        time.perf_counter()
        - pipeline_start
    )

    if verbose:
        print("=" * 100)
        print("5. VERIFIER AGENT")
        print("=" * 100)
        print(
            "Overall status:",
            verification_output.overall_status
        )
        print(
            "Confidence:",
            verification_output.confidence
        )
        print(
            "Recommended product:",
            verification_output
            .recommended_product_title
        )
        print()
        print(verification_output.summary)
        print()

        print("=" * 100)
        print("PIPELINE COMPLETED")
        print("=" * 100)
        print(
            f"Total latency: "
            f"{total_latency:.2f} seconds"
        )

    return {
        "system": "coordinated_multi_agent",
        "user_query": user_query,
        "structured_query": structured_query,
        "retrieved_products": retrieved_products,
        "enriched_products": enriched_products,
        "ranking_output": ranking_output,
        "verification_output": verification_output,
        "latency": {
            "query_agent": round(
                query_latency,
                4
            ),
            "retrieval_agent": round(
                retrieval_latency,
                4
            ),
            "review_agent": round(
                review_latency,
                4
            ),
            "ranking_agent": round(
                ranking_latency,
                4
            ),
            "verifier_agent": round(
                verifier_latency,
                4
            ),
            "total": round(
                total_latency,
                4
            )
        }
    }

In [25]:
# =====================================================
# FINAL COORDINATED MULTI-AGENT RUN
# =====================================================

from langchain_community.callbacks.manager import (
    get_openai_callback
)

import pandas as pd


FINAL_FOLDER = (
    PROJECT_ROOT
    / "Results"
    / "Final"
)


benchmark_df = pd.read_csv(
    FINAL_FOLDER
    / "final_60_query_benchmark.csv"
)


coord_final_rows = []


for _, test_case in benchmark_df.iterrows():

    test_id = int(
        test_case["test_id"]
    )

    user_query = str(
        test_case["user_query"]
    )

    print(
        "Coordinated:",
        test_id
    )


    try:

        with get_openai_callback() as cb:

            result = run_coordinated_system(
                user_query=user_query,
                retrieval_k=10,
                max_reviews=3,
                verbose=False
            )


        verification_output = result.get(
            "verification_output"
        )


        ranking_output = result.get(
            "ranking_output"
        )


        ranked_products = (
            ranking_output.products
            if ranking_output is not None
            else []
        )


        top_5_asins = [
            product.parent_asin
            for product
            in ranked_products[:5]
            if product.parent_asin
        ]


        top_5_titles = [
            product.title
            for product
            in ranked_products[:5]
            if product.title
        ]


        recommended_product = None
        recommended_asin = None
        overall_status = None
        confidence = None


        if verification_output is not None:

            recommended_product = (
                verification_output
                .recommended_product_title
            )

            recommended_asin = (
                verification_output
                .recommended_product_asin
            )

            overall_status = (
                verification_output
                .overall_status
            )

            confidence = (
                verification_output
                .confidence
            )


        coord_final_rows.append({

            "test_id":
                test_id,

            "category":
                test_case["category"],

            "user_query":
                user_query,

            "recommended_product":
                recommended_product,

            "recommended_asin":
                recommended_asin,

            "overall_status":
                overall_status,

            "confidence":
                confidence,

            "top_5_asins":
                "|".join(
                    top_5_asins
                ),

            "top_5_titles":
                " || ".join(
                    top_5_titles
                ),

            "total_latency":
                result[
                    "latency"
                ][
                    "total"
                ],

            "prompt_tokens":
                int(
                    cb.prompt_tokens
                ),

            "completion_tokens":
                int(
                    cb.completion_tokens
                ),

            "total_tokens":
                int(
                    cb.total_tokens
                ),

            "estimated_cost_usd":
                float(
                    cb.total_cost
                ),

            "error":
                result.get(
                    "error"
                )
        })


    except Exception as error:

        coord_final_rows.append({

            "test_id":
                test_id,

            "category":
                test_case["category"],

            "user_query":
                user_query,

            "recommended_product":
                None,

            "recommended_asin":
                None,

            "overall_status":
                "failed",

            "confidence":
                "low",

            "top_5_asins":
                "",

            "top_5_titles":
                "",

            "total_latency":
                0,

            "prompt_tokens":
                0,

            "completion_tokens":
                0,

            "total_tokens":
                0,

            "estimated_cost_usd":
                0,

            "error":
                str(error)
        })


coord_final_df = pd.DataFrame(
    coord_final_rows
)


display(
    coord_final_df
)


coord_final_df.to_csv(
    FINAL_FOLDER
    / "final_coordinated_results.csv",
    index=False
)


print(
    "Final Coordinated run complete."
)

Coordinated: 1
Coordinated: 2
Coordinated: 3
Coordinated: 4
Coordinated: 5
Coordinated: 6
Coordinated: 7
Coordinated: 8
Coordinated: 9
Coordinated: 10
Coordinated: 11
Coordinated: 12
Coordinated: 13
Coordinated: 14
Coordinated: 15
Coordinated: 16
Coordinated: 17
Coordinated: 18
Coordinated: 19
Coordinated: 20
Coordinated: 21
Coordinated: 22
Coordinated: 23
Coordinated: 24
Coordinated: 25
Coordinated: 26
Coordinated: 27
Coordinated: 28
Coordinated: 29
Coordinated: 30
Coordinated: 31
Coordinated: 32
Coordinated: 33
Coordinated: 34
Coordinated: 35
Coordinated: 36
Coordinated: 37
Coordinated: 38
Coordinated: 39
Coordinated: 40
Coordinated: 41
Coordinated: 42
Coordinated: 43
Coordinated: 44
Coordinated: 45
Coordinated: 46
Coordinated: 47
Coordinated: 48
Coordinated: 49
Coordinated: 50
Coordinated: 51
Coordinated: 52
Coordinated: 53
Coordinated: 54
Coordinated: 55
Coordinated: 56
Coordinated: 57
Coordinated: 58
Coordinated: 59
Coordinated: 60

,test_id,category,user_query,recommended_product,recommended_asin,overall_status,confidence,top_5_asins,top_5_titles,total_latency,prompt_tokens,completion_tokens,total_tokens,estimated_cost_usd,error
0,1,Brand Only,Recommend a Samsung phone.,Samsung Galaxy S5 SM-G900H Factory Unlocked Ce...,B00JKSUHLU,passed_with_warnings,medium,B00JKSUHLU|B00D93LOY6|B00LMJDP1Y|B00CGIULGC|B0...,Samsung Galaxy S5 SM-G900H Factory Unlocked Ce...,14.7049,3708,798,4506,0.001035,None
1,2,Brand Only,Recommend an Apple phone.,Apple iPhone 5 - 16GB (Black) Factory Unlocked,B00CX0OZHY,passed_with_warnings,medium,B00CX0OZHY,Apple iPhone 5 - 16GB (Black) Factory Unlocked,4.8089,1238,100,1338,0.000246,None
2,3,Brand Only,Suggest a Motorola smartphone.,Heart with Stars (Muti Color) Cell Phone Charm...,B004NULVAQ,passed_with_warnings,medium,B004NULVAQ|B001VF7LWI|B002VRO83K|B006P82YC8|B0...,Heart with Stars (Muti Color) Cell Phone Charm...,10.6493,2699,599,3298,0.000764,None
3,4,Brand Only,Recommend a Nokia phone.,Nokia E5-00 Unlocked GSM Phone with Easy Email...,B003X26SLM,passed_with_warnings,medium,B003X26SLM|B0055JQA46|B00UYAE1K6|B0014DGPZG,Nokia E5-00 Unlocked GSM Phone with Easy Email...,9.5178,2329,419,2748,0.000601,None
4,5,Brand Only,Suggest a Google phone.,"Google Pixel XL 128GB - 5.5"" Android GSM 4G LT...",B01M27MVQI,passed_with_warnings,medium,B01M27MVQI|B00INKCR14|B08BXBT8MD,"Google Pixel XL 128GB - 5.5"" Android GSM 4G LT...",6.8641,2045,320,2365,0.000499,None
5,6,Brand + Feature,Recommend a Samsung phone with a good camera.,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,B00D93LOY6,passed_with_warnings,medium,B00D93LOY6|B09C6N8P6Y|B00CGIULGC|B0B1QXHB7L|B0...,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,7.5794,2321,430,2751,0.000606,None
6,7,Brand + Feature,Recommend a Samsung phone with long battery life.,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",B09S6VKCLX,passed_with_warnings,medium,B09S6VKCLX|B09WT8N5X7|B09X9FC88M|B00JKSUHLU|B0...,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",5.9444,1798,288,2086,0.000442,None
7,8,Brand + Feature,Recommend an Apple phone with a good camera.,SteadyMate SM1 HD Professional Handheld Camera...,B00ORZVW42,passed_with_warnings,medium,B00ORZVW42,SteadyMate SM1 HD Professional Handheld Camera...,2.9600,1268,81,1349,0.000239,None
8,9,Brand + Feature,Suggest a Motorola phone with a good camera.,Motorola DROID A855 Android Phone (Verizon Wir...,B002VRO83K,passed_with_warnings,medium,B002VRO83K|B006P82YC8|B001COKAT4|B004P551BE|B0...,Motorola DROID A855 Android Phone (Verizon Wir...,3.2013,1403,139,1542,0.000294,None
9,10,Brand + Feature,Recommend a Samsung phone with fast performance.,Samsung Galaxy S5 SM-G900H Factory Unlocked Ce...,B00JKSUHLU,passed_with_warnings,medium,B00JKSUHLU|B00D93LOY6|B00LMJDP1Y|B09C6N8P6Y|B0...,Samsung Galaxy S5 SM-G900H Factory Unlocked Ce...,3.8741,1550,139,1689,0.000316,None
10,11,Brand + Feature,Recommend a Samsung phone for photography.,Samsung Galaxy S5 SM-G900H Factory Unlocked Ce...,B00JKSUHLU,passed_with_warnings,medium,B00JKSUHLU|B00D93LOY6|B00LMJDP1Y|B00CGIULGC|B0...,Samsung Galaxy S5 SM-G900H Factory Unlocked Ce...,3.0645,1549,160,1709,0.000328,None
11,12,Brand + Feature,Suggest a Samsung smartphone for gaming.,SAMSUNG Galaxy S21 FE 5G SM-G990U 256GB Factor...,B0BF1FZTLQ,passed_with_warnings,medium,B0BF1FZTLQ|B00LMJDP1Y|B00JKSUHLU|B00D93LOY6|B0...,SAMSUNG Galaxy S21 FE 5G SM-G990U 256GB Factor...,3.8886,1553,158,1711,0.000328,None
12,13,Brand + Feature,Recommend a Nokia phone with a good camera.,Nokia E5-00 Unlocked GSM Phone with Easy Email...,B003X26SLM,passed_with_warnings,medium,B003X26SLM|B0055JQA46|B00UYAE1K6|B0014DGPZG,Nokia E5-00 Unlocked GSM Phone with Easy Email...,3.1800,1561,144,1705,0.000321,None
13,14,Budget,Recommend a smartphone under 200.,Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked ...,B00CGIULGC,passed_with_warnings,medium,B00CGIULGC|B00O3PAN1E|B00NEEXCTK|B002VRO83K|B0...,Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked ...,9.3040,2315,442,2757,0.000612,None
14,15,Budget,Recommend a smartphone under 250.,Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked ...,B00CGIULGC,passed_with_warnings,medium,B00CGIULGC|B00O3PAN1E|B00NEEXCTK|B002VRO83K|B0...,Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked ...,3.5879,1565,141,1706,0.000319,None
15,16,Budget,Recommend a phone under 300.,Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked ...,B00CGIULGC,passed_with_warnings,medium,B00CGIULGC|B00O3PAN1E|B00NEEXCTK|B002VRO83K|B0...,Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked ...,3.0664,1565,138,1703,0.000318,None
16,17,Budget,Suggest a smartphone under 400.,Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked ...,B00CGIULGC,passed_with_warnings,medium,B00CGIULGC|B00O3PAN1E|B00NEEXCTK|B002VRO83K|B0...,Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked ...,3.1834,1565,138,1703,0.000318,None
17,18,Budget,Recommend a Samsung phone under 300.,Samsung Galaxy S3 Mini G730a 8GB Unlocked GSM ...,B00LMJDP1Y,passed_with_warnings,medium,B00LMJDP1Y|B00CGIULGC|B0B1QXHB7L|B00D93LOY6|B0...,Samsung Galaxy S3 Mini G730a 8GB Unlocked GSM ...,3.6783,1590,153,1743,0.000330,None
18,19,Budget,Recommend an Apple phone under 500.,None,None,passed_with_warnings,medium,B00CX0OZHY,Apple iPhone 5 - 16GB (Black) Factory Unlocked,2.7599,1244,95,1339,0.000244,None
19,20,Budget,Recommend a Motorola phone under 300.,None,None,passed_with_warnings,medium,B004NULVAQ|B001VF7LWI|B002VRO83K|B006P82YC8|B0...,Heart with Stars (Muti Color) Cell Phone Charm...,3.6884,1494,150,1644,0.000314,None
20,21,Feature Only,Recommend a phone with a great camera.,"POSH Revel S500a - 5.0"", 4G, Android 4.4 Kit K...",B00O3PAN1E,passed_with_warnings,medium,B00O3PAN1E|B00NEEXCTK|B00CGIULGC|B002VRO83K|B0...,"POSH Revel S500a - 5.0"", 4G, Android 4.4 Kit K...",7.3700,2660,423,3083,0.000653,None
21,22,Feature Only,Recommend a phone with long battery life.,OUKITEL 8000mAh Large Battery 18W Flash Charge...,B0995SX8X8,passed_with_warnings,medium,B07K9PR1H5|B0995SX8X8|B09L4QQCN2|B01LZ8516T|B0...,"OUKITEL OK6000 Plus Unlocked Smartphones, 5.5i...",8.3151,2250,390,2640,0.000571,None
22,23,Feature Only,Suggest a smartphone for gaming.,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",B09L4QQCN2,passed_with_warnings,medium,B09L4QQCN2|B0BLHCXZ8K|B00O3PAN1E|B00NEEXCTK|B0...,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",4.2943,1534,151,1685,0.000321,None
23,24,Feature Only,I need a phone for photography.,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,B00D93LOY6,passed_with_warnings,medium,B00D93LOY6|B00O3PAN1E|B00NEEXCTK|B00CGIULGC|B0...,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,6.7447,2349,333,2682,0.000552,None
24,25,Feature Only,Recommend a smartphone with fast performance.,"OUKITEL OK6000 Plus Unlocked Smartphones, 5.5i...",B07K9PR1H5,passed_with_warnings,medium,B07K9PR1H5|B00H92G0UG|B00NO80S3E|B07RB4ZH83|B0...,"OUKITEL OK6000 Plus Unlocked Smartphones, 5.5i...",5.5342,2439,295,2734,0.000543,None
25,26,Feature Only,Recommend a phone with fast charging.,None,None,None,None,,,2.4311,573,21,594,0.000099,No valid products were available after retriev...
26,27,Feature Only,Recommend a smartphone with good sound quality.,LG Electronics V20 - Factory Unlocked GSM Phon...,B078K4JQXC,passed_with_warnings,medium,B078K4JQXC|B00NO80S3E|B0006A0H4S|B008M0NS4U|B0...,LG Electronics V20 - Factory Unlocked GSM Phon...,8.7279,2182,428,2610,0.000584,None
27,28,Feature Only,Recommend a phone with large storage.,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",B09L4QQCN2,passed_with_warnings,medium,B09L4QQCN2|B08JPBCVBL|B0BBRBXPGC|B07K9PR1H5|B0...,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",5.4281,1989,276,2265,0.000464,None
28,29,Multiple Features,Recommend a phone with a good camera and long ...,"Samsung Galaxy S22 Smartphone, Factory Unlocke...",B09WT8N5X7,passed_with_warnings,medium,B09WT8N5X7|B002VRO83K|B08JPBCVBL|B09L4QQCN2|B0...,"Samsung Galaxy S22 Smartphone, Factory Unlocke...",3.7925,1445,120,1565,0.000289,None
29,30,Multiple Features,Recommend a smartphone with a good camera and ...,Alcatel One Fierce Prepaid Phone (MetroPCS),B00H92G0UG,passed_with_warnings,medium,B00H92G0UG|B00O3PAN1E|B00NO80S3E|B07K9PR1H5|B0...,Alcatel One Fierce Prepaid Phone (MetroPCS) ||...,3.4883,1557,143,1700,0.000319,None
30,31,Multiple Features,Recommend a phone with long battery life and f...,OUKITEL 8000mAh Large Battery 18W Flash Charge...,B0995SX8X8,passed_with_warnings,medium,B09L4QQCN2|B0995SX8X8,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",2.9708,1567,131,1698,0.000314,None
31,32,Multiple Features,Recommend a phone for gaming with long battery...,"SANSHREUNI Dual Sim Unlocked Cell Phones,4G+12...",B0BLHCXZ8K,passed_with_warnings,medium,B09L4QQCN2|B0BLHCXZ8K|B01LZ8516T|B00NO80S3E|B0...,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",3.8814,1541,139,1680,0.000315,None
32,33,Multiple Features,Recommend a phone for photography with large s...,"Ulefone Armor 15 Unlocked Rugged Phone, Built-...",B0BBRBXPGC,passed_with_warnings,medium,B0BBRBXPGC|B01M27MVQI|B08JPBCVBL|B0B1KJDM4L|B0...,"Ulefone Armor 15 Unlocked Rugged Phone, Built-...",3.2904,1582,143,1725,0.000323,None
33,34,Multiple Features,"Recommend a smartphone with a good camera, lon...","Samsung Galaxy S21 FE 5G Cell Phone, Factory U...",B0B1QXHB7L,passed_with_warnings,medium,B0B1QXHB7L|B09S6VKCLX|B09WT8N5X7|B07K9PR1H5|B0...,"Samsung Galaxy S21 FE 5G Cell Phone, Factory U...",4.4897,1481,166,1647,0.000322,None
34,35,Multiple Features,Recommend a phone with good sound quality and ...,LG Electronics V20 - Factory Unlocked GSM Phon...,B078K4JQXC,passed_with_warnings,medium,B078K4JQXC|B00NO80S3E|B09WT8N5X7|B09L4QQCN2|B0...,LG Electronics V20 - Factory Unlocked GSM Phon...,6.8806,1500,131,1631,0.000304,None
35,36,Multiple Features,Suggest a phone with fast charging and a good ...,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",B09L4QQCN2,passed_with_warnings,medium,B09L4QQCN2|B0995SX8X8,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",3.4442,1570,122,1692,0.000309,None
36,37,Complex,Recommend a Samsung phone under 300 with a goo...,"Samsung Galaxy A52 (5G) 128GB A526U 6.5"" Displ...",B09C6N8P6Y,passed_with_warnings,medium,B09C6N8P6Y|B00CGIULGC|B0B1QXHB7L|B00D93LOY6|B0...,"Samsung Galaxy A52 (5G) 128GB A526U 6.5"" Displ...",3.1743,1562,156,1718,0.000328,None
37,38,Complex,Recommend a Samsung phone under 400 with long ...,None,None,failed,low,B00CGIULGC|B004RZ2HWS,Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked ...,2.9029,1569,143,1712,0.000321,None
38,39,Complex,Recommend an Apple phone under 500 with a good...,None,None,passed_with_warnings,medium,B00ORZVW42,SteadyMate SM1 HD Professional Handheld Camera...,2.6209,1274,84,1358,0.000241,None
39,40,Complex,Recommend a Motorola phone under 300 with long...,None,None,passed_with_warnings,medium,B001VF7LWI|B002VRO83K|B001COKAT4|B006P82YC8|B0...,Motorola T505 Bluetooth Portable In-Car Speake...,2.9823,1449,115,1564,0.000286,None
40,41,Complex,Recommend a Samsung phone under 500 with a goo...,"Samsung Galaxy A52 (5G) 128GB A526U 6.5"" Displ...",B09C6N8P6Y,passed_with_warnings,medium,B00D93LOY6|B09C6N8P6Y|B00CGIULGC|B0BF1FZTLQ|B0...,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,3.2386,1590,159,1749,0.000334,None
41,42,Complex,Recommend a Samsung phone under 500 with a goo...,"Samsung Galaxy S21 FE 5G Cell Phone, Factory U...",B0B1QXHB7L,passed_with_warnings,medium,B0B1QXHB7L|B09WT8N5X7|B00CGIULGC|B00D93LOY6|B0...,"Samsung Galaxy S21 FE 5G Cell Phone, Factory U...",3.0098,1495,141,1636,0.000309,None
42,43,Ambiguous,Recommend the best Samsung phone.,Samsung Galaxy S5 SM-G900H Factory Unlocked Ce...,B00JKSUHLU,passed_with_warnings,medium,B00JKSUHLU|B00D93LOY6|B00LMJDP1Y|B00CGIULGC|B0...,Samsung Galaxy S5 SM-G900H Factory Unlocked Ce...,3.7741,1545,146,1691,0.000319,None
43,44,Ambiguous,I need something good for photography.,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,B00D93LOY6,passed_with_warnings,medium,B00D93LOY6|B00O3PAN1E|B00NEEXCTK|B00CGIULGC|B0...,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,4.7184,1587,154,1741,0.000330,None
44,45,Ambiguous,I need a phone that performs well.,"POSH Revel S500a - 5.0"", 4G, Android 4.4 Kit K...",B00O3PAN1E,passed_with_warnings,medium,B00O3PAN1E|B00NEEXCTK|B00CGIULGC|B002VRO83K|B0...,"POSH Revel S500a - 5.0"", 4G, Android 4.4 Kit K...",3.0892,1566,155,1721,0.000328,None
45,46,Ambiguous,Suggest a good phone for travelling.,CUBOT Quest 5.5-inch Android 9.0 Pie Rugged Sm...,B07RB4ZH83,passed_with_warnings,medium,B07RB4ZH83|B0B74J524C|B002S0OCHM|B00XM28BQ8|B0...,CUBOT Quest 5.5-inch Android 9.0 Pie Rugged Sm...,8.0800,2938,439,3377,0.000704,None
46,47,Ambiguous,I want a good all-round smartphone.,"POSH Revel S500a - 5.0"", 4G, Android 4.4 Kit K...",B00O3PAN1E,passed_with_warnings,medium,B00O3PAN1E|B00NEEXCTK|B00CGIULGC|B002VRO83K|B0...,"POSH Revel S500a - 5.0"", 4G, Android 4.4 Kit K...",3.7592,1566,152,1718,0.000326,None
47,48,Unsupported,Recommend an Apple phone with stylus support.,None,None,failed,low,B00ORZVW42,SteadyMate SM1 HD Professional Handheld Camera...,2.3571,1266,73,1339,0.000234,None
48,49,Unsupported,Recommend a Samsung phone with a removable bat...,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,B00D93LOY6,passed_with_warnings,medium,B00D93LOY6|B00JKSUHLU|B00CGIULGC|B09WT8N5X7|B0...,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,3.1903,1563,139,1702,0.000318,None
49,50,Unsupported,Recommend an Apple phone with a removable batt...,None,None,failed,low,B00CX0OZHY|B08RMRGR13,Apple iPhone 5 - 16GB (Black) Factory Unlocked...,3.3731,1460,183,1643,0.000329,None
50,51,Unsupported,Recommend a Samsung phone with stylus support ...,MChoice Precision Capacitive Stylus Touch Scre...,B07B7CWD9G,passed_with_warnings,medium,B00CGIULGC|B07B7CWD9G|B004RZ2HWS,Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked ...,3.3918,1478,176,1654,0.000327,None
51,52,Unsupported,Recommend a Google phone with a removable batt...,None,None,None,None,,,1.2432,575,22,597,0.000099,No valid products were available after retriev...
52,53,Unsupported,Recommend an Apple phone with wireless chargin...,None,None,None,None,,,1.2108,578,22,600,0.000100,No valid products were available after retriev...
53,54,No Match,Recommend a Nokia phone with an 8K camera and ...,None,None,failed,low,B003X26SLM|B00UYAE1K6,Nokia E5-00 Unlocked GSM Phone with Easy Email...,3.7692,1512,185,1697,0.000338,None
54,55,No Match,Recommend an Apple phone under 50.,None,None,passed_with_warnings,medium,B00CX0OZHY,Apple iPhone 5 - 16GB (Black) Factory Unlocked,3.7845,1244,111,1355,0.000253,None
55,56,No Match,Recommend a Samsung phone under 20 with a grea...,None,None,passed_with_warnings,medium,B00D93LOY6|B00K8CS822|B004RZ2HWS|B0734KKDMX|B0...,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,3.1764,1494,151,1645,0.000315,None
56,57,No Match,Recommend a Motorola phone with 1TB storage an...,None,None,failed,low,B002VRO83K|B001COKAT4|B006P82YC8|B004P551BE|B0...,Motorola DROID A855 Android Phone (Verizon Wir...,3.6862,1416,133,1549,0.000292,None
57,58,No Match,Recommend a Google phone under 50 with long ba...,None,None,None,None,,,1.2865,578,22,600,0.000100,No valid products were available after retriev...
58,59,No Match,Recommend an Apple phone with an 8K camera and...,None,None,failed,low,B00ORZVW42,SteadyMate SM1 HD Professional Handheld Camera...,5.1547,1277,86,1363,0.000243,None
59,60,No Match,Recommend a Samsung phone under 10 with 1TB st...,None,None,failed,low,B00D93LOY6|B0798KWR6Y|B078JRHXXT|B004RZ2HWS,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,5.3395,1899,277,2176,0.000451,None

Final Coordinated run complete.

In [26]:
# =====================================================
# TOKEN TRACKING - COORDINATED MULTI-AGENT
# =====================================================

from langchain_community.callbacks.manager import get_openai_callback
import pandas as pd


# Load the exact same 15 queries
test_queries_df = pd.read_csv(
    PROJECT_ROOT
    / "Results"
    / "coordinated_pipeline_test_results.csv"
)[["test_id", "user_query"]].drop_duplicates(
    subset=["test_id"]
).sort_values("test_id")


coordinated_token_rows = []

print("Queries loaded:", len(test_queries_df))


for _, row in test_queries_df.iterrows():

    test_id = int(row["test_id"])
    user_query = str(row["user_query"])

    print(
        "Running Coordinated Multi-Agent:",
        test_id
    )


    with get_openai_callback() as cb:

        result = run_coordinated_system(
            user_query=user_query,
            retrieval_k=10,
            max_reviews=3,
            verbose=False
        )


    coordinated_token_rows.append({
        "test_id": test_id,
        "system": "Coordinated Multi-Agent",
        "user_query": user_query,
        "prompt_tokens": int(cb.prompt_tokens),
        "completion_tokens": int(cb.completion_tokens),
        "total_tokens": int(cb.total_tokens),
        "estimated_cost_usd": float(cb.total_cost)
    })


coordinated_token_df = pd.DataFrame(
    coordinated_token_rows
)


display(
    coordinated_token_df
)


coordinated_token_df.to_csv(
    PROJECT_ROOT
    / "Results"
    / "coordinated_token_usage.csv",
    index=False
)


print(
    "Saved Coordinated Multi-Agent token results."
)

Queries loaded: 15
Running Coordinated Multi-Agent: 1
Running Coordinated Multi-Agent: 2
Running Coordinated Multi-Agent: 3
Running Coordinated Multi-Agent: 4
Running Coordinated Multi-Agent: 5
Running Coordinated Multi-Agent: 6
Running Coordinated Multi-Agent: 7
Running Coordinated Multi-Agent: 8
Running Coordinated Multi-Agent: 9
Running Coordinated Multi-Agent: 10
Running Coordinated Multi-Agent: 11
Running Coordinated Multi-Agent: 12
Running Coordinated Multi-Agent: 13
Running Coordinated Multi-Agent: 14
Running Coordinated Multi-Agent: 15

,test_id,system,user_query,prompt_tokens,completion_tokens,total_tokens,estimated_cost_usd
0,1,Coordinated Multi-Agent,Recommend a Samsung phone with a good camera a...,1475,147,1622,0.000309
1,2,Coordinated Multi-Agent,I want an Apple phone with excellent camera qu...,1270,79,1349,0.000238
2,3,Coordinated Multi-Agent,Suggest a Google phone with fast performance.,1540,115,1655,0.000300
3,4,Coordinated Multi-Agent,Recommend a Samsung phone under 300 with a goo...,1562,157,1719,0.000328
4,5,Coordinated Multi-Agent,Recommend a smartphone under 250 with long bat...,1525,149,1674,0.000318
5,6,Coordinated Multi-Agent,Recommend a phone with a great camera.,1572,136,1708,0.000317
6,7,Coordinated Multi-Agent,Recommend a phone with long battery life.,1540,132,1672,0.000310
7,8,Coordinated Multi-Agent,Suggest a smartphone for gaming.,1534,160,1694,0.000326
8,9,Coordinated Multi-Agent,"Recommend a Samsung phone with a good camera, ...",1570,151,1721,0.000326
9,10,Coordinated Multi-Agent,Recommend an Apple phone with a good camera an...,1713,227,1940,0.000393
10,11,Coordinated Multi-Agent,Recommend the best Samsung phone.,1545,148,1693,0.000321
11,12,Coordinated Multi-Agent,I need something good for photography.,1587,154,1741,0.000330
12,13,Coordinated Multi-Agent,Recommend an Apple phone with stylus support.,1266,73,1339,0.000234
13,14,Coordinated Multi-Agent,Recommend a Samsung phone with a removable bat...,1563,139,1702,0.000318
14,15,Coordinated Multi-Agent,Recommend a Nokia phone with an 8K camera and ...,1512,186,1698,0.000338

Saved Coordinated Multi-Agent token results.

In [27]:
result = run_coordinated_system(
    user_query=(
        "Recommend an apple headphone with a good sound quality"
        " and long battery life."
    ),
    retrieval_k=10,
    max_reviews=3,
    verbose=True
)

====================================================================================================
1. QUERY AGENT
====================================================================================================
product_type='headset' brand='Apple' budget=None features=['good sound quality', 'long battery life']

====================================================================================================
2. RETRIEVAL AGENT
====================================================================================================
Retrieved products: 1
- vodbov Bluetooth Headset, Wireless earpiece for Business/Sport/Driver Noise Cancelling Mic Black Bluetooth Headphones Compatible with Apple Android Cell Phones,MacBook and Compatible with Alexa | Score: 0.4752

====================================================================================================
3. REVIEW AGENT
====================================================================================================
Products enriched: 1
- vodbov Bluetooth Headset, Wireless earpiece for Business/Sport/Driver Noise Cancelling Mic Black Bluetooth Headphones Compatible with Apple Android Cell Phones,MacBook and Compatible with Alexa | Sentiment: Mixed

====================================================================================================
4. RANKING AGENT
====================================================================================================
1. vodbov Bluetooth Headset, Wireless earpiece for Business/Sport/Driver Noise Cancelling Mic Black Bluetooth Headphones Compatible with Apple Android Cell Phones,MacBook and Compatible with Alexa | Final score: 0.4096

====================================================================================================
5. VERIFIER AGENT
====================================================================================================
Overall status: failed
Confidence: low
Recommended product: None

Verification finished with status 'failed' and low confidence. All 1 products failed one or more critical checks, so no product could be recommended.

====================================================================================================
PIPELINE COMPLETED
====================================================================================================
Total latency: 2.91 seconds

In [28]:
result["structured_query"]

ProductQuery(product_type='headset', brand='Apple', budget=None, features=['good sound quality', 'long battery life'])

In [29]:
result["ranking_output"]

RankingOutput(products=[RankedProduct(rank=1, parent_asin='B07GP25L9F', title='vodbov Bluetooth Headset, Wireless earpiece for Business/Sport/Driver Noise Cancelling Mic Black Bluetooth Headphones Compatible with Apple Android Cell Phones,MacBook and Compatible with Alexa', average_rating=3.9, retrieval_score=0.475169034091271, final_score=0.409612, reason='The vodbov Bluetooth Headset ranks first due to its decent average rating of 3.9 and positive feedback as a backup option for Bluetooth devices. However, it lacks good sound quality, which is a requested feature, as noted in the review summary.')])

In [30]:
result["verification_output"]

VerifierOutput(overall_status='failed', confidence='low', verified_products=[ProductVerification(rank=1, parent_asin='B07GP25L9F', title='vodbov Bluetooth Headset, Wireless earpiece for Business/Sport/Driver Noise Cancelling Mic Black Bluetooth Headphones Compatible with Apple Android Cell Phones,MacBook and Compatible with Alexa', status='failed', brand_match=True, product_type_match=False, feature_status='partial_match', feature_match_ratio=0.5, matched_features=['good sound quality'], missing_features=['long battery life'], budget_verifiable=False, budget_match=None, evidence_strength='weak', warnings=['The product may not match the requested product type or may be an accessory.', 'Only some of the requested features were supported by the available evidence.', 'Missing feature evidence: long battery life', 'The recommendation has limited review evidence.'], verification_reason='Brand match: True. Product type match: False. Feature status: partial_match. Feature match ratio: 0.50. Evidence strength: weak. Price available: False. Budget requested: False. Budget match: None.')], recommended_product_asin=None, recommended_product_title=None, summary="Verification finished with status 'failed' and low confidence. All 1 products failed one or more critical checks, so no product could be recommended.")

In [31]:
result["latency"]

{'query_agent': 0.9587,
 'retrieval_agent': 0.3952,
 'review_agent': 0.0,
 'ranking_agent': 1.548,
 'verifier_agent': 0.002,
 'total': 2.9069}

### TESTING:

In [32]:
# =====================================================
# TEST QUERIES FOR COORDINATED PIPELINE
# =====================================================

test_queries = [

    # -----------------------------------------
    # Brand + feature queries
    # -----------------------------------------
    {
        "test_id": 1,
        "category": "Brand + Features",
        "query": (
            "Recommend a Samsung phone with a good camera "
            "and long battery life."
        )
    },

    {
        "test_id": 2,
        "category": "Brand + Features",
        "query": (
            "I want an Apple phone with excellent camera quality."
        )
    },

    {
        "test_id": 3,
        "category": "Brand + Features",
        "query": (
            "Suggest a Google phone with fast performance."
        )
    },

    # -----------------------------------------
    # Budget queries
    # -----------------------------------------
    {
        "test_id": 4,
        "category": "Budget",
        "query": (
            "Recommend a Samsung phone under 300 "
            "with a good camera."
        )
    },

    {
        "test_id": 5,
        "category": "Budget",
        "query": (
            "Recommend a smartphone under 250 "
            "with long battery life."
        )
    },

    # -----------------------------------------
    # Feature-only queries
    # -----------------------------------------
    {
        "test_id": 6,
        "category": "Feature Only",
        "query": (
            "Recommend a phone with a great camera."
        )
    },

    {
        "test_id": 7,
        "category": "Feature Only",
        "query": (
            "Recommend a phone with long battery life."
        )
    },

    {
        "test_id": 8,
        "category": "Feature Only",
        "query": (
            "Suggest a smartphone for gaming."
        )
    },

    # -----------------------------------------
    # Multi-feature queries
    # -----------------------------------------
    {
        "test_id": 9,
        "category": "Multiple Features",
        "query": (
            "Recommend a Samsung phone with a good camera, "
            "long battery life and fast performance."
        )
    },

    {
        "test_id": 10,
        "category": "Multiple Features",
        "query": (
            "Recommend an Apple phone with a good camera "
            "and large storage."
        )
    },

    # -----------------------------------------
    # Ambiguous queries
    # -----------------------------------------
    {
        "test_id": 11,
        "category": "Ambiguous",
        "query": (
            "Recommend the best Samsung phone."
        )
    },

    {
        "test_id": 12,
        "category": "Ambiguous",
        "query": (
            "I need something good for photography."
        )
    },

    # -----------------------------------------
    # Negative or difficult queries
    # -----------------------------------------
    {
        "test_id": 13,
        "category": "Negative",
        "query": (
            "Recommend an Apple phone with stylus support."
        )
    },

    {
        "test_id": 14,
        "category": "Negative",
        "query": (
            "Recommend a Samsung phone with a removable battery "
            "and an excellent camera."
        )
    },

    {
        "test_id": 15,
        "category": "No Match",
        "query": (
            "Recommend a Nokia phone with an 8K camera "
            "and 1TB storage."
        )
    }
]

In [33]:
test_case = test_queries[0]

result = run_coordinated_system(
    user_query=test_case["query"],
    retrieval_k=10,
    max_reviews=3,
    verbose=True
)

====================================================================================================
1. QUERY AGENT
====================================================================================================
product_type='smartphone' brand='Samsung' budget=None features=['good camera', 'long battery life', 'camera']

====================================================================================================
2. RETRIEVAL AGENT
====================================================================================================
Retrieved products: 8
- Samsung Galaxy S21 FE 5G Cell Phone, Factory Unlocked Android Smartphone, 128GB, 120Hz Display, Pro Grade Camera, All Day Intelligent Battery, (Olive Green) (Renewed) | Score: 0.6121
- Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 256GB, 8K Camera & Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom White (Renewed) | Score: 0.606
- SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Black - Unlocked (Renewed Premium) | Score: 0.6049
- Samsung Galaxy S5 SM-G900H Factory Unlocked Cellphone, International Version, Black | Score: 0.5535
- Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked Android Ruggedized Smart Phone | Score: 0.5399
- Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black | Score: 0.5394
- Samsung Galaxy S22 Ultra 256GB Unlocked ATT TMobile Verizon 100% batt! 7548400 | Score: 0.5262
- Samsung A797 Flight Unlocked Phone with QWERTY Keyboard, 2MP Camera and GPS - Grey | Score: 0.4793

====================================================================================================
3. REVIEW AGENT
====================================================================================================
Products enriched: 8
- Samsung Galaxy S21 FE 5G Cell Phone, Factory Unlocked Android Smartphone, 128GB, 120Hz Display, Pro Grade Camera, All Day Intelligent Battery, (Olive Green) (Renewed) | Sentiment: Unknown
- Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 256GB, 8K Camera & Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom White (Renewed) | Sentiment: Unknown
- SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Black - Unlocked (Renewed Premium) | Sentiment: Unknown
- Samsung Galaxy S5 SM-G900H Factory Unlocked Cellphone, International Version, Black | Sentiment: Positive
- Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked Android Ruggedized Smart Phone | Sentiment: Mixed
- Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black | Sentiment: Positive
- Samsung Galaxy S22 Ultra 256GB Unlocked ATT TMobile Verizon 100% batt! 7548400 | Sentiment: Unknown
- Samsung A797 Flight Unlocked Phone with QWERTY Keyboard, 2MP Camera and GPS - Grey | Sentiment: Mixed

====================================================================================================
4. RANKING AGENT
====================================================================================================
1. Samsung Galaxy S21 FE 5G Cell Phone, Factory Unlocked Android Smartphone, 128GB, 120Hz Display, Pro Grade Camera, All Day Intelligent Battery, (Olive Green) (Renewed) | Final score: 0.6805
2. SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Black - Unlocked (Renewed Premium) | Final score: 0.6680
3. Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 256GB, 8K Camera & Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom White (Renewed) | Final score: 0.6636
4. Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black | Final score: 0.6320
5. Samsung Galaxy S5 SM-G900H Factory Unlocked Cellphone, International Version, Black | Final score: 0.5873
6. Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked Android Ruggedized Smart Phone | Final score: 0.5807
7. Samsung Galaxy S22 Ultra 256GB Unlocked ATT TMobile Verizon 100% batt! 7548400 | Final score: 0.5560
8. Samsung A797 Flight Unlocked Phone with QWERTY Keyboard, 2MP Camera and GPS - Grey | Final score: 0.4392

====================================================================================================
5. VERIFIER AGENT
====================================================================================================
Overall status: passed_with_warnings
Confidence: medium
Recommended product: Samsung Galaxy S21 FE 5G Cell Phone, Factory Unlocked Android Smartphone, 128GB, 120Hz Display, Pro Grade Camera, All Day Intelligent Battery, (Olive Green) (Renewed)

Verification finished with status 'passed_with_warnings' and medium confidence. The highest-ranked valid recommendation is Samsung Galaxy S21 FE 5G Cell Phone, Factory Unlocked Android Smartphone, 128GB, 120Hz Display, Pro Grade Camera, All Day Intelligent Battery, (Olive Green) (Renewed). The verifier identified 0 failed product(s) and 13 warning(s) across the ranked results.

====================================================================================================
PIPELINE COMPLETED
====================================================================================================
Total latency: 3.45 seconds

In [34]:
# =====================================================
# RUN ALL TEST QUERIES
# =====================================================

import time
import pandas as pd


test_results = []

for test_case in test_queries:

    print("=" * 100)
    print(
        f"TEST {test_case['test_id']} "
        f"| {test_case['category']}"
    )
    print("=" * 100)
    print(test_case["query"])
    print()

    try:

        start_time = time.perf_counter()

        result = run_coordinated_system(
            user_query=test_case["query"],
            retrieval_k=10,
            max_reviews=3,
            verbose=False
        )

        execution_time = (
            time.perf_counter()
            - start_time
        )

        structured_query = result.get(
    "structured_query"
)

        ranking_output = result.get(
            "ranking_output"
        )

        ranked_products = (
            ranking_output.products
            if ranking_output is not None
            else []
        )

        verification_output = result.get(
            "verification_output"
        )


# =====================================================
# BUILD VERIFIED TOP-5 LIST
# =====================================================

        verified_products = (
                verification_output.verified_products
                if verification_output is not None
                else []
            )


            # Keep only products accepted by the Verifier Agent
        accepted_verified_products = [
                product
                for product in verified_products
                if str(product.status).strip().lower()
                in {
                    "passed",
                    "passed_with_warning",
                    "passed_with_warnings"
                }
            ]


            # Preserve their verified/ranking order
        accepted_verified_products = sorted(
                accepted_verified_products,
                key=lambda product: product.rank
            )


        verified_top_5 = (
                accepted_verified_products[:5]
            )


        top_5_asins = [
                product.parent_asin
                for product in verified_top_5
                if product.parent_asin
            ]


        top_5_titles = [
                product.title
                for product in verified_top_5
                if product.title
            ]

        retrieved_products = result.get(
                        "retrieved_products",
                        []
                    )
        # If verification returned no accepted products,
# keep the verified Top-5 columns empty.

        if not verified_top_5:

                top_5_asins = []
                top_5_titles = []

        if verification_output is not None:

            recommended_title = (
                verification_output.recommended_product_title
            )

            recommended_asin = (
                verification_output.recommended_product_asin
            )

            overall_status = (
                verification_output.overall_status
            )

            confidence = (
                verification_output.confidence
            )

        else:

            recommended_title = None
            recommended_asin = None
            overall_status = "no_result"
            confidence = "low"

        test_results.append(
            {
                "test_id": test_case["test_id"],
                "category": test_case["category"],
                "user_query": test_case["query"],

                "product_type": getattr(
                    structured_query,
                    "product_type",
                    None
                ),

                "brand": getattr(
                    structured_query,
                    "brand",
                    None
                ),

                "budget": getattr(
                    structured_query,
                    "budget",
                    None
                ),

                "features": ", ".join(
                    getattr(
                        structured_query,
                        "features",
                        []
                    ) or []
                ),

                "retrieved_count": len(
                    retrieved_products
                ),

                "ranked_count": len(
                    ranked_products
                ),

                "verified_count": len(
                    accepted_verified_products
                ),


                "recommended_product": recommended_title,
                "recommended_asin": recommended_asin,

                "top_5_asins": "|".join(
                    top_5_asins
                ),

                "top_5_titles": " || ".join(
                    top_5_titles
                ),

                "overall_status": overall_status,
                "confidence": confidence,

                "query_latency": result.get(
                    "latency",
                    {}
                ).get(
                    "query_agent",
                    0
                ),

                "retrieval_latency": result.get(
                    "latency",
                    {}
                ).get(
                    "retrieval_agent",
                    0
                ),

                "review_latency": result.get(
                    "latency",
                    {}
                ).get(
                    "review_agent",
                    0
                ),

                "ranking_latency": result.get(
                    "latency",
                    {}
                ).get(
                    "ranking_agent",
                    0
                ),

                "verifier_latency": result.get(
                    "latency",
                    {}
                ).get(
                    "verifier_agent",
                    0
                ),

                "total_latency": result.get(
                    "latency",
                    {}
                ).get(
                    "total",
                    execution_time
                ),

                "error": result.get("error")
            }
        )

        print(
            "Recommended:",
            recommended_title
        )

        print(
            "Status:",
            overall_status
        )

        print(
            "Latency:",
            round(execution_time, 2),
            "seconds"
        )

    except Exception as e:

        test_results.append(
            {
                "test_id": test_case["test_id"],
                "category": test_case["category"],
                "user_query": test_case["query"],

                "product_type": None,
                "brand": None,
                "budget": None,
                "features": None,

                "retrieved_count": 0,
                "ranked_count": 0,
                "verified_count": 0,

                "recommended_product": None,
                "recommended_asin": None,

                "top_5_asins": "",
                "top_5_titles": "",

                "overall_status": "error",
                "confidence": "low",

                "query_latency": 0,
                "retrieval_latency": 0,
                "review_latency": 0,
                "ranking_latency": 0,
                "verifier_latency": 0,
                "total_latency": 0,

                "error": str(e)
            }
        )

        print(
            "Error:",
            str(e)
        )

====================================================================================================
TEST 1 | Brand + Features
====================================================================================================
Recommend a Samsung phone with a good camera and long battery life.

Recommended: Samsung Galaxy S21 FE 5G Cell Phone, Factory Unlocked Android Smartphone, 128GB, 120Hz Display, Pro Grade Camera, All Day Intelligent Battery, (Olive Green) (Renewed)
Status: passed_with_warnings
Latency: 4.21 seconds
====================================================================================================
TEST 2 | Brand + Features
====================================================================================================
I want an Apple phone with excellent camera quality.

Recommended: SteadyMate SM1 HD Professional Handheld Camera Stabilizer for Apple iPhone 6 Plus, 6, 5S, 5C, 5, 4S and 4 Smart Phones
Status: passed_with_warnings
Latency: 2.55 seconds
====================================================================================================
TEST 3 | Brand + Features
====================================================================================================
Suggest a Google phone with fast performance.

Recommended: None
Status: failed
Latency: 3.58 seconds
====================================================================================================
TEST 4 | Budget
====================================================================================================
Recommend a Samsung phone under 300 with a good camera.

Recommended: Samsung Galaxy A52 (5G) 128GB A526U 6.5" Display Quad Camera Smartphone - Black (Renewed) (AT&T Unlocked)
Status: passed_with_warnings
Latency: 7.18 seconds
====================================================================================================
TEST 5 | Budget
====================================================================================================
Recommend a smartphone under 250 with long battery life.

Recommended: None
Status: passed_with_warnings
Latency: 4.31 seconds
====================================================================================================
TEST 6 | Feature Only
====================================================================================================
Recommend a phone with a great camera.

Recommended: POSH Revel S500a - 5.0", 4G, Android 4.4 Kit Kat, Dual-core, 4GB, 8MP Camera, Dual Sim Smartphone (Black)
Status: passed_with_warnings
Latency: 4.08 seconds
====================================================================================================
TEST 7 | Feature Only
====================================================================================================
Recommend a phone with long battery life.

Recommended: OUKITEL 8000mAh Large Battery 18W Flash Charge Outdoor Phone Android 10 4G 6+128GB Dual SIM Smartphone WP7 IP68 Rugged Cell Phone 6.56" FHD+ Display Unlocked Phone NFC OTG GPS Mobile Phone (Orange)
Status: passed_with_warnings
Latency: 3.92 seconds
====================================================================================================
TEST 8 | Feature Only
====================================================================================================
Suggest a smartphone for gaming.

Recommended: Black Shark 4 Unlocked Phone, 5G Gaming Phone, Fast Charging 120W Cell Phone 12+256GB, 144Hz Snapdragon 870 Android Phone, 6.67" 48MP 4500mAh NFC Mobile Phone Global Version -Frost Grey
Status: passed_with_warnings
Latency: 43.61 seconds
====================================================================================================
TEST 9 | Multiple Features
====================================================================================================
Recommend a Samsung phone with a good camera, long battery life and fast performance.

Recommended: Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black
Status: passed_with_warnings
Latency: 3.01 seconds
====================================================================================================
TEST 10 | Multiple Features
====================================================================================================
Recommend an Apple phone with a good camera and large storage.

Recommended: Apple iPhone 5 - 16GB (Black) Factory Unlocked
Status: passed_with_warnings
Latency: 2.81 seconds
====================================================================================================
TEST 11 | Ambiguous
====================================================================================================
Recommend the best Samsung phone.

Recommended: Samsung Galaxy S5 SM-G900H Factory Unlocked Cellphone, International Version, Black
Status: passed_with_warnings
Latency: 3.85 seconds
====================================================================================================
TEST 12 | Ambiguous
====================================================================================================
I need something good for photography.

Recommended: Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black
Status: passed_with_warnings
Latency: 3.21 seconds
====================================================================================================
TEST 13 | Negative
====================================================================================================
Recommend an Apple phone with stylus support.

Recommended: None
Status: failed
Latency: 2.69 seconds
====================================================================================================
TEST 14 | Negative
====================================================================================================
Recommend a Samsung phone with a removable battery and an excellent camera.

Recommended: Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black
Status: passed_with_warnings
Latency: 3.25 seconds
====================================================================================================
TEST 15 | No Match
====================================================================================================
Recommend a Nokia phone with an 8K camera and 1TB storage.

Recommended: None
Status: failed
Latency: 4.09 seconds

In [35]:
test_results_df = pd.DataFrame(
    test_results
)

display(
    test_results_df[
        [
            "test_id",
            "retrieved_count",
            "ranked_count",
            "verified_count",
            "recommended_product",
            "top_5_asins",
            "overall_status",
            "error"
        ]
    ]
)

,test_id,retrieved_count,ranked_count,verified_count,recommended_product,top_5_asins,overall_status,error
0,1,8,8,8,"Samsung Galaxy S21 FE 5G Cell Phone, Factory U...",B0B1QXHB7L|B09S6VKCLX|B09WT8N5X7|B00D93LOY6|B0...,passed_with_warnings,None
1,2,1,1,1,SteadyMate SM1 HD Professional Handheld Camera...,B00ORZVW42,passed_with_warnings,None
2,3,2,2,0,None,,failed,None
3,4,10,10,9,"Samsung Galaxy A52 (5G) 128GB A526U 6.5"" Displ...",B09C6N8P6Y|B00CGIULGC|B0B1QXHB7L|B00D93LOY6|B0...,passed_with_warnings,None
4,5,10,10,2,None,B0995SX8X8|B0BBRBXPGC,passed_with_warnings,None
5,6,10,10,10,"POSH Revel S500a - 5.0"", 4G, Android 4.4 Kit K...",B00O3PAN1E|B00NEEXCTK|B00CGIULGC|B002VRO83K|B0...,passed_with_warnings,None
6,7,10,10,2,OUKITEL 8000mAh Large Battery 18W Flash Charge...,B0995SX8X8|B0BBRBXPGC,passed_with_warnings,None
7,8,10,10,2,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",B09L4QQCN2|B0BLHCXZ8K,passed_with_warnings,None
8,9,10,10,10,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,B00D93LOY6|B00JKSUHLU|B0B1QXHB7L|B09S6VKCLX|B0...,passed_with_warnings,None
9,10,3,3,3,Apple iPhone 5 - 16GB (Black) Factory Unlocked,B00CX0OZHY|B00BUYRQG6|B00ORZVW42,passed_with_warnings,None
10,11,10,10,10,Samsung Galaxy S5 SM-G900H Factory Unlocked Ce...,B00JKSUHLU|B00D93LOY6|B00LMJDP1Y|B00CGIULGC|B0...,passed_with_warnings,None
11,12,10,10,10,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,B00D93LOY6|B00O3PAN1E|B00NEEXCTK|B00CGIULGC|B0...,passed_with_warnings,None
12,13,1,1,0,None,,failed,None
13,14,7,7,7,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,B00D93LOY6|B00JKSUHLU|B00CGIULGC|B09WT8N5X7|B0...,passed_with_warnings,None
14,15,2,2,0,None,,failed,None

In [36]:
validation_df = test_results_df[
    [
        "test_id",
        "retrieved_count",
        "ranked_count",
        "verified_count",
        "overall_status",
        "error"
    ]
].copy()

validation_df[
    "rejected_count"
] = (
    validation_df["ranked_count"]
    - validation_df["verified_count"]
)

display(validation_df)

,test_id,retrieved_count,ranked_count,verified_count,overall_status,error,rejected_count
0,1,8,8,8,passed_with_warnings,None,0
1,2,1,1,1,passed_with_warnings,None,0
2,3,2,2,0,failed,None,2
3,4,10,10,9,passed_with_warnings,None,1
4,5,10,10,2,passed_with_warnings,None,8
5,6,10,10,10,passed_with_warnings,None,0
6,7,10,10,2,passed_with_warnings,None,8
7,8,10,10,2,passed_with_warnings,None,8
8,9,10,10,10,passed_with_warnings,None,0
9,10,3,3,3,passed_with_warnings,None,0
10,11,10,10,10,passed_with_warnings,None,0
11,12,10,10,10,passed_with_warnings,None,0
12,13,1,1,0,failed,None,1
13,14,7,7,7,passed_with_warnings,None,0
14,15,2,2,0,failed,None,2

In [37]:
# =====================================================
# DISPLAY FINAL SUMMARY
# =====================================================

summary_columns = [
    "test_id",
    "category",
    "user_query",
    "product_type",
    "brand",
    "budget",
    "features",

    "retrieved_count",
    "ranked_count",
    "verified_count",

    "recommended_product",
    "recommended_asin",

    "top_5_asins",
    "top_5_titles",

    "overall_status",
    "confidence",
    "total_latency",
    "error"
]

display(
    test_results_df[
        summary_columns
    ]
)

,test_id,category,user_query,product_type,brand,budget,features,retrieved_count,ranked_count,verified_count,recommended_product,recommended_asin,top_5_asins,top_5_titles,overall_status,confidence,total_latency,error
0,1,Brand + Features,Recommend a Samsung phone with a good camera a...,smartphone,Samsung,NaN,"good camera, long battery life, camera",8,8,8,"Samsung Galaxy S21 FE 5G Cell Phone, Factory U...",B0B1QXHB7L,B0B1QXHB7L|B09S6VKCLX|B09WT8N5X7|B00D93LOY6|B0...,"Samsung Galaxy S21 FE 5G Cell Phone, Factory U...",passed_with_warnings,medium,4.2139,None
1,2,Brand + Features,I want an Apple phone with excellent camera qu...,smartphone,Apple,NaN,"excellent camera quality, camera",1,1,1,SteadyMate SM1 HD Professional Handheld Camera...,B00ORZVW42,B00ORZVW42,SteadyMate SM1 HD Professional Handheld Camera...,passed_with_warnings,medium,2.5485,None
2,3,Brand + Features,Suggest a Google phone with fast performance.,smartphone,Google,NaN,fast performance,2,2,0,None,None,,,failed,low,3.5827,None
3,4,Budget,Recommend a Samsung phone under 300 with a goo...,smartphone,Samsung,300.0,"good camera, camera",10,10,9,"Samsung Galaxy A52 (5G) 128GB A526U 6.5"" Displ...",B09C6N8P6Y,B09C6N8P6Y|B00CGIULGC|B0B1QXHB7L|B00D93LOY6|B0...,"Samsung Galaxy A52 (5G) 128GB A526U 6.5"" Displ...",passed_with_warnings,medium,7.1814,None
4,5,Budget,Recommend a smartphone under 250 with long bat...,smartphone,None,250.0,long battery life,10,10,2,None,None,B0995SX8X8|B0BBRBXPGC,OUKITEL 8000mAh Large Battery 18W Flash Charge...,passed_with_warnings,medium,4.3112,None
5,6,Feature Only,Recommend a phone with a great camera.,smartphone,None,NaN,"great camera, camera",10,10,10,"POSH Revel S500a - 5.0"", 4G, Android 4.4 Kit K...",B00O3PAN1E,B00O3PAN1E|B00NEEXCTK|B00CGIULGC|B002VRO83K|B0...,"POSH Revel S500a - 5.0"", 4G, Android 4.4 Kit K...",passed_with_warnings,medium,4.0805,None
6,7,Feature Only,Recommend a phone with long battery life.,smartphone,None,NaN,long battery life,10,10,2,OUKITEL 8000mAh Large Battery 18W Flash Charge...,B0995SX8X8,B0995SX8X8|B0BBRBXPGC,OUKITEL 8000mAh Large Battery 18W Flash Charge...,passed_with_warnings,medium,3.9159,None
7,8,Feature Only,Suggest a smartphone for gaming.,smartphone,None,NaN,gaming,10,10,2,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",B09L4QQCN2,B09L4QQCN2|B0BLHCXZ8K,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",passed_with_warnings,medium,43.6093,None
8,9,Multiple Features,"Recommend a Samsung phone with a good camera, ...",smartphone,Samsung,NaN,"good camera, long battery life, fast performan...",10,10,10,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,B00D93LOY6,B00D93LOY6|B00JKSUHLU|B0B1QXHB7L|B09S6VKCLX|B0...,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,passed_with_warnings,medium,3.0113,None
9,10,Multiple Features,Recommend an Apple phone with a good camera an...,smartphone,Apple,NaN,"good camera, large storage, camera",3,3,3,Apple iPhone 5 - 16GB (Black) Factory Unlocked,B00CX0OZHY,B00CX0OZHY|B00BUYRQG6|B00ORZVW42,Apple iPhone 5 - 16GB (Black) Factory Unlocked...,passed_with_warnings,medium,2.8133,None
10,11,Ambiguous,Recommend the best Samsung phone.,smartphone,Samsung,NaN,,10,10,10,Samsung Galaxy S5 SM-G900H Factory Unlocked Ce...,B00JKSUHLU,B00JKSUHLU|B00D93LOY6|B00LMJDP1Y|B00CGIULGC|B0...,Samsung Galaxy S5 SM-G900H Factory Unlocked Ce...,passed_with_warnings,medium,3.8511,None
11,12,Ambiguous,I need something good for photography.,smartphone,None,NaN,photography,10,10,10,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,B00D93LOY6,B00D93LOY6|B00O3PAN1E|B00NEEXCTK|B00CGIULGC|B0...,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,passed_with_warnings,medium,3.2098,None
12,13,Negative,Recommend an Apple phone with stylus support.,smartphone,Apple,NaN,stylus support,1,1,0,None,None,,,failed,low,2.6858,None
13,14,Negative,Recommend a Samsung phone with a removable bat...,smartphone,Samsung,NaN,"removable battery, excellent camera, camera",7,7,7,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,B00D93LOY6,B00D93LOY6|B00JKSUHLU|B00CGIULGC|B09WT8N5X7|B0...,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,passed_with_warnings,medium,3.2493,None
14,15,No Match,Recommend a Nokia phone with an 8K camera and ...,smartphone,Nokia,NaN,"8k camera, 1tb storage",2,2,0,None,None,,,failed,low,4.0888,None

In [38]:
# =====================================================
# SAVE UPDATED COORDINATED RESULTS
# =====================================================

from pathlib import Path

results_folder = (
    PROJECT_ROOT
    / "Results"
)

results_folder.mkdir(
    parents=True,
    exist_ok=True
)

output_path = (
    results_folder
    / "coordinated_pipeline_test_results.csv"
)

test_results_df.to_csv(
    output_path,
    index=False
)

print(
    "Results saved to:",
    output_path
)

Results saved to: C:\Users\srush\Desktop\Multi agent coordination\Results\coordinated_pipeline_test_results.csv

In [39]:
print("File exists:", output_path.exists())

saved_df = pd.read_csv(output_path)

print("Rows saved:", len(saved_df))

display(
    saved_df[
        [
            "test_id",
            "verified_count",
            "recommended_product",
            "overall_status",
            "confidence"
        ]
    ]
)

File exists: True
Rows saved: 15

,test_id,verified_count,recommended_product,overall_status,confidence
0,1,8,"Samsung Galaxy S21 FE 5G Cell Phone, Factory U...",passed_with_warnings,medium
1,2,1,SteadyMate SM1 HD Professional Handheld Camera...,passed_with_warnings,medium
2,3,0,NaN,failed,low
3,4,9,"Samsung Galaxy A52 (5G) 128GB A526U 6.5"" Displ...",passed_with_warnings,medium
4,5,2,NaN,passed_with_warnings,medium
5,6,10,"POSH Revel S500a - 5.0"", 4G, Android 4.4 Kit K...",passed_with_warnings,medium
6,7,2,OUKITEL 8000mAh Large Battery 18W Flash Charge...,passed_with_warnings,medium
7,8,2,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",passed_with_warnings,medium
8,9,10,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,passed_with_warnings,medium
9,10,3,Apple iPhone 5 - 16GB (Black) Factory Unlocked,passed_with_warnings,medium
10,11,10,Samsung Galaxy S5 SM-G900H Factory Unlocked Ce...,passed_with_warnings,medium
11,12,10,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,passed_with_warnings,medium
12,13,0,NaN,failed,low
13,14,7,Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM...,passed_with_warnings,medium
14,15,0,NaN,failed,low

In [40]:
# =====================================================
# CONFIRM SAVED FILE
# =====================================================

saved_coordinated_df = pd.read_csv(
    output_path
)

required_columns = [
    "verified_count",
    "top_5_asins",
    "top_5_titles"
]

print(
    saved_coordinated_df[
        required_columns
    ].head()
)

print(
    "Saved rows:",
    len(saved_coordinated_df)
)

   verified_count                                        top_5_asins  \
0               8  B0B1QXHB7L|B09S6VKCLX|B09WT8N5X7|B00D93LOY6|B0...
1               1                                         B00ORZVW42
2               0                                                NaN
3               9  B09C6N8P6Y|B00CGIULGC|B0B1QXHB7L|B00D93LOY6|B0...
4               2                              B0995SX8X8|B0BBRBXPGC

                                        top_5_titles
0  Samsung Galaxy S21 FE 5G Cell Phone, Factory U...
1  SteadyMate SM1 HD Professional Handheld Camera...
2                                                NaN
3  Samsung Galaxy A52 (5G) 128GB A526U 6.5" Displ...
4  OUKITEL 8000mAh Large Battery 18W Flash Charge...
Saved rows: 15

In [41]:
# =====================================================
# DIAGNOSE TEST 8: GAMING QUERY
# =====================================================

gaming_result = run_coordinated_system(
    user_query="Suggest a smartphone for gaming.",
    retrieval_k=10,
    max_reviews=3,
    verbose=False
)

structured_query = gaming_result[
    "structured_query"
]

print("=" * 80)
print("STRUCTURED QUERY")
print("=" * 80)

if hasattr(
    structured_query,
    "model_dump"
):
    print(
        structured_query.model_dump()
    )
else:
    print(
        structured_query
    )


print()
print("=" * 80)
print("RETRIEVED PRODUCTS")
print("=" * 80)

for rank, (
    document,
    score
) in enumerate(
    gaming_result.get(
        "retrieved_products",
        []
    ),
    start=1
):

    print(
        rank,
        "|",
        document.metadata.get(
            "parent_asin"
        ),
        "|",
        document.metadata.get(
            "title"
        ),
        "| score:",
        round(
            float(score),
            4
        )
    )


print()
print("=" * 80)
print("RANKED PRODUCTS")
print("=" * 80)

ranking_output = gaming_result.get(
    "ranking_output"
)

if ranking_output is not None:

    for product in (
        ranking_output.products
    ):

        print(
            product.rank,
            "|",
            product.parent_asin,
            "|",
            product.title,
            "| final score:",
            round(
                product.final_score,
                4
            )
        )


print()
print("=" * 80)
print("VERIFIED PRODUCTS")
print("=" * 80)

verification_output = gaming_result.get(
    "verification_output"
)

if verification_output is not None:

    for product in (
        verification_output
        .verified_products
    ):

        print(
            product.rank,
            "|",
            product.parent_asin,
            "|",
            product.title,
            "| status:",
            product.status
        )

================================================================================
STRUCTURED QUERY
================================================================================
{'product_type': 'smartphone', 'brand': None, 'budget': None, 'features': ['gaming']}

================================================================================
RETRIEVED PRODUCTS
================================================================================
1 | B09L4QQCN2 | Black Shark 4 Unlocked Phone, 5G Gaming Phone, Fast Charging 120W Cell Phone 12+256GB, 144Hz Snapdragon 870 Android Phone, 6.67" 48MP 4500mAh NFC Mobile Phone Global Version -Frost Grey | score: 0.6329
2 | B0BLHCXZ8K | SANSHREUNI Dual Sim Unlocked Cell Phones,4G+128GB C21 Ultra Smartphone, 6.8 inch Waterdrop Screen Android Phone, 5000mAh Battery, 24+50 MP Unlocked Cell Phone, Fingerprint Lock & Face ID Mobile Phone | score: 0.5417
3 | B00NEEXCTK | Huawei Ascend G7 16GB GSM Unlocked Android Smartphone w/ 13MP Camera, 5.5" IPS LCD Display, Quad-Core CPU - White/Silver | score: 0.4675
4 | B00NO80S3E | HTC Deluxe - 4G LTE GSM Factory Unlocked, 5" Android Smartphone with Beats Audio - Black | score: 0.4561
5 | B002VRO83K | Motorola DROID A855 Android Phone (Verizon Wireless) | score: 0.4517
6 | B00CGIULGC | Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked Android Ruggedized Smart Phone | score: 0.4511
7 | B0BBRBXPGC | Ulefone Armor 15 Unlocked Rugged Phone, Built-in Earbuds, Android 12, 6600mAh Battery, 8-Core Processor 6GB+128GB, 12MP+13MP Dual Main Camera, Dual SIM, 3-Card Slot T-Mobile Rugged Smartphone (Blue) | score: 0.4502
8 | B00O3PAN1E | POSH Revel S500a - 5.0", 4G, Android 4.4 Kit Kat, Dual-core, 4GB, 8MP Camera, Dual Sim Smartphone (Black) | score: 0.4467
9 | B07RB4ZH83 | CUBOT Quest 5.5-inch Android 9.0 Pie Rugged Smartphone Unlocked, 4GB+64GB,4G Dual SIM, NFC,Gyroscope, 4000mAh Battery, 12MP Camera, IP68 Waterproof Shockproof, Dustproof (Black) | score: 0.4443
10 | B00OSLAA52 | BLU Dash 5.5 Smartphone - Unlocked - Retail Packaging - (Pink) | score: 0.4334

================================================================================
RANKED PRODUCTS
================================================================================
1 | B09L4QQCN2 | Black Shark 4 Unlocked Phone, 5G Gaming Phone, Fast Charging 120W Cell Phone 12+256GB, 144Hz Snapdragon 870 Android Phone, 6.67" 48MP 4500mAh NFC Mobile Phone Global Version -Frost Grey | final score: 0.706
2 | B0BLHCXZ8K | SANSHREUNI Dual Sim Unlocked Cell Phones,4G+128GB C21 Ultra Smartphone, 6.8 inch Waterdrop Screen Android Phone, 5000mAh Battery, 24+50 MP Unlocked Cell Phone, Fingerprint Lock & Face ID Mobile Phone | final score: 0.6012
3 | B00O3PAN1E | POSH Revel S500a - 5.0", 4G, Android 4.4 Kit Kat, Dual-core, 4GB, 8MP Camera, Dual Sim Smartphone (Black) | final score: 0.4457
4 | B00NEEXCTK | Huawei Ascend G7 16GB GSM Unlocked Android Smartphone w/ 13MP Camera, 5.5" IPS LCD Display, Quad-Core CPU - White/Silver | final score: 0.427
5 | B00NO80S3E | HTC Deluxe - 4G LTE GSM Factory Unlocked, 5" Android Smartphone with Beats Audio - Black | final score: 0.411
6 | B00CGIULGC | Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked Android Ruggedized Smart Phone | final score: 0.403
7 | B002VRO83K | Motorola DROID A855 Android Phone (Verizon Wireless) | final score: 0.3995
8 | B07RB4ZH83 | CUBOT Quest 5.5-inch Android 9.0 Pie Rugged Smartphone Unlocked, 4GB+64GB,4G Dual SIM, NFC,Gyroscope, 4000mAh Battery, 12MP Camera, IP68 Waterproof Shockproof, Dustproof (Black) | final score: 0.3931
9 | B0BBRBXPGC | Ulefone Armor 15 Unlocked Rugged Phone, Built-in Earbuds, Android 12, 6600mAh Battery, 8-Core Processor 6GB+128GB, 12MP+13MP Dual Main Camera, Dual SIM, 3-Card Slot T-Mobile Rugged Smartphone (Blue) | final score: 0.3871
10 | B00OSLAA52 | BLU Dash 5.5 Smartphone - Unlocked - Retail Packaging - (Pink) | final score: 0.3824

================================================================================
VERIFIED PRODUCTS
================================================================================
1 | B09L4QQCN2 | Black Shark 4 Unlocked Phone, 5G Gaming Phone, Fast Charging 120W Cell Phone 12+256GB, 144Hz Snapdragon 870 Android Phone, 6.67" 48MP 4500mAh NFC Mobile Phone Global Version -Frost Grey | status: passed_with_warning
2 | B0BLHCXZ8K | SANSHREUNI Dual Sim Unlocked Cell Phones,4G+128GB C21 Ultra Smartphone, 6.8 inch Waterdrop Screen Android Phone, 5000mAh Battery, 24+50 MP Unlocked Cell Phone, Fingerprint Lock & Face ID Mobile Phone | status: passed_with_warning
3 | B00O3PAN1E | POSH Revel S500a - 5.0", 4G, Android 4.4 Kit Kat, Dual-core, 4GB, 8MP Camera, Dual Sim Smartphone (Black) | status: failed
4 | B00NEEXCTK | Huawei Ascend G7 16GB GSM Unlocked Android Smartphone w/ 13MP Camera, 5.5" IPS LCD Display, Quad-Core CPU - White/Silver | status: failed
5 | B00NO80S3E | HTC Deluxe - 4G LTE GSM Factory Unlocked, 5" Android Smartphone with Beats Audio - Black | status: failed
6 | B00CGIULGC | Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked Android Ruggedized Smart Phone | status: failed
7 | B002VRO83K | Motorola DROID A855 Android Phone (Verizon Wireless) | status: failed
8 | B07RB4ZH83 | CUBOT Quest 5.5-inch Android 9.0 Pie Rugged Smartphone Unlocked, 4GB+64GB,4G Dual SIM, NFC,Gyroscope, 4000mAh Battery, 12MP Camera, IP68 Waterproof Shockproof, Dustproof (Black) | status: failed
9 | B0BBRBXPGC | Ulefone Armor 15 Unlocked Rugged Phone, Built-in Earbuds, Android 12, 6600mAh Battery, 8-Core Processor 6GB+128GB, 12MP+13MP Dual Main Camera, Dual SIM, 3-Card Slot T-Mobile Rugged Smartphone (Blue) | status: failed
10 | B00OSLAA52 | BLU Dash 5.5 Smartphone - Unlocked - Retail Packaging - (Pink) | status: failed

In [42]:
# =====================================================
# CHECK WHETHER BLACK SHARK EXISTS IN FAISS
# =====================================================

exact_results = vector_db.similarity_search_with_score(
    "Black Shark 4 5G Gaming Phone",
    k=50
)

black_shark_matches = []

for document, score in exact_results:

    asin = str(
        document.metadata.get(
            "parent_asin",
            ""
        )
    ).strip()

    title = str(
        document.metadata.get(
            "title",
            ""
        )
    ).strip()

    if (
        asin == "B09L4QQCN2"
        or "black shark" in title.lower()
    ):
        black_shark_matches.append(
            {
                "parent_asin": asin,
                "title": title,
                "score": float(score)
            }
        )

print(
    "Black Shark matches found:",
    len(black_shark_matches)
)

for match in black_shark_matches:
    print(match)

Black Shark matches found: 1
{'parent_asin': 'B09L4QQCN2', 'title': 'Black Shark 4 Unlocked Phone, 5G Gaming Phone, Fast Charging 120W Cell Phone 12+256GB, 144Hz Snapdragon 870 Android Phone, 6.67" 48MP 4500mAh NFC Mobile Phone Global Version -Frost Grey', 'score': 0.5815507173538208}

In [43]:
# =====================================================
# RAW FAISS SEARCH FOR GAMING QUERY
# =====================================================

raw_gaming_results = (
    vector_db.similarity_search_with_score(
        "smartphone gaming",
        k=50
    )
)

for rank, (
    document,
    score
) in enumerate(
    raw_gaming_results,
    start=1
):

    asin = document.metadata.get(
        "parent_asin"
    )

    title = document.metadata.get(
        "title"
    )

    print(
        rank,
        "|",
        asin,
        "|",
        title,
        "| score:",
        round(
            float(score),
            4
        )
    )

1 | B09L4QQCN2 | Black Shark 4 Unlocked Phone, 5G Gaming Phone, Fast Charging 120W Cell Phone 12+256GB, 144Hz Snapdragon 870 Android Phone, 6.67" 48MP 4500mAh NFC Mobile Phone Global Version -Frost Grey | score: 1.0818
2 | B07F4BSXMQ | Gamer Heartbeat Smartphone Grip Best Video Game Player Gift PopSockets Grip and Stand for Phones and Tablets | score: 1.1072
3 | B018C96B7Q | Airsspu Virtual Reality Headset 3D VR Glasses Google Cardboard for iPhone Samsung Note LG HTC Moto 4~6 inch Smartphones for 3D Video/Movies/Games | score: 1.1456
4 | B07L2W1ZSR | Gameboy iPhone Case Handheld Game Console Phone Case with 36 Small Games Color Screen Retro 3D Gameboy Design for iPhone Xs Max, White | score: 1.1487
5 | B01768GWC8 | SainSonic ZH-01 Virtual Reality Headset 3D VR Glasses for 3.5~5.6 inch Smartphone | score: 1.1643
6 | B08N47M2DV | Autbye Gameboy Phone Cases, Retro 3D Gameboy Case for iPhone with 36 Small Games, Color Display Shockproof Video Game Phone Case, Phone Protective Case(for iPhone 6/7/8/6S,Black) | score: 1.1695
7 | B09X24P3D8 | Gamevice for iPhone - MFi iPhone Game Controller: Fits iPhone 14 – Play Xbox Cloud Gaming, PS Remote Play, GeForceNOW, Arcade, Luna, CoD, Diablo Immortal, Apex – Free 1 Month Xbox Game Pass Ultimate | score: 1.1718
8 | B00OSLAA52 | BLU Dash 5.5 Smartphone - Unlocked - Retail Packaging - (Pink) | score: 1.1863
9 | B093JXQX8M | WeLohas Gameboy Case for iPhone 6 Plus/ 6s Plus/ 7 Plus/ 8 Plus,Handheld Retro 168 Classic Games,Color Video Display Game Case for iPhone,Anti-Scratch Shockproof Phone Cover for iPhone Pink | score: 1.1919
10 | B00MBCIX36 | Unlocked JIAKE miniS5 MTK6572 2G ROM 5.0 Inch Android 4.2 3G Smartphone(Black) | score: 1.1968
11 | B00CGIULGC | Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked Android Ruggedized Smart Phone | score: 1.1987
12 | B002S0OCHM | HTC PURE Windows Phone (AT&T) | score: 1.2032
13 | B002VRO83K | Motorola DROID A855 Android Phone (Verizon Wireless) | score: 1.2066
14 | B00O3PAN1E | POSH Revel S500a - 5.0", 4G, Android 4.4 Kit Kat, Dual-core, 4GB, 8MP Camera, Dual Sim Smartphone (Black) | score: 1.2082
15 | B07RB4ZH83 | CUBOT Quest 5.5-inch Android 9.0 Pie Rugged Smartphone Unlocked, 4GB+64GB,4G Dual SIM, NFC,Gyroscope, 4000mAh Battery, 12MP Camera, IP68 Waterproof Shockproof, Dustproof (Black) | score: 1.2172
16 | B00F3SJJRO | Huawei U8833/Y300 Android 4.1 Dual Core 1.0GHz 4.0 inch WVGA | score: 1.2173
17 | B08XBQQS1G | Unlocked Smartphones, Mate40 Pro Dual SIM Unlocked Cell Phones Smart Phone, 5.45in HD Full Screen, 512MB RAM + 4GB ROM, 0.3MP + 2MP, Android 4.4.2, Face/Fingerprint Unlock, 1500mAh Battery(Black) | score: 1.2191
18 | B00NHPQDQ0 | Sudroid Z18 2.45 Inches Unlocked 3G Mini Phone with Android 4.4 Os (Black) | score: 1.222
19 | B01N1WRJWA | Ulefone Armor Triple Proofing Phone 32GB 4.7 Inch Android 6.0 Smartphone Black | score: 1.2245
20 | B003Y3BM0W | Motorola DROID II, Black 8GB (Verizon Wireless) | score: 1.2267
21 | B011LZMS98 | BLU Studio 5.5C D690u Unlocked GSM Dual-SIM Quad-Core Android Lollipop Smartphone - Blue | score: 1.2303
22 | B01D10LJMI | AGPtEK D1 Safety Android Mobile Phone Smart Phone for Kids Children|Parental Control Mode| GPS+LBS+WiFi | 4" Screen, Color Blue | score: 1.2306
23 | B0BLHCXZ8K | SANSHREUNI Dual Sim Unlocked Cell Phones,4G+128GB C21 Ultra Smartphone, 6.8 inch Waterdrop Screen Android Phone, 5000mAh Battery, 24+50 MP Unlocked Cell Phone, Fingerprint Lock & Face ID Mobile Phone | score: 1.2333
24 | B09PFX1X67 | Semiconductor Phone Cooler, Phone Cooling Case with Temperature Display&Adjustment, Mobile Phone Radiator with Dual Cooling Chips, 2.63-3.46 Inches Clip for Gaming, Livestreaming (Silver) | score: 1.2364
25 | B07BSJGRL8 | Acer Liquid Zest Plus 16GB DS 5.5" Display 2GB Ram 4G LTE 13MP- Factory Unlocked Phone - (US Warranty) (Blue) (Certified Refurbished) | score: 1.2371
26 | B01LZ8516T | ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inch, 16GB (Glacier Silver) | score: 1.2391
27 | B00XM28BQ8 | Amazing 6.0 GSM Unlocked Multi-Carrier no Contract Android Smart Phone-Gray | score: 1.2391
28 | B00NEEXCTK | Huawei Ascend G7 16GB GSM Unlocked Android Smartphone w/ 13MP Camera, 5.5" IPS LCD Display, Quad-Core CPU - White/Silver | score: 1.2409
29 | B09FKHS3CB | Global Version M11 Ultra 7.3inch Smartphone Unlocked 16G RAM-1T ROM with Android 11 Mobile Cell 6800mAh 48MP+64MP HD Full Screen Face ID Fingerprint Unlock 5G with Qualcomm Snapdragon 888 (Black) | score: 1.2457
30 | B08G11DG6J | KAVOYI Retro Handheld Game Console Phone Case for iPhone 11 Pro Max Case with Built in 36 Classic Games Compatible with iPhone 11 Pro Max Anti-Scratch Shock Absorption Cover (11 PM White) | score: 1.2503
31 | B005BHTZPI | Huawei M835 Prepaid Phone (MetroPCS) | score: 1.2534
32 | B0BBRBXPGC | Ulefone Armor 15 Unlocked Rugged Phone, Built-in Earbuds, Android 12, 6600mAh Battery, 8-Core Processor 6GB+128GB, 12MP+13MP Dual Main Camera, Dual SIM, 3-Card Slot T-Mobile Rugged Smartphone (Blue) | score: 1.2545
33 | B07K9PR1H5 | OUKITEL OK6000 Plus Unlocked Smartphones, 5.5inch, 4GB RAM 64GB ROM | score: 1.255
34 | B0B5Z9JGZN | Hengwin Leather Cell Phone Pouch for iPhone 14 Plus 13 Pro Max Samsung Galaxy A13 A73 5G A23 A04s Motorola Edge 30 Ultra LG Velvet 5G Holster Belt Clip Carrying Case Holder for Working Running (Brown) | score: 1.2551
35 | B00D93LOY6 | Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black | score: 1.2583
36 | B08MX3MDQ2 | VR Headset 3D Virtual Reality Glasses Full Screen Visual Wide-Angle Soft & Comfortable-Compatible with IOS and Android | score: 1.2624
37 | B0995SX8X8 | OUKITEL 8000mAh Large Battery 18W Flash Charge Outdoor Phone Android 10 4G 6+128GB Dual SIM Smartphone WP7 IP68 Rugged Cell Phone 6.56" FHD+ Display Unlocked Phone NFC OTG GPS Mobile Phone (Orange) | score: 1.2632
38 | B00NO80S3E | HTC Deluxe - 4G LTE GSM Factory Unlocked, 5" Android Smartphone with Beats Audio - Black | score: 1.2641
39 | B0B74J524C | KXD 6A | Unlocked Cell Phone | 5.5" Full Screen Display | 8GB ROM | 2500mAh Battery | 8MP Camera | Android Smartphone | US Version | Black | score: 1.2661
40 | B004HR7SXY | (Used Mint Condition) Blackberry Curve 8330 Trackball / Qwerty Keyboard Smart-phone with 2.0 Megapixel-Camera - Blue-tooth Capable - (Red) 1XEVDO CDMA 2000 for (Sprint Network) | score: 1.2716
41 | B07G37CLJ5 | VeeR VR Headset with Control, Virtual Reality Goggles Compatible with Android, Suit for 4.7-6.0 Inch Screen Cell Phone Virtual Reality Headsets for VR Videos & Games | score: 1.2721
42 | B009FV7GBG | RuggedQX RGQX601P XXL Super Heavy Duty Horizontal Holster Pouch Universal for Samsung Galaxy S3, Galaxy Note, HTC One X and Other Smartphones - Black | score: 1.2754
43 | B07B19C631 | LG Escape 2 H443 Unlocked GSM 4.7" HD Display Quad-Core Android 5.1 Smartphone w/ 8MP Camera - Black (Renewed) | score: 1.2766
44 | B07GKC6C22 | Unlocked Cell Phones International Version Android 8.1, v mobile A13 Dual Sim Unlocked Smartphones with 5.5 inch, 1 GB RAM + 8 GB ROM +16 GB Micro SD Card, 3000 mAh Battery, White | score: 1.2782
45 | B07KXMPRJ1 | Eboxer 9" Screen Magnifier for Cell Phone, Foldable 3D HD Mobile Phone Screen Amplifier Projector for Videos Movies and Gaming, Screen Enlarger with Stable Clip and Visor | score: 1.2783
46 | B06W5K6VW2 | Sports Cellphone Running Armband iPhone Galaxy Note Samsung Outdooor Workout ArmBag for All 3.5 to 6.0 inch Smartphone (Purple) | score: 1.2783
47 | B01FJT7ND8 | Sony Xperia X unlocked smartphone,32GB Lime Gold (US Warranty) | score: 1.2792
48 | B08S3LP8TY | Achort 12'' Screen Magnifier for Cell Phone 3D MobileMagnifier Screen HD with Foldable Phone Stand Amplifier wth Camera Shutter Remote Control Screen Enlarger for Video Movie Supports All Smartphones | score: 1.2801
49 | B074Q34TKB | BLU Studio J8 - 5.5" HD Unlocked Smartphone -8GB +1GB RAM -Rose Gold | score: 1.2853
50 | B00DB4LSOE | Charm 14 PursePlus Touch Cell Phone Purse - Retail Packaging - Black | score: 1.2865

In [44]:
# =====================================================
# DIAGNOSTIC QUERIES
# =====================================================

diagnostic_queries = [
    {
        "test_id": 6,
        "query": "Recommend a phone with a great camera.",
        "expected_terms": [
            "pixel",
            "s21 ultra",
            "camera"
        ]
    },
    {
        "test_id": 7,
        "query": "Recommend a phone with long battery life.",
        "expected_terms": [
            "8000mah",
            "6000mah",
            "max",
            "battery"
        ]
    },
    {
        "test_id": 8,
        "query": "Suggest a smartphone for gaming.",
        "expected_terms": [
            "black shark",
            "gaming",
            "rog",
            "redmagic"
        ]
    },
    {
        "test_id": 9,
        "query": (
            "Recommend a Samsung phone with a good camera, "
            "long battery life and fast performance."
        ),
        "expected_terms": [
            "s22",
            "s21",
            "s10"
        ]
    },
    {
        "test_id": 12,
        "query": "I need something good for photography.",
        "expected_terms": [
            "pixel",
            "s21 ultra",
            "camera phone"
        ]
    },
    {
        "test_id": 14,
        "query": (
            "Recommend a Samsung phone with a removable battery "
            "and an excellent camera."
        ),
        "expected_terms": [
            "galaxy s5",
            "removable battery"
        ]
    }
]

In [45]:
# =====================================================
# RAW FAISS VS RETRIEVAL AGENT
# =====================================================

def diagnose_retrieval_query(
    test_id: int,
    user_query: str,
    expected_terms: list[str],
    raw_k: int = 30,
    retrieval_k: int = 10
) -> dict:

    structured_query = query_agent.parse(
        user_query
    )

    print()
    print("=" * 100)
    print(
        f"TEST {test_id}: {user_query}"
    )
    print("=" * 100)

    print(
        "Structured query:",
        structured_query.model_dump()
        if hasattr(
            structured_query,
            "model_dump"
        )
        else structured_query
    )

    # Raw FAISS search
    raw_search_text = " ".join(
        [
            str(
                structured_query.product_type
                or ""
            ),
            str(
                structured_query.brand
                or ""
            ),
            " ".join(
                structured_query.features
                or []
            )
        ]
    ).strip()

    raw_results = (
        vector_db.similarity_search_with_score(
            raw_search_text,
            k=raw_k
        )
    )

    # Final Retrieval Agent output
    agent_results = (
        retrieval_agent.retrieve(
            query=structured_query,
            k=retrieval_k
        )
    )

    expected_terms_lower = [
        term.lower()
        for term in expected_terms
    ]

    def matches_expected(
        title: str
    ) -> bool:

        title_lower = str(
            title
        ).lower()

        return any(
            term in title_lower
            for term in expected_terms_lower
        )

    raw_expected = []

    for rank, (
        document,
        score
    ) in enumerate(
        raw_results,
        start=1
    ):

        title = document.metadata.get(
            "title",
            ""
        )

        if matches_expected(title):

            raw_expected.append(
                {
                    "rank": rank,
                    "asin": (
                        document.metadata.get(
                            "parent_asin"
                        )
                    ),
                    "title": title,
                    "score": float(score)
                }
            )

    agent_expected = []

    for rank, (
        document,
        score
    ) in enumerate(
        agent_results,
        start=1
    ):

        title = document.metadata.get(
            "title",
            ""
        )

        if matches_expected(title):

            agent_expected.append(
                {
                    "rank": rank,
                    "asin": (
                        document.metadata.get(
                            "parent_asin"
                        )
                    ),
                    "title": title,
                    "score": float(score)
                }
            )

    print()
    print("Expected matches in raw FAISS:")
    for product in raw_expected:
        print(product)

    print()
    print("Expected matches after Retrieval Agent:")
    for product in agent_expected:
        print(product)

    if raw_expected and not agent_expected:
        diagnosis = (
            "Potential retrieval filtering loss"
        )

    elif raw_expected and agent_expected:
        diagnosis = (
            "Expected product preserved"
        )

    elif not raw_expected:
        diagnosis = (
            "Expected product not found in raw candidate pool"
        )

    else:
        diagnosis = (
            "No clear diagnosis"
        )

    print()
    print("Diagnosis:", diagnosis)

    return {
        "test_id": test_id,
        "user_query": user_query,
        "structured_features": "|".join(
            structured_query.features
            or []
        ),
        "raw_expected_count": len(
            raw_expected
        ),
        "agent_expected_count": len(
            agent_expected
        ),
        "diagnosis": diagnosis
    }

In [46]:
diagnostic_results = []

for test_case in diagnostic_queries:

    result = diagnose_retrieval_query(
        test_id=test_case["test_id"],
        user_query=test_case["query"],
        expected_terms=(
            test_case["expected_terms"]
        ),
        raw_k=30,
        retrieval_k=10
    )

    diagnostic_results.append(
        result
    )

diagnostic_df = pd.DataFrame(
    diagnostic_results
)

display(
    diagnostic_df
)

====================================================================================================
TEST 6: Recommend a phone with a great camera.
====================================================================================================
Structured query: {'product_type': 'smartphone', 'brand': None, 'budget': None, 'features': ['great camera', 'camera']}

Expected matches in raw FAISS:
{'rank': 2, 'asin': 'B07979NV1M', 'title': 'ShutterGrip Secure Camera Handle Holder with Removable Bluetooth Remote Clicker, FaceTime, Zoom Stand, Tripod Compatible Bluetooth Camera Remote for iPhone, Android', 'score': 1.0410563945770264}
{'rank': 5, 'asin': 'B06XQ41H62', 'title': 'Premium HD Bluetooth Selfie Remote Control Camera Shutter for iPhone, Samsung Galaxy, Android, iPad, iPod, Tablets - Amazing Selfie Clicker for Photos, Videos, 30ft Range (Aqua)', 'score': 1.0664548873901367}
{'rank': 6, 'asin': 'B07QYTKZMT', 'title': 'UKCOCO Phone Camera Lens Compatible with iPhone, Samsung and Other Smartphones-Universal Portable Lens Kit Super Wide Angle Lens Macro Lens and Fisheye Lens Clip On 3 in 1 Mobile Phone Lens(Red)', 'score': 1.0671354532241821}
{'rank': 8, 'asin': 'B00USQ4UX4', 'title': 'Portable Mini 16 Leds LED Flash Fill Light Rechargeable for Smartphone iphone Samsung HTC and Camera Video Light (Black)', 'score': 1.0749762058258057}
{'rank': 10, 'asin': 'B08S3LP8TY', 'title': "Achort 12'' Screen Magnifier for Cell Phone 3D MobileMagnifier Screen HD with Foldable Phone Stand Amplifier wth Camera Shutter Remote Control Screen Enlarger for Video Movie Supports All Smartphones", 'score': 1.0923067331314087}
{'rank': 11, 'asin': 'B088T1N932', 'title': 'Selfie Ring Light with Cell Phone Holder Stand for Live Stream, LED Camera Lighting with Flexible Arms Compatible with iOS/Android', 'score': 1.0929021835327148}
{'rank': 14, 'asin': 'B00ZAJB9C4', 'title': 'New Version Genuine Gold Universal Clip-on 180 degree 3 in 1 Fisheye+Wide Angle+Macro Phone Camera Lens Kit for iPhone 5/5S/4/4S/6/6 Plus Samsung Galaxy S5/S4/S3 Note 4/3/2 G386 HTC Blackberry Bold Touch, Sony Xperia, Motorola Droid', 'score': 1.0975677967071533}
{'rank': 15, 'asin': 'B018LSGXDA', 'title': 'Fisheye Lens With Selfie Ring Light, Phone Camera Lens Kit With Ring Light [180 Fisheye+0.65x Wide Angle+10x Macro]For Cell Phone, iphone 7/6S/ Plus, Samsung S7/S6/edge, Black', 'score': 1.0983550548553467}
{'rank': 17, 'asin': 'B00ORZVW42', 'title': 'SteadyMate SM1 HD Professional Handheld Camera Stabilizer for Apple iPhone 6 Plus, 6, 5S, 5C, 5, 4S and 4 Smart Phones', 'score': 1.104482889175415}
{'rank': 18, 'asin': 'B07F6ZM9QJ', 'title': 'Phone Camera Lens, 0.4X Wide Angle Lens + 12X Macro Lens & 235° Fish Eye Lens + 15X Macro Lens, Clip on Cell Phone Camera Lens for Replacement iPhone 8 7 6s 6Plus, Smart Phones & Tablet', 'score': 1.1051826477050781}
{'rank': 20, 'asin': 'B0B5GW3R1X', 'title': 'Torjim 62" Phone Tripod, Portable Selfie Stick Tripod with Remote, Compatible with iPhone/Android/Camera, Stable Cell Phone Tripod Stand Perfect for Video Recording/Selfies/Live Streaming/Vlogging', 'score': 1.1150726079940796}
{'rank': 22, 'asin': 'B07Q7QXBMZ', 'title': 'Selfie Ring Light, Upgraded Ring Light with Cell Phone Holder Stand for Live Stream/Makeup, LED Camera Light 3 Light Modes 10-Level Brightness 360° Rotating for iPhone and Android', 'score': 1.1206576824188232}
{'rank': 23, 'asin': 'B08CMJX15B', 'title': "Coral's Coral Lens Smartphone Clip-on Camera Filter Kit with Wide Angle + Macro Lens & Waterproof Case iPhone Android Universal FITS UP to 3 Cameras (Black)", 'score': 1.1212313175201416}
{'rank': 24, 'asin': 'B00D93LOY6', 'title': 'Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black', 'score': 1.1226489543914795}
{'rank': 26, 'asin': 'B09SCMKYHZ', 'title': 'LIERONT Phone Camera Lens, 25X Telephoto Lens for iPhone Samsung Pixel, 4K HD 0.65X Wide Angle Lens & 25X Macro Lens(Screwed Together), 210° Fisheye Lens, Kaleidoscope Lens', 'score': 1.123894214630127}
{'rank': 30, 'asin': 'B06XKWDSZF', 'title': 'Xenvo SquidGrip Flexible Cell Phone Tripod and Portable Action Camera Holder - Compatible with iPhone, GoPro, Android, Samsung, Google Pixel and All Mobile Phones', 'score': 1.1353576183319092}

Expected matches after Retrieval Agent:
{'rank': 1, 'asin': 'B00NEEXCTK', 'title': 'Huawei Ascend G7 16GB GSM Unlocked Android Smartphone w/ 13MP Camera, 5.5" IPS LCD Display, Quad-Core CPU - White/Silver', 'score': 0.6240100559543099}
{'rank': 4, 'asin': 'B00O3PAN1E', 'title': 'POSH Revel S500a - 5.0", 4G, Android 4.4 Kit Kat, Dual-core, 4GB, 8MP Camera, Dual Sim Smartphone (Black)', 'score': 0.6006943539122128}
{'rank': 9, 'asin': 'B0B74J524C', 'title': 'KXD 6A | Unlocked Cell Phone | 5.5" Full Screen Display | 8GB ROM | 2500mAh Battery | 8MP Camera | Android Smartphone | US Version | Black', 'score': 0.5608257834851463}

Diagnosis: Expected product preserved

====================================================================================================
TEST 7: Recommend a phone with long battery life.
====================================================================================================
Structured query: {'product_type': 'smartphone', 'brand': None, 'budget': None, 'features': ['long battery life']}

Expected matches in raw FAISS:
{'rank': 1, 'asin': 'B0995SX8X8', 'title': 'OUKITEL 8000mAh Large Battery 18W Flash Charge Outdoor Phone Android 10 4G 6+128GB Dual SIM Smartphone WP7 IP68 Rugged Cell Phone 6.56" FHD+ Display Unlocked Phone NFC OTG GPS Mobile Phone (Orange)', 'score': 1.0134437084197998}
{'rank': 2, 'asin': 'B01LZ8516T', 'title': 'ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inch, 16GB (Glacier Silver)', 'score': 1.041747808456421}
{'rank': 3, 'asin': 'B07TC4QT96', 'title': 'xiyihoo Portable Charger, Solar Power Bank 26800mAh 15W Quick Charge Battery Pack, 3 Outputs Phone Charger with Bright Flashlight IP66 Waterproof for iPhone Android Cell Phones', 'score': 1.080340027809143}
{'rank': 4, 'asin': 'B07MW7ZQVN', 'title': 'SHENMZ LG V20 Battery,6800mAh (More Than 2X Extra Battery Power) Replacement LG V20 Extended Battery BL-44E1F with Black TPU Case for LG H910 H918 VS995 LS997 Phone | LG V20 Battery Case', 'score': 1.0848395824432373}
{'rank': 6, 'asin': 'B0054DZ32I', 'title': 'HTC 74H01885-00M Thunderbolt 6400 Extended Battery with Door - 2750 MaH - Non-Retail Packaging - Black', 'score': 1.092806339263916}
{'rank': 8, 'asin': 'B07GKC6C22', 'title': 'Unlocked Cell Phones International Version Android 8.1, v mobile A13 Dual Sim Unlocked Smartphones with 5.5 inch, 1 GB RAM + 8 GB ROM +16 GB Micro SD Card, 3000 mAh Battery, White', 'score': 1.097609281539917}
{'rank': 9, 'asin': 'B0B74J524C', 'title': 'KXD 6A | Unlocked Cell Phone | 5.5" Full Screen Display | 8GB ROM | 2500mAh Battery | 8MP Camera | Android Smartphone | US Version | Black', 'score': 1.1023101806640625}
{'rank': 10, 'asin': 'B07Z62Q7GM', 'title': 'Battery Case for iPhone X/XS 6500mAh, YASPS Portable Protective Charger Case Rechargeable Extended Battery Pack Charging Case for iPhone X/XS/10 (5.8 inch) Ultra Slim Backup Cover Power Bank - Black', 'score': 1.104525089263916}
{'rank': 11, 'asin': 'B07RB4ZH83', 'title': 'CUBOT Quest 5.5-inch Android 9.0 Pie Rugged Smartphone Unlocked, 4GB+64GB,4G Dual SIM, NFC,Gyroscope, 4000mAh Battery, 12MP Camera, IP68 Waterproof Shockproof, Dustproof (Black)', 'score': 1.107153296470642}
{'rank': 12, 'asin': 'B0BBRBXPGC', 'title': 'Ulefone Armor 15 Unlocked Rugged Phone, Built-in Earbuds, Android 12, 6600mAh Battery, 8-Core Processor 6GB+128GB, 12MP+13MP Dual Main Camera, Dual SIM, 3-Card Slot T-Mobile Rugged Smartphone (Blue)', 'score': 1.1132160425186157}
{'rank': 14, 'asin': 'B07NY3H6NK', 'title': 'Battery Case for iPhone 8/7/6/6s, Upgraded 6000mAh Charging Charger Cases Rechargeable Extended Battery Portable Pack for Apple iPhone 6/6s/7/8 - Black', 'score': 1.1145131587982178}
{'rank': 15, 'asin': 'B073G8PRMQ', 'title': 'mophie Power Boost XXL Power Pack- 20,800 mAh Internal Battery, Dual USB-A Charging Ports with 4.2A Power, LED Indicator, USB-A to Micro USB Charging Cord (Included), Triple-Tested for Safety', 'score': 1.11460280418396}
{'rank': 16, 'asin': 'B07YXTYRPL', 'title': 'Solar Power Bank 36000mAh, Qi Wireless Charger, 15W Fast Charging Type C + Dual USB Outputs, 5V/3A High Speed Power Bank with LED Flashlight + Hard Travel Case, IP66 Rated Waterproof, Dustproof', 'score': 1.1161361932754517}
{'rank': 17, 'asin': 'B07D8HV57R', 'title': 'HDCKU Battery Replaccement for Galaxy J3 J320,J5 G500,Grand Prime G530 2600mAh Li-ion Spare Battery Replacement with NFC', 'score': 1.1164638996124268}
{'rank': 18, 'asin': 'B07B944RHF', 'title': 'Friengood Solar Charger, Portable 25000mAh Solar Power Bank, Waterproof Solar External Battery Pack with Dual USB Ports and Flashlight for iPhone, iPad, Samsung, Android Phones and More (Black)', 'score': 1.1205682754516602}
{'rank': 19, 'asin': 'B08XBQQS1G', 'title': 'Unlocked Smartphones, Mate40 Pro Dual SIM Unlocked Cell Phones Smart Phone, 5.45in HD Full Screen, 512MB RAM + 4GB ROM, 0.3MP + 2MP, Android 4.4.2, Face/Fingerprint Unlock, 1500mAh Battery(Black)', 'score': 1.1210904121398926}
{'rank': 21, 'asin': 'B09WT8N5X7', 'title': 'Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 256GB, 8K Camera & Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom White (Renewed)', 'score': 1.1237268447875977}
{'rank': 24, 'asin': 'B071HQ6R28', 'title': 'Battery Case for iPhone 8/7/6S/6, ZeroLemon 4500mAh Portable Power Charger Rechargeable External Battery Protective Charging Case for Apple iPhone 6,6S,7,8 (4.7 Inch) (Black)', 'score': 1.1279816627502441}
{'rank': 25, 'asin': 'B09M7514S7', 'title': 'Flip Phone for Seniors, Big Button Senior Cell Phone 32+32MB Memory Dual Cards Dual Standby 2G Mobile Phone Keyboard Phone, SOS Button, 1200mAh Battery(Red)', 'score': 1.1280863285064697}
{'rank': 26, 'asin': 'B071NL874P', 'title': 'mophie Juice Pack Battery Case for Samsung Galaxy S8 (not plus) 2,950 mAh Built-in Battery - Wireless Charging - Black', 'score': 1.1302871704101562}
{'rank': 27, 'asin': 'B07DC1BL2R', 'title': 'ROMOSS 10000mAh 2-in-1 Power Bank and Wall Charger, Dual USB Portable Charger with Foldable AC Wall Plug External Battery Packs Compatible Smartphone and Android Device (Grey)', 'score': 1.1313581466674805}
{'rank': 30, 'asin': 'B09YY7B6GC', 'title': 'OHZHAO Portable Charger 5500mAh Compact Power Bank Cute Battery Pack with Built-in iOS and 18W PD Fast Charging Ports for iPhone, iPad, Airpods, Samsung, LG, Google, Moto, Android and More (Black)', 'score': 1.1331948041915894}

Expected matches after Retrieval Agent:
{'rank': 1, 'asin': 'B0995SX8X8', 'title': 'OUKITEL 8000mAh Large Battery 18W Flash Charge Outdoor Phone Android 10 4G 6+128GB Dual SIM Smartphone WP7 IP68 Rugged Cell Phone 6.56" FHD+ Display Unlocked Phone NFC OTG GPS Mobile Phone (Orange)', 'score': 0.5858542261236719}
{'rank': 4, 'asin': 'B01LZ8516T', 'title': 'ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inch, 16GB (Glacier Silver)', 'score': 0.47077148964919585}
{'rank': 6, 'asin': 'B0BBRBXPGC', 'title': 'Ulefone Armor 15 Unlocked Rugged Phone, Built-in Earbuds, Android 12, 6600mAh Battery, 8-Core Processor 6GB+128GB, 12MP+13MP Dual Main Camera, Dual SIM, 3-Card Slot T-Mobile Rugged Smartphone (Blue)', 'score': 0.4594293862977955}
{'rank': 8, 'asin': 'B07RB4ZH83', 'title': 'CUBOT Quest 5.5-inch Android 9.0 Pie Rugged Smartphone Unlocked, 4GB+64GB,4G Dual SIM, NFC,Gyroscope, 4000mAh Battery, 12MP Camera, IP68 Waterproof Shockproof, Dustproof (Black)', 'score': 0.44860307537939736}
{'rank': 10, 'asin': 'B0B74J524C', 'title': 'KXD 6A | Unlocked Cell Phone | 5.5" Full Screen Display | 8GB ROM | 2500mAh Battery | 8MP Camera | Android Smartphone | US Version | Black', 'score': 0.4234943038808492}

Diagnosis: Expected product preserved

====================================================================================================
TEST 8: Suggest a smartphone for gaming.
====================================================================================================
Structured query: {'product_type': 'smartphone', 'brand': None, 'budget': None, 'features': ['gaming']}

Expected matches in raw FAISS:
{'rank': 1, 'asin': 'B09L4QQCN2', 'title': 'Black Shark 4 Unlocked Phone, 5G Gaming Phone, Fast Charging 120W Cell Phone 12+256GB, 144Hz Snapdragon 870 Android Phone, 6.67" 48MP 4500mAh NFC Mobile Phone Global Version -Frost Grey', 'score': 1.0612537860870361}
{'rank': 4, 'asin': 'B09X24P3D8', 'title': 'Gamevice for iPhone - MFi iPhone Game Controller: Fits iPhone 14 – Play Xbox Cloud Gaming, PS Remote Play, GeForceNOW, Arcade, Luna, CoD, Diablo Immortal, Apex – Free 1 Month Xbox Game Pass Ultimate', 'score': 1.1330676078796387}
{'rank': 22, 'asin': 'B09PFX1X67', 'title': 'Semiconductor Phone Cooler, Phone Cooling Case with Temperature Display&Adjustment, Mobile Phone Radiator with Dual Cooling Chips, 2.63-3.46 Inches Clip for Gaming, Livestreaming (Silver)', 'score': 1.2127869129180908}

Expected matches after Retrieval Agent:
{'rank': 1, 'asin': 'B09L4QQCN2', 'title': 'Black Shark 4 Unlocked Phone, 5G Gaming Phone, Fast Charging 120W Cell Phone 12+256GB, 144Hz Snapdragon 870 Android Phone, 6.67" 48MP 4500mAh NFC Mobile Phone Global Version -Frost Grey', 'score': 0.6329109177916736}

Diagnosis: Expected product preserved

====================================================================================================
TEST 9: Recommend a Samsung phone with a good camera, long battery life and fast performance.
====================================================================================================
Structured query: {'product_type': 'smartphone', 'brand': 'Samsung', 'budget': None, 'features': ['good camera', 'long battery life', 'fast performance', 'camera']}

Expected matches in raw FAISS:
{'rank': 1, 'asin': 'B09WT8N5X7', 'title': 'Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 256GB, 8K Camera & Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom White (Renewed)', 'score': 0.8948131799697876}
{'rank': 2, 'asin': 'B09S6VKCLX', 'title': 'SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Black - Unlocked (Renewed Premium)', 'score': 0.9379172325134277}
{'rank': 5, 'asin': 'B09X9FC88M', 'title': 'Samsung Galaxy S22 Ultra 256GB Unlocked ATT TMobile Verizon 100% batt! 7548400', 'score': 0.968103289604187}
{'rank': 7, 'asin': 'B0BF1FZTLQ', 'title': 'SAMSUNG Galaxy S21 FE 5G SM-G990U 256GB Factory Unlocked Smartphone (Renewed) (Olive)', 'score': 0.9913127422332764}
{'rank': 10, 'asin': 'B0BM3F9RK1', 'title': 'Samsung Galaxy S10 G973U Unlocked 128GB - Flamingo Pink (Renewed)', 'score': 1.0115678310394287}
{'rank': 11, 'asin': 'B0B1QXHB7L', 'title': 'Samsung Galaxy S21 FE 5G Cell Phone, Factory Unlocked Android Smartphone, 128GB, 120Hz Display, Pro Grade Camera, All Day Intelligent Battery, (Olive Green) (Renewed)', 'score': 1.0126879215240479}
{'rank': 21, 'asin': 'B08225GDLL', 'title': 'SAMSUNG Galaxy S10 Factory Unlocked Phone with 128GB (U.S. Warranty), Prism Blue - SM-G973UZBAXAA w/AKG N700NC Headphones', 'score': 1.0767409801483154}

Expected matches after Retrieval Agent:
{'rank': 1, 'asin': 'B0B1QXHB7L', 'title': 'Samsung Galaxy S21 FE 5G Cell Phone, Factory Unlocked Android Smartphone, 128GB, 120Hz Display, Pro Grade Camera, All Day Intelligent Battery, (Olive Green) (Renewed)', 'score': 0.5686169896579204}
{'rank': 2, 'asin': 'B09WT8N5X7', 'title': 'Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 256GB, 8K Camera & Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom White (Renewed)', 'score': 0.5608469417226954}
{'rank': 3, 'asin': 'B09S6VKCLX', 'title': 'SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Black - Unlocked (Renewed Premium)', 'score': 0.5596905378982594}
{'rank': 5, 'asin': 'B0BF1FZTLQ', 'title': 'SAMSUNG Galaxy S21 FE 5G SM-G990U 256GB Factory Unlocked Smartphone (Renewed) (Olive)', 'score': 0.5206320360338029}
{'rank': 9, 'asin': 'B09X9FC88M', 'title': 'Samsung Galaxy S22 Ultra 256GB Unlocked ATT TMobile Verizon 100% batt! 7548400', 'score': 0.5038612380162559}

Diagnosis: Expected product preserved

====================================================================================================
TEST 12: I need something good for photography.
====================================================================================================
Structured query: {'product_type': 'smartphone', 'brand': None, 'budget': None, 'features': ['photography']}

Expected matches in raw FAISS:
{'rank': 26, 'asin': 'B09SCMKYHZ', 'title': 'LIERONT Phone Camera Lens, 25X Telephoto Lens for iPhone Samsung Pixel, 4K HD 0.65X Wide Angle Lens & 25X Macro Lens(Screwed Together), 210° Fisheye Lens, Kaleidoscope Lens', 'score': 1.087665319442749}

Expected matches after Retrieval Agent:

Diagnosis: Potential retrieval filtering loss

====================================================================================================
TEST 14: Recommend a Samsung phone with a removable battery and an excellent camera.
====================================================================================================
Structured query: {'product_type': 'smartphone', 'brand': 'Samsung', 'budget': None, 'features': ['removable battery', 'excellent camera', 'camera']}

Expected matches in raw FAISS:
{'rank': 8, 'asin': 'B00JKSUHLU', 'title': 'Samsung Galaxy S5 SM-G900H Factory Unlocked Cellphone, International Version, Black', 'score': 1.0099644660949707}
{'rank': 29, 'asin': 'B00MH88LCW', 'title': 'New Original Samsung Galaxy S5 G900A Battery Door Back Cover with Waterproof Seal and W/NFC ~ (AT&T-GOLD)', 'score': 1.060624361038208}

Expected matches after Retrieval Agent:
{'rank': 1, 'asin': 'B00JKSUHLU', 'title': 'Samsung Galaxy S5 SM-G900H Factory Unlocked Cellphone, International Version, Black', 'score': 0.5557798133964714}

Diagnosis: Expected product preserved

,test_id,user_query,structured_features,raw_expected_count,agent_expected_count,diagnosis
0,6,Recommend a phone with a great camera.,great camera|camera,16,3,Expected product preserved
1,7,Recommend a phone with long battery life.,long battery life,22,5,Expected product preserved
2,8,Suggest a smartphone for gaming.,gaming,3,1,Expected product preserved
3,9,"Recommend a Samsung phone with a good camera, ...",good camera|long battery life|fast performance...,7,5,Expected product preserved
4,12,I need something good for photography.,photography,1,0,Potential retrieval filtering loss
5,14,Recommend a Samsung phone with a removable bat...,removable battery|excellent camera|camera,2,1,Expected product preserved

In [47]:
# =====================================================
# DIAGNOSE TEST 14
# =====================================================

test_query = (
    "Recommend a Samsung phone with a removable "
    "battery and an excellent camera."
)

test_query_structured = query_agent.parse(
    test_query
)

print(
    "Structured query:",
    test_query_structured.model_dump()
)

search_query = build_search_query(
    test_query_structured
)

print(
    "\nSearch query:",
    search_query
)

# Get a large raw FAISS candidate pool
raw_results = (
    vector_db.similarity_search_with_score(
        search_query,
        k=50
    )
)

target_asin = "B00JKSUHLU"


# =====================================================
# 1. FIND TARGET IN RAW FAISS
# =====================================================

print("\nRAW FAISS")

for rank, (doc, score) in enumerate(
    raw_results,
    start=1
):

    asin = str(
        doc.metadata.get(
            "parent_asin",
            ""
        )
    )

    if asin == target_asin:

        print(
            "Found target at raw rank:",
            rank
        )

        print(
            "Title:",
            doc.metadata.get(
                "title"
            )
        )

        print(
            "Rating:",
            doc.metadata.get(
                "average_rating"
            )
        )

        print(
            "Price:",
            doc.metadata.get(
                "price"
            )
        )

        print(
            "FAISS distance:",
            score
        )


# =====================================================
# 2. APPLY PRODUCT FILTER
# =====================================================

filtered_results = filter_products(
    raw_results,
    test_query_structured,
    min_rating=0.0
)

filtered_asins = [
    str(
        doc.metadata.get(
            "parent_asin",
            ""
        )
    )
    for doc, _ in filtered_results
]

print()
print(
    "Target survived filter:",
    target_asin in filtered_asins
)

print(
    "Products after filtering:",
    len(filtered_results)
)


# =====================================================
# 3. RUN FINAL RETRIEVAL AGENT
# =====================================================

final_results = retrieval_agent.retrieve(
    query=test_query_structured,
    k=10
)

print()
print("FINAL RETRIEVAL")

for rank, (
    doc,
    score
) in enumerate(
    final_results,
    start=1
):

    print(
        rank,
        "|",
        doc.metadata.get(
            "parent_asin"
        ),
        "|",
        doc.metadata.get(
            "title"
        ),
        "|",
        round(
            float(score),
            4
        )
    )


final_asins = [
    str(
        doc.metadata.get(
            "parent_asin",
            ""
        )
    )
    for doc, _ in final_results
]

print()
print(
    "Target in final Top-10:",
    target_asin in final_asins
)

Structured query: {'product_type': 'smartphone', 'brand': 'Samsung', 'budget': None, 'features': ['removable battery', 'excellent camera', 'camera']}

Search query: phone smartphone mobile cell phone cellphone android phone samsung removable battery camera

RAW FAISS
Found target at raw rank: 25
Title: Samsung Galaxy S5 SM-G900H Factory Unlocked Cellphone, International Version, Black
Rating: 4.3
Price: 579.99
FAISS distance: 1.0417097

Target survived filter: True
Products after filtering: 7

FINAL RETRIEVAL
1 | B00JKSUHLU | Samsung Galaxy S5 SM-G900H Factory Unlocked Cellphone, International Version, Black | 0.5558
2 | B00CGIULGC | Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked Android Ruggedized Smart Phone | 0.5506
3 | B00D93LOY6 | Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black | 0.5443
4 | B09X9FC88M | Samsung Galaxy S22 Ultra 256GB Unlocked ATT TMobile Verizon 100% batt! 7548400 | 0.5234
5 | B09WT8N5X7 | Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 256GB, 8K Camera & Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom White (Renewed) | 0.5224
6 | B07QH32PCY | SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G LTE Phone w/ 12MP Camera - Midnight Black | 0.5221
7 | B004RZ2HWS | Samsung A797 Flight Unlocked Phone with QWERTY Keyboard, 2MP Camera and GPS - Grey | 0.4835

Target in final Top-10: True

In [48]:
# =====================================================
# RETRIEVAL REGRESSION TEST
# =====================================================

test_queries = [
    "Suggest a smartphone for gaming.",

    "Recommend a phone with a great camera.",

    "Recommend a phone with long battery life.",

    (
        "Recommend a Samsung phone with a good camera, "
        "long battery life and fast performance."
    ),

    (
        "Recommend a Samsung phone with a removable battery "
        "and an excellent camera."
    )
]


for text in test_queries:

    query = query_agent.parse(
        text
    )

    print("\n" + "=" * 100)
    print("QUERY:", text)

    print(
        "STRUCTURED:",
        query.model_dump()
    )

    results = retrieval_agent.retrieve(
        query=query,
        k=10
    )

    print("\nRETRIEVED PRODUCTS:")

    for rank, (
        doc,
        score
    ) in enumerate(
        results,
        start=1
    ):

        print(
            rank,
            "|",
            doc.metadata.get(
                "parent_asin"
            ),
            "|",
            doc.metadata.get(
                "title"
            ),
            "|",
            round(
                float(score),
                4
            )
        )

====================================================================================================
QUERY: Suggest a smartphone for gaming.
STRUCTURED: {'product_type': 'smartphone', 'brand': None, 'budget': None, 'features': ['gaming']}

RETRIEVED PRODUCTS:
1 | B09L4QQCN2 | Black Shark 4 Unlocked Phone, 5G Gaming Phone, Fast Charging 120W Cell Phone 12+256GB, 144Hz Snapdragon 870 Android Phone, 6.67" 48MP 4500mAh NFC Mobile Phone Global Version -Frost Grey | 0.6329
2 | B0BLHCXZ8K | SANSHREUNI Dual Sim Unlocked Cell Phones,4G+128GB C21 Ultra Smartphone, 6.8 inch Waterdrop Screen Android Phone, 5000mAh Battery, 24+50 MP Unlocked Cell Phone, Fingerprint Lock & Face ID Mobile Phone | 0.5417
3 | B00NEEXCTK | Huawei Ascend G7 16GB GSM Unlocked Android Smartphone w/ 13MP Camera, 5.5" IPS LCD Display, Quad-Core CPU - White/Silver | 0.4675
4 | B00NO80S3E | HTC Deluxe - 4G LTE GSM Factory Unlocked, 5" Android Smartphone with Beats Audio - Black | 0.4561
5 | B002VRO83K | Motorola DROID A855 Android Phone (Verizon Wireless) | 0.4517
6 | B00CGIULGC | Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked Android Ruggedized Smart Phone | 0.4511
7 | B0BBRBXPGC | Ulefone Armor 15 Unlocked Rugged Phone, Built-in Earbuds, Android 12, 6600mAh Battery, 8-Core Processor 6GB+128GB, 12MP+13MP Dual Main Camera, Dual SIM, 3-Card Slot T-Mobile Rugged Smartphone (Blue) | 0.4502
8 | B00O3PAN1E | POSH Revel S500a - 5.0", 4G, Android 4.4 Kit Kat, Dual-core, 4GB, 8MP Camera, Dual Sim Smartphone (Black) | 0.4467
9 | B07RB4ZH83 | CUBOT Quest 5.5-inch Android 9.0 Pie Rugged Smartphone Unlocked, 4GB+64GB,4G Dual SIM, NFC,Gyroscope, 4000mAh Battery, 12MP Camera, IP68 Waterproof Shockproof, Dustproof (Black) | 0.4443
10 | B00OSLAA52 | BLU Dash 5.5 Smartphone - Unlocked - Retail Packaging - (Pink) | 0.4334

====================================================================================================
QUERY: Recommend a phone with a great camera.
STRUCTURED: {'product_type': 'smartphone', 'brand': None, 'budget': None, 'features': ['great camera', 'camera']}

RETRIEVED PRODUCTS:
1 | B00NEEXCTK | Huawei Ascend G7 16GB GSM Unlocked Android Smartphone w/ 13MP Camera, 5.5" IPS LCD Display, Quad-Core CPU - White/Silver | 0.624
2 | B00CGIULGC | Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked Android Ruggedized Smart Phone | 0.603
3 | B002VRO83K | Motorola DROID A855 Android Phone (Verizon Wireless) | 0.6012
4 | B00O3PAN1E | POSH Revel S500a - 5.0", 4G, Android 4.4 Kit Kat, Dual-core, 4GB, 8MP Camera, Dual Sim Smartphone (Black) | 0.6007
5 | B011LZMS98 | BLU Studio 5.5C D690u Unlocked GSM Dual-SIM Quad-Core Android Lollipop Smartphone - Blue | 0.5817
6 | B00MBCIX36 | Unlocked JIAKE miniS5 MTK6572 2G ROM 5.0 Inch Android 4.2 3G Smartphone(Black) | 0.5796
7 | B01N1WRJWA | Ulefone Armor Triple Proofing Phone 32GB 4.7 Inch Android 6.0 Smartphone Black | 0.5676
8 | B00NHPQDQ0 | Sudroid Z18 2.45 Inches Unlocked 3G Mini Phone with Android 4.4 Os (Black) | 0.562
9 | B0B74J524C | KXD 6A | Unlocked Cell Phone | 5.5" Full Screen Display | 8GB ROM | 2500mAh Battery | 8MP Camera | Android Smartphone | US Version | Black | 0.5608
10 | B01D10LJMI | AGPtEK D1 Safety Android Mobile Phone Smart Phone for Kids Children|Parental Control Mode| GPS+LBS+WiFi | 4" Screen, Color Blue | 0.5533

====================================================================================================
QUERY: Recommend a phone with long battery life.
STRUCTURED: {'product_type': 'smartphone', 'brand': None, 'budget': None, 'features': ['long battery life']}

RETRIEVED PRODUCTS:
1 | B0995SX8X8 | OUKITEL 8000mAh Large Battery 18W Flash Charge Outdoor Phone Android 10 4G 6+128GB Dual SIM Smartphone WP7 IP68 Rugged Cell Phone 6.56" FHD+ Display Unlocked Phone NFC OTG GPS Mobile Phone (Orange) | 0.5859
2 | B07K9PR1H5 | OUKITEL OK6000 Plus Unlocked Smartphones, 5.5inch, 4GB RAM 64GB ROM | 0.5823
3 | B09L4QQCN2 | Black Shark 4 Unlocked Phone, 5G Gaming Phone, Fast Charging 120W Cell Phone 12+256GB, 144Hz Snapdragon 870 Android Phone, 6.67" 48MP 4500mAh NFC Mobile Phone Global Version -Frost Grey | 0.4743
4 | B01LZ8516T | ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inch, 16GB (Glacier Silver) | 0.4708
5 | B00NO80S3E | HTC Deluxe - 4G LTE GSM Factory Unlocked, 5" Android Smartphone with Beats Audio - Black | 0.4655
6 | B0BBRBXPGC | Ulefone Armor 15 Unlocked Rugged Phone, Built-in Earbuds, Android 12, 6600mAh Battery, 8-Core Processor 6GB+128GB, 12MP+13MP Dual Main Camera, Dual SIM, 3-Card Slot T-Mobile Rugged Smartphone (Blue) | 0.4594
7 | B002VRO83K | Motorola DROID A855 Android Phone (Verizon Wireless) | 0.4554
8 | B07RB4ZH83 | CUBOT Quest 5.5-inch Android 9.0 Pie Rugged Smartphone Unlocked, 4GB+64GB,4G Dual SIM, NFC,Gyroscope, 4000mAh Battery, 12MP Camera, IP68 Waterproof Shockproof, Dustproof (Black) | 0.4486
9 | B01N1WRJWA | Ulefone Armor Triple Proofing Phone 32GB 4.7 Inch Android 6.0 Smartphone Black | 0.4329
10 | B0B74J524C | KXD 6A | Unlocked Cell Phone | 5.5" Full Screen Display | 8GB ROM | 2500mAh Battery | 8MP Camera | Android Smartphone | US Version | Black | 0.4235

====================================================================================================
QUERY: Recommend a Samsung phone with a good camera, long battery life and fast performance.
STRUCTURED: {'product_type': 'smartphone', 'brand': 'Samsung', 'budget': None, 'features': ['good camera', 'long battery life', 'fast performance', 'camera']}

RETRIEVED PRODUCTS:
1 | B0B1QXHB7L | Samsung Galaxy S21 FE 5G Cell Phone, Factory Unlocked Android Smartphone, 128GB, 120Hz Display, Pro Grade Camera, All Day Intelligent Battery, (Olive Green) (Renewed) | 0.5686
2 | B09WT8N5X7 | Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 256GB, 8K Camera & Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom White (Renewed) | 0.5608
3 | B09S6VKCLX | SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Black - Unlocked (Renewed Premium) | 0.5597
4 | B00JKSUHLU | Samsung Galaxy S5 SM-G900H Factory Unlocked Cellphone, International Version, Black | 0.5315
5 | B0BF1FZTLQ | SAMSUNG Galaxy S21 FE 5G SM-G990U 256GB Factory Unlocked Smartphone (Renewed) (Olive) | 0.5206
6 | B00CGIULGC | Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked Android Ruggedized Smart Phone | 0.5195
7 | B09C6N8P6Y | Samsung Galaxy A52 (5G) 128GB A526U 6.5" Display Quad Camera Smartphone - Black (Renewed) (AT&T Unlocked) | 0.5191
8 | B00D93LOY6 | Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black | 0.5149
9 | B09X9FC88M | Samsung Galaxy S22 Ultra 256GB Unlocked ATT TMobile Verizon 100% batt! 7548400 | 0.5039
10 | B07QH32PCY | SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G LTE Phone w/ 12MP Camera - Midnight Black | 0.4965

====================================================================================================
QUERY: Recommend a Samsung phone with a removable battery and an excellent camera.
STRUCTURED: {'product_type': 'smartphone', 'brand': 'Samsung', 'budget': None, 'features': ['removable battery', 'excellent camera', 'camera']}

RETRIEVED PRODUCTS:
1 | B00JKSUHLU | Samsung Galaxy S5 SM-G900H Factory Unlocked Cellphone, International Version, Black | 0.5558
2 | B00CGIULGC | Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked Android Ruggedized Smart Phone | 0.5506
3 | B00D93LOY6 | Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black | 0.5443
4 | B09X9FC88M | Samsung Galaxy S22 Ultra 256GB Unlocked ATT TMobile Verizon 100% batt! 7548400 | 0.5234
5 | B09WT8N5X7 | Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 256GB, 8K Camera & Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom White (Renewed) | 0.5224
6 | B07QH32PCY | SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G LTE Phone w/ 12MP Camera - Midnight Black | 0.5221
7 | B004RZ2HWS | Samsung A797 Flight Unlocked Phone with QWERTY Keyboard, 2MP Camera and GPS - Grey | 0.4835

In [49]:
# =====================================================
# TEST UPDATED VERIFIER
# =====================================================

verifier_test_queries = [
    "Suggest a smartphone for gaming.",

    (
        "Recommend a Samsung phone with a good camera, "
        "long battery life and fast performance."
    ),

    (
        "Recommend a Samsung phone with a removable battery "
        "and an excellent camera."
    ),

    (
        "Recommend a Nokia phone with an 8K camera "
        "and 1TB storage."
    )
]


for text in verifier_test_queries:

    print("\n" + "=" * 100)
    print("QUERY:", text)
    print("=" * 100)

    result = run_coordinated_system(
        user_query=text,
        retrieval_k=10,
        max_reviews=3,
        verbose=False
    )

    verification_output = result.get(
        "verification_output"
    )

    if verification_output is None:

        print("NO VERIFICATION OUTPUT")
        continue

    print(
        "Overall status:",
        verification_output.overall_status
    )

    print(
        "Recommended product:",
        verification_output.recommended_product_title
    )

    print(
        "Recommended ASIN:",
        verification_output.recommended_product_asin
    )

    print(
        "Confidence:",
        verification_output.confidence
    )

    print("\nVERIFIED PRODUCTS:")

    for product in (
        verification_output.verified_products
    ):

        print(
            product.rank,
            "|",
            product.parent_asin,
            "|",
            product.status,
            "| feature:",
            product.feature_status,
            "| ratio:",
            product.feature_match_ratio,
            "| missing:",
            product.missing_features
        )

====================================================================================================
QUERY: Suggest a smartphone for gaming.
====================================================================================================
Overall status: passed_with_warnings
Recommended product: Black Shark 4 Unlocked Phone, 5G Gaming Phone, Fast Charging 120W Cell Phone 12+256GB, 144Hz Snapdragon 870 Android Phone, 6.67" 48MP 4500mAh NFC Mobile Phone Global Version -Frost Grey
Recommended ASIN: B09L4QQCN2
Confidence: medium

VERIFIED PRODUCTS:
1 | B09L4QQCN2 | passed_with_warning | feature: full_match | ratio: 1.0 | missing: []
2 | B0BLHCXZ8K | passed_with_warning | feature: full_match | ratio: 1.0 | missing: []
3 | B00O3PAN1E | failed | feature: no_match | ratio: 0.0 | missing: ['gaming']
4 | B00NEEXCTK | failed | feature: no_match | ratio: 0.0 | missing: ['gaming']
5 | B00NO80S3E | failed | feature: no_match | ratio: 0.0 | missing: ['gaming']
6 | B00CGIULGC | failed | feature: no_match | ratio: 0.0 | missing: ['gaming']
7 | B002VRO83K | failed | feature: no_match | ratio: 0.0 | missing: ['gaming']
8 | B07RB4ZH83 | failed | feature: no_match | ratio: 0.0 | missing: ['gaming']
9 | B0BBRBXPGC | failed | feature: no_match | ratio: 0.0 | missing: ['gaming']
10 | B00OSLAA52 | failed | feature: no_match | ratio: 0.0 | missing: ['gaming']

====================================================================================================
QUERY: Recommend a Samsung phone with a good camera, long battery life and fast performance.
====================================================================================================
Overall status: passed_with_warnings
Recommended product: Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black
Recommended ASIN: B00D93LOY6
Confidence: medium

VERIFIED PRODUCTS:
1 | B00D93LOY6 | passed_with_warning | feature: partial_match | ratio: 0.667 | missing: ['long battery life']
2 | B00JKSUHLU | passed_with_warning | feature: partial_match | ratio: 0.667 | missing: ['long battery life']
3 | B0B1QXHB7L | passed_with_warning | feature: partial_match | ratio: 0.667 | missing: ['fast performance']
4 | B09S6VKCLX | passed_with_warning | feature: partial_match | ratio: 0.667 | missing: ['fast performance']
5 | B09WT8N5X7 | passed_with_warning | feature: partial_match | ratio: 0.667 | missing: ['fast performance']
6 | B0BF1FZTLQ | passed_with_warning | feature: partial_match | ratio: 0.667 | missing: ['fast performance']
7 | B09C6N8P6Y | passed_with_warning | feature: partial_match | ratio: 0.333 | missing: ['long battery life', 'fast performance']
8 | B00CGIULGC | passed_with_warning | feature: partial_match | ratio: 0.333 | missing: ['long battery life', 'fast performance']
9 | B09X9FC88M | passed_with_warning | feature: partial_match | ratio: 0.667 | missing: ['fast performance']
10 | B07QH32PCY | passed_with_warning | feature: partial_match | ratio: 0.333 | missing: ['long battery life', 'fast performance']

====================================================================================================
QUERY: Recommend a Samsung phone with a removable battery and an excellent camera.
====================================================================================================
Overall status: passed_with_warnings
Recommended product: Samsung Galaxy Mega 6.3 I9200 8GB Unlocked GSM Dual-Core Android Smartphone w/ 8 MP Camera - Black
Recommended ASIN: B00D93LOY6
Confidence: medium

VERIFIED PRODUCTS:
1 | B00D93LOY6 | passed_with_warning | feature: partial_match | ratio: 0.5 | missing: ['removable battery']
2 | B00JKSUHLU | passed_with_warning | feature: partial_match | ratio: 0.5 | missing: ['removable battery']
3 | B00CGIULGC | passed_with_warning | feature: partial_match | ratio: 0.5 | missing: ['removable battery']
4 | B09WT8N5X7 | passed_with_warning | feature: partial_match | ratio: 0.5 | missing: ['removable battery']
5 | B09X9FC88M | passed_with_warning | feature: partial_match | ratio: 0.5 | missing: ['removable battery']
6 | B07QH32PCY | passed_with_warning | feature: partial_match | ratio: 0.5 | missing: ['removable battery']
7 | B004RZ2HWS | passed_with_warning | feature: partial_match | ratio: 0.5 | missing: ['removable battery']

====================================================================================================
QUERY: Recommend a Nokia phone with an 8K camera and 1TB storage.
====================================================================================================
Overall status: failed
Recommended product: None
Recommended ASIN: None
Confidence: low

VERIFIED PRODUCTS:
1 | B003X26SLM | failed | feature: no_match | ratio: 0.0 | missing: ['8k camera', '1tb storage']
2 | B00UYAE1K6 | failed | feature: no_match | ratio: 0.0 | missing: ['8k camera', '1tb storage']

In [50]:
result = run_coordinated_system(
    user_query=(
        "Recommend a Nokia phone with an 8K camera "
        "and 1TB storage."
    ),
    retrieval_k=10,
    max_reviews=3,
    verbose=False
)

print(result)

verification_output = result.get(
    "verification_output"
)

print("\nVerification output:")
print(verification_output)

if verification_output is not None:

    print(
        "\nOverall status:",
        verification_output.overall_status
    )

    print(
        "Recommended product:",
        verification_output.recommended_product_title
    )

    print(
        "Recommended ASIN:",
        verification_output.recommended_product_asin
    )

    for product in (
        verification_output.verified_products
    ):
        print(
            product.rank,
            "|",
            product.parent_asin,
            "|",
            product.status,
            "|",
            product.feature_status,
            "|",
            product.missing_features
        )

{'system': 'coordinated_multi_agent', 'user_query': 'Recommend a Nokia phone with an 8K camera and 1TB storage.', 'structured_query': ProductQuery(product_type='smartphone', brand='Nokia', budget=None, features=['8k camera', '1tb storage']), 'retrieved_products': [(Document(id='018822ba-1feb-4eb3-9f27-02897d9ddc67', metadata={'parent_asin': 'B003X26SLM', 'title': 'Nokia E5-00 Unlocked GSM Phone with Easy Email Setup, IM, QWERTY, 5 MP Camera, Ovi Store with Apps, and Free Ovi Maps Navigation (White)', 'price': nan, 'average_rating': 4.4, 'rating_number': 139, 'categories': 'Cell Phones & Accessories > Wireless Trade-In Buy Box Widget > Unlocked Wireless Trade-In', 'similarity': 0.4940051158919844, 'retrieval_score': 0.5463256302487554, 'feature_match': 0.5, 'brand': 'nokia', 'product_type': 'phone', 'requested_features': ['camera', '1tb storage'], 'budget': None}, page_content='Title: Nokia E5-00 Unlocked GSM Phone with Easy Email Setup, IM, QWERTY, 5 MP Camera, Ovi Store with Apps, and Free Ovi Maps Navigation (White)\n\nDescription: Product Description Discover more ways to stay connected with friends, family, business contacts and everyone important to you with the Nokia E5-00. It has everything you need to stay in touch with a variety of email and messaging options, while also helping you to take and share pics and videos, explore the web, connect through social networking, access work and personal email, navigate your day and more. The affordable Nokia E5 even manages to fit a full QWERTY keyboard into its compact, eye-catching design for quick and easy messaging on the go. Plus, there are plenty of features to make it the perfect business-focused device. Stay productive and stay in the loop with work no matter where you are with simple setup and access for your corporate email account. The Nokia E5 makes communicating with work a breeze with Mail for Exchange, the free, direct and secure corporate email solution that offers a robust desktop-like email experience right on your phone, with email, calendar, contacts and more. Plus, your work email shows up on your phone instantly, so you don’t have to wait for important emails. The Nokia E5 also features a fully integrated Microsoft Communicator Mobile client, to provide your mobile device the same great IM, contacts and usability that you enjoy on your computer. Keep in touch however you like with a variety of ways to connect to others with the Nokia E5. The home screen offers an easy visual way to view your contacts and makes it easy to organize the people you talk to most. The Nokia E5 also features one-click access to messaging as well as easy email setup and support for plenty of popular personal email services. The leading IM services have also been seamlessly integrated onto the phone. The Nokia E5 also offers free voice-guided navigation from Ovi Maps so you always know where you’re going. Plus customize your phone with thousands of available apps from Ovi Store. Connect with everyone and everything you want with the Nokia E5. Amazon.com Great for mobile messaging as well as providing excellent voice communications, the Symbian-based Nokia E5-00 unlocked mobile phone follows the successful blueprint of devices such as the Nokia E72 and Nokia E63. It combines high-quality business features--such as synchronization of contacts and e-mail with Microsoft Exchange and IBM Lotus Notes Traveler environments--with all of the personal networking and entertainment capabilities that a busy professional expects from a smartphone. The E5 also provides access to social networks directly on the homescreen, enabling you to view, comment, and update your status and share pictures to social networks such as Facebook and Twitter. Designed for those that want to be productive in both their professional and personal lives. You\'ll stay on track thanks to the integrated GPS with free Ovi Maps Navigation for voice-guided directions, and you can find nearby restaurants, landmarks, events and other points of interest as you travel from place to place. Keep on top of your emails from your phone or computer using the free Ovi Mail service, and discover and download apps and games via the pre-loaded Ovi Store. You\'ll also be able to sync, store, and manage your documents and files remotely with Ovi Files. The Nokia C6 comes with a pre-loaded 2 GB microSD memory card that includes Ovi Maps data for the US, Ovi Suite, and bonus content--no need to download anything from the Web or discs. And you can add more memory via optional microSD memory cards up to 16 GB in size. Type a quick email, SMS or note using the full QWERTY keyboard--built for fast, efficient messaging--and see everything clearly on the 2.36-inch widescreen display. Other features include Wi-Fi networking, 5-megapixel digital camera with DVD-quality video capture, Web browser with RSS feed support, multi-format digital media player, personal organizer tools, and up to 5.5 hours of 3G talk time (18.5 hours on standard GSM networks). Unlocked Phone This unlocked cell phone can be used with a GSM network service provider. It does not come with a SIM card, and it requires that you provide a SIM card for usage with your selected service provider. This phone comes with a full manufacturer\'s warranty. When paired with a compatible 3G network, you\'ll enjoy a high-speed connection offering a variety of feature-rich wireless services--from data connectivity to your office to multimedia streaming, and take advantage of simultaneous voice and data services. In areas not served by a 3G network, you\'ll continue to receive data service via EDGE network (depending on network compatibility). Note that the downloading of maps, games, music and videos and uploading of images and videos involves transferring large amounts of data. Your service provider may charge for the data transmission, and the availability of particular services and features may vary by carrier. Stay on top of all your communications: from instant messaging and corporate e-mail to Twitter and Facebook (see larger image ). Key Features Fast 3G connectivity with broadband-like speeds via 850/1900/2100 MHz UMTS/HSDPA (with EDGE data connectivity where 3G not available). Fast 3G connectivity with broadband-like speeds via 850/1900/2100 MHz UMTS/HSDPA (with EDGE data connectivity where 3G not available). Integrated assisted GPS (A-GPS) receiver with free Ovi Maps enables you to find your route quickly and easily, whether walking or driving. Use the Walk pedestrian navigation to find your way, or the voice-guided Drive navigation to find the best route. (Learn more) Integrated assisted GPS (A-GPS) receiver with free Ovi Maps enables you to find your route quickly and easily, whether walking or driving. Use the Walk pedestrian navigation to find your way, or the voice-guided Drive navigation to find the best route. ( Learn more ) 2.36-inch LCD screen (320 x 240 pixels, 256K color depth) 2.36-inch LCD screen (320 x 240 pixels, 256K color depth) Full QWERTY keyboard with dedicated home and messaging keys; five-way Navi key with soft keys, call and end keys. Full QWERTY keyboard with dedicated home and messaging keys; five-way Navi key with soft keys, call and end keys. Symbian OS version v. 9.3 (S60 3rd Edition, Feature Pack 2) Symbian OS version v. 9.3 (S60 3rd Edition, Feature Pack 2) See and share your Facebook and Twitter feeds from friends and colleagues right from your homescreen See and share your Facebook and Twitter feeds from friends and colleagues right from your homescreen 5-megapixel camera with 3x digital zoom, LED flash, multiple scene, white balance, and capture modes (such as panorama), and still image editor 5-megapixel camera with 3x digital zoom, LED flash, multiple scene, white balance, and capture modes (such as panorama), and still image editor Video capture capabilities with VGA resolution (640 x 480) at 15 frames per second (fps) Video capture capabilities with VGA resolution (640 x 480) at 15 frames per second (fps) Digital audio/video player with compatibility for MP3, WMA, and AAC/eAAC+ audio formats, plus MP4 and 3GPP video formats Digital audio/video player with compatibility for MP3, WMA, and AAC/eAAC+ audio formats, plus MP4 and 3GPP video formats Wi-Fi networking (802.11b/g) for accessing home and corporate networks as well as hotspots while on the go. Wi-Fi networking (802.11b/g) for accessing home and corporate networks as well as hotspots while on the go. Bluetooth connectivity (version 2.0) includes profiles for communication headset, hands-free car kits, and the A2DP Bluetooth profile--enabling you to wirelessly stream your music to a pair of compatible Bluetooth stereo headphones or speaker dock. Bluetooth connectivity (version 2.0) includes profiles for communication headset, hands-free car kits, and the A2DP Bluetooth profile--enabling you to wirelessly stream your music to a pair of compatible Bluetooth stereo headphones or speaker dock. 256 MB internal memory 256 MB internal memory Included 2 GB microSD memory card with support for optional cards up to 16 GB. Included 2 GB microSD memory card with support for optional cards up to 16 GB. SMS and MMS messaging with common inbox SMS and MMS messaging with common inbox Instant messaging via AIM, Yahoo! Messenger, MSN Live, and Google Talk Instant messaging via AIM, Yahoo! Messenger, MSN Live, and Google Talk Corporate e-mail connectivity via Mail for Exchange and IBM Lotus Notes Traveler Corporate e-mail connectivity via Mail for Exchange and IBM Lotus Notes Traveler Access to personal e-mail via Yahoo! Mail, Gmail, Windows Live, Hotmail, and other popular POP/IMAP services. Easy Ovi Mail free email account creation directly from phone. Access to personal e-mail via Yahoo! Mail, Gmail, Windows Live, Hotmail, and other popular POP/IMAP services. Easy Ovi Mail free email account creation directly from phone. Nokia Web Browser (OSS) with Mini Map, Web feeds support (RSS) and xSP framework support Nokia Web Browser (OSS) with Mini Map, Web feeds support (RSS) and xSP framework support Pre-loaded applications include Quick Office Suite, PDF reader, ZIP (for compressed files), and Dictionary Pre-loaded applications include Quick Office Suite, PDF reader, ZIP (for compressed files), and Dictionary Organizer tools including calendar, to-do list, notes, active notes, recorder, calculator, clock, and converter Organizer tools including calendar, to-do list, notes, active notes, recorder, calculator, clock, and converter Airplane mode allows you to listen to music while the cellular connectivity is turned off Airplane mode allows you to listen to music while the cellular connectivity is turned off 3.5mm headphone jack 3.5mm headphone jack USB 2.0 portVital Statistics The Nokia E5-00 weighs 4.4 ounces and measures 4.5 x 2.3 x 0.5 inches. Its 1200 mAh lithium-ion battery is rated at up to 5.5 hours of talk time on 3G networks (18.5 hours on standard GMS networks), and up to 705 hours (29+ days) of standby time. It runs on the 850/900/1800/1900 MHz GSM/GPRS/EDGE frequencies, plus 850/1900/2100 3G networks (HSDPA). What\'s in the Box Nokia E5-00 handset, rechargeable battery (BL-4D), charger (AC-8), 2 GB microSD card, connectivity cable (CA-101D), wired stereo headset (WH-102), user guide Free Worldwide Walk and Drive NavigationNokia now offers its Ovi Maps walk and drive navigation application free across the globe. Drivers receive turn-by-turn voice guidance including lane assistance, traffic information (in 10 countries including the U.S.), and safety camera and speed warnings, while pedestrians will be guided on shortcuts through parks and pedestrian-only zones in over 100 cities across the globe. And unlike other mobile navigation mapping solutions, Ovi Maps works offline--no cellular service is required.  Driving directions. 3D landmarks. Lonely Planet guide. Real-time weather.With the new Ovi Maps for mobile you get for free:Maps for over 180 countries and free map updates Drive and Walk navigation available in over 70 countries with real-time voice guidance My Position enables you to find your current location easier and faster than ever. New one box search for quicker access to finding places and addresses. Save your favorite places and routes, then synchronize them with your Ovi account over the air. Car navigation with voice and visual instructions, lane assistance and speed limit information. Now also with text-to-speech voice guidance. Pedestrian navigation with routing through pedestrian zones and shortcuts, pathways through parks and buildings, stairways and plazas. Now with text-to-speech voice guidance. Get real-time weather information including a 5-day forecast, for your current or any location found via search. Lonely Planet and Michelin offer you dynamic access to the best and most relevant editorial travel content for over 1000 destinations. Find thousands of listings for sights, restaurants, hotels, shops, nightlife, and more. Look these places up on the map and get to them with Walk and Drive navigation. Discover the events happening nearby your location on the map or any place found via search. Share your location on Facebook--where you are, what you are up to and finish with a photo. No Hidden CostsThe new version of Ovi Maps comes with all the maps and high-end, car grade navigation features you need for free and is yours to keep for the life of the smartphone. No additional licenses needed for extra countries, regions or services like traffic information or city guides. Data charges from network operators may apply.Voice Guidance and Traffic InformationTurn-by-turn, voice guided navigation comes free for both drivers and pedestrians. For drivers this includes lane assistance, traffic information, safety camera, and speed warnings. For pedestrians, this includes shortcuts through parks and pedestrian-only zones for over 100 cities around the world as well as 6,000 3D landmarks in over 200 cities to help you find exactly where you are.Unique Hybrid TechnologyOvi Maps is built on an advanced technology called hybrid vector maps. Vector maps are high quality but less data intensive and allow you to continue to navigate even if you lose your network connection. This means that maps downloaded or updated across a network connection are about half the size of bulky bitmaps used by other mobile map providers. The hybrid technology ensures that, unlike other providers, any downloaded map data is stored on the device for future use.No Network Connection Required When NavigatingAvoid expensive, battery-draining network connections with Nokia\'s unique hybrid technology. Maps can be pre-loaded on to your Nokia smartphone so you can set Ovi Maps to offline mode, saving battery power, and the navigation system will still work. This is particularly useful for those worried about data connection costs when travelling abroad or when you are travelling through areas with little or no network coverage.Best Global CoverageYou take your mobile with you wherever you go in the world so, as standard, voice guided navigation for both pedestrians and drivers is available for 74 countries in 46 different languages and there are maps for over 180 countries. This gives you the best maps with the largest global coverage for free. USB 2.0 port Vital Statistics The Nokia E5-00 weighs 4.4 ounces and measures 4.5 x 2.3 x 0.5 inches. Its 1200 mAh lithium-ion battery is rated at up to 5.5 hours of talk time on 3G networks (18.5 hours on standard GMS networks), and up to 705 hours (29+ days) of standby time. It runs on the 850/900/1800/1900 MHz GSM/GPRS/EDGE frequencies, plus 850/1900/2100 3G networks (HSDPA). What\'s in the Box Nokia E5-00 handset, rechargeable battery (BL-4D), charger (AC-8), 2 GB microSD card, connectivity cable (CA-101D), wired stereo headset (WH-102), user guide Free Worldwide Walk and Drive Navigation Nokia now offers its Ovi Maps walk and drive navigation application free across the globe. Drivers receive turn-by-turn voice guidance including lane assistance, traffic information (in 10 countries including the U.S.), and safety camera and speed warnings, while pedestrians will be guided on shortcuts through parks and pedestrian-only zones in over 100 cities across the globe. And unlike other mobile navigation mapping solutions, Ovi Maps works offline--no cellular service is required. Driving directions. 3D landmarks. Lonely Planet guide. Real-time weather. With the new Ovi Maps for mobile you get for free: Maps for over 180 countries and free map updates Maps for over 180 countries and free map updates Drive and Walk navigation available in over 70 countries with real-time voice guidance Drive and Walk navigation available in over 70 countries with real-time voice guidance My Position enables you to find your current location easier and faster than ever. My Position enables you to find your current location easier and faster than ever. New one box search for quicker access to finding places and addresses. New one box search for quicker access to finding places and addresses. Save your favorite places and routes, then synchronize them with your Ovi account over the air. Save your favorite places and routes, then synchronize them with your Ovi account over the air. Car navigation with voice and visual instructions, lane assistance and speed limit information. Now also with text-to-speech voice guidance. Car navigation with voice and visual instructions , lane assistance and speed limit information. Now also with text-to-speech voice guidance. Pedestrian navigation with routing through pedestrian zones and shortcuts, pathways through parks and buildings, stairways and plazas. Now with text-to-speech voice guidance. Pedestrian navigation with routing through pedestrian zones and shortcuts, pathways through parks and buildings, stairways and plazas. Now with text-to-speech voice guidance. Get real-time weather information including a 5-day forecast, for your current or any location found via search. Get real-time weather information including a 5-day forecast, for your current or any location found via search. Lonely Planet and Michelin offer you dynamic access to the best and most relevant editorial travel content for over 1000 destinations. Find thousands of listings for sights, restaurants, hotels, shops, nightlife, and more. Look these places up on the map and get to them with Walk and Drive navigation. Lonely Planet and Michelin offer you dynamic access to the best and most relevant editorial travel content for over 1000 destinations. Find thousands of listings for sights, restaurants, hotels, shops, nightlife, and more. Look these places up on the map and get to them with Walk and Drive navigation. Discover the events happening nearby your location on the map or any place found via search. Discover the events happening nearby your location on the map or any place found via search. Share your location on Facebook--where you are, what you are up to and finish with a photo. No Hidden CostsThe new version of Ovi Maps comes with all the maps and high-end, car grade navigation features you need for free and is yours to keep for the life of the smartphone. No additional licenses needed for extra countries, regions or services like traffic information or city guides. Data charges from network operators may apply.Voice Guidance and Traffic InformationTurn-by-turn, voice guided navigation comes free for both drivers and pedestrians. For drivers this includes lane assistance, traffic information, safety camera, and speed warnings. For pedestrians, this includes shortcuts through parks and pedestrian-only zones for over 100 cities around the world as well as 6,000 3D landmarks in over 200 cities to help you find exactly where you are.Unique Hybrid TechnologyOvi Maps is built on an advanced technology called hybrid vector maps. Vector maps are high quality but less data intensive and allow you to

In [51]:
# =====================================================
# COORDINATED SCALABILITY TEST
# =====================================================

from pathlib import Path
import pandas as pd

from langchain_community.callbacks.manager import (
    get_openai_callback
)


PROJECT_ROOT = Path("..").resolve()

FINAL_FOLDER = (
    PROJECT_ROOT
    / "Results"
    / "Final"
)


benchmark = pd.read_csv(
    FINAL_FOLDER
    / "final_60_query_benchmark.csv"
)


SCALABILITY_QUERY_IDS = [
    6,
    14,
    21,
    29,
    34,
    37,
    48,
    54
]


scalability_queries = (
    benchmark[
        benchmark[
            "test_id"
        ].isin(
            SCALABILITY_QUERY_IDS
        )
    ]
    .copy()
)


print(
    "Scalability queries:",
    len(scalability_queries)
)


scalability_rows = []


for k in [5, 10, 20, 30]:

    print(
        "\nRunning retrieval_k =",
        k
    )

    for _, row in scalability_queries.iterrows():

        print(
            "Test:",
            row["test_id"]
        )

        with get_openai_callback() as cb:

            result = run_coordinated_system(
                user_query=row[
                    "user_query"
                ],
                retrieval_k=k,
                max_reviews=3,
                verbose=False
            )


        scalability_rows.append({

            "system":
                "Coordinated Multi-Agent",

            "test_id":
                int(
                    row[
                        "test_id"
                    ]
                ),

            "retrieval_k":
                k,

            "latency":
                result[
                    "latency"
                ][
                    "total"
                ],

            "tokens":
                int(
                    cb.total_tokens
                )
        })


coordinated_scalability = pd.DataFrame(
    scalability_rows
)


display(
    coordinated_scalability
)


coordinated_scalability.to_csv(
    FINAL_FOLDER
    / "coordinated_scalability.csv",
    index=False
)


print(
    "Saved coordinated scalability results."
)

Scalability queries: 8

Running retrieval_k = 5
Test: 6
Test: 14
Test: 21
Test: 29
Test: 34
Test: 37
Test: 48
Test: 54

Running retrieval_k = 10
Test: 6
Test: 14
Test: 21
Test: 29
Test: 34
Test: 37
Test: 48
Test: 54

Running retrieval_k = 20
Test: 6
Test: 14
Test: 21
Test: 29
Test: 34
Test: 37
Test: 48
Test: 54

Running retrieval_k = 30
Test: 6
Test: 14
Test: 21
Test: 29
Test: 34
Test: 37
Test: 48
Test: 54

                     system  test_id  retrieval_k  latency  tokens
0   Coordinated Multi-Agent        6            5   5.2852    1728
1   Coordinated Multi-Agent       14            5   3.5117    1705
2   Coordinated Multi-Agent       21            5   4.0063    1720
3   Coordinated Multi-Agent       29            5   3.5405    1652
4   Coordinated Multi-Agent       34            5   4.1996    1647
5   Coordinated Multi-Agent       37            5   4.2245    1717
6   Coordinated Multi-Agent       48            5   3.6629    1339
7   Coordinated Multi-Agent       54            5   4.6217    1697
8   Coordinated Multi-Agent        6           10   4.0924    1737
9   Coordinated Multi-Agent       14           10   3.7795    1703
10  Coordinated Multi-Agent       21           10   3.5156    1720
11  Coordinated Multi-Agent       29           10   4.1689    1571
12  Coordinated Multi-Agent       34           10   3.9446    1647
13  Coordinated Multi-Agent       37           10   4.6488    1694
14  Coordinated Multi-Agent       48           10   4.6225    1339
15  Coordinated Multi-Agent       54           10   3.8729    1697
16  Coordinated Multi-Agent        6           20   5.3247    1740
17  Coordinated Multi-Agent       14           20   9.3948    2692
18  Coordinated Multi-Agent       21           20   8.0293    2221
19  Coordinated Multi-Agent       29           20   5.4271    1700
20  Coordinated Multi-Agent       34           20   6.5738    2334
21  Coordinated Multi-Agent       37           20   6.7198    1730
22  Coordinated Multi-Agent       48           20   4.4729    1647
23  Coordinated Multi-Agent       54           20   4.1218    1692
24  Coordinated Multi-Agent        6           30   6.0999    2065
25  Coordinated Multi-Agent       14           30  11.9159    2973
26  Coordinated Multi-Agent       21           30   9.2919    2030
27  Coordinated Multi-Agent       29           30   3.8568    1699
28  Coordinated Multi-Agent       34           30   6.8797    2298
29  Coordinated Multi-Agent       37           30   4.9719    1719
30  Coordinated Multi-Agent       48           30   3.8153    1647
31  Coordinated Multi-Agent       54           30   5.1403    1692

Saved coordinated scalability results.

In [52]:
coordinated_scalability.groupby(
    "retrieval_k"
)[
    [
        "latency",
        "tokens"
    ]
].mean()

              latency    tokens
retrieval_k
5            4.131550  1650.625
10           4.080650  1638.500
20           6.258025  1969.500
30           6.496462  2015.375