In [1]:
import os
import sys
import time
import json
import pandas as pd

from pathlib import Path
from dotenv import load_dotenv

from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.vectorstores import FAISS

from typing import Literal

C:\Users\srush\AppData\Local\Temp\ipykernel_15432\2498989732.py:12: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.vectorstores import FAISS

In [2]:
load_dotenv()

PROJECT_ROOT = Path("..").resolve()

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))


llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)


embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small"
)


faiss_path = (
    PROJECT_ROOT
    / "Data"
    / "Cleaned"
    / "faiss_index"
)

vector_db = FAISS.load_local(
    folder_path=str(faiss_path),
    embeddings=embeddings,
    allow_dangerous_deserialization=True
)


reviews_path = (
    PROJECT_ROOT
    / "Data"
    / "Cleaned"
    / "reviews_sample.parquet"
)

reviews_df = pd.read_parquet(
    reviews_path
)

print("Single-agent resources loaded successfully.")

Single-agent resources loaded successfully.

In [3]:
class SingleAgentProduct(BaseModel):
    rank: int
    parent_asin: str
    title: str
    reason: str


class SingleAgentOutput(BaseModel):
    products: list[SingleAgentProduct] = Field(
        default_factory=list
    )

    recommended_product_asin: str | None = None
    recommended_product_title: str | None = None

    confidence: Literal[
    "high",
    "medium",
    "low"
]
    summary: str

In [4]:
def retrieve_single_agent_candidates(
    user_query: str,
    k: int = 10
) -> list[dict]:

    results = (
        vector_db.similarity_search_with_score(
            user_query,
            k=k
        )
    )

    candidates = []

    for document, distance in results:

        metadata = document.metadata.copy()

        candidates.append(
            {
                "parent_asin": str(
                    metadata.get(
                        "parent_asin",
                        ""
                    )
                ),

                "title": str(
                    metadata.get(
                        "title",
                        ""
                    )
                ),

                "price": metadata.get(
                    "price"
                ),

                "average_rating": metadata.get(
                    "average_rating",
                    0
                ),

                "rating_number": metadata.get(
                    "rating_number",
                    0
                ),

                "categories": metadata.get(
                    "categories",
                    []
                ),

                "product_text": document.page_content,

                "retrieval_distance": float(
                    distance
                )
            }
        )

    return candidates

In [5]:
def get_review_evidence(
    parent_asin: str,
    max_reviews: int = 3
) -> dict:

    product_reviews = reviews_df[
        reviews_df["parent_asin"]
        == parent_asin
    ]

    if product_reviews.empty:
        return {
            "review_count": 0,
            "average_review_rating": 0,
            "reviews": []
        }

    reviews = (
        product_reviews["text"]
        .dropna()
        .head(max_reviews)
        .astype(str)
        .tolist()
    )

    return {
        "review_count": len(
            product_reviews
        ),

        "average_review_rating": round(
            float(
                product_reviews["rating"]
                .mean()
            ),
            2
        ),

        "reviews": reviews
    }

In [6]:
def enrich_single_agent_candidates(
    candidates: list[dict],
    max_reviews: int = 3
) -> list[dict]:

    enriched = []

    for candidate in candidates:

        review_evidence = (
            get_review_evidence(
                parent_asin=(
                    candidate["parent_asin"]
                ),
                max_reviews=max_reviews
            )
        )

        enriched.append(
            {
                **candidate,
                **review_evidence
            }
        )

    return enriched

In [7]:
class SingleRecommendationAgent:

    def __init__(
        self,
        llm: ChatOpenAI
    ):

        self.structured_llm = (
            llm.with_structured_output(
                SingleAgentOutput
            )
        )

    def recommend(
        self,
        user_query: str,
        candidates: list[dict]
    ) -> SingleAgentOutput:

        compact_candidates = []

        for candidate in candidates:

            compact_candidates.append(
                {
                    "parent_asin": (
                        candidate[
                            "parent_asin"
                        ]
                    ),

                    "title": (
                        candidate["title"]
                    ),

                    "price": (
                        candidate.get(
                            "price"
                        )
                    ),

                    "average_rating": (
                        candidate.get(
                            "average_rating",
                            0
                        )
                    ),

                    "rating_number": (
                        candidate.get(
                            "rating_number",
                            0
                        )
                    ),

                    "product_text": str(
                        candidate.get(
                            "product_text",
                            ""
                        )
                    )[:500],

                    "review_count": (
                        candidate.get(
                            "review_count",
                            0
                        )
                    ),

                    "reviews": [
                        str(review)[:250]
                        for review in candidate.get(
                            "reviews",
                            []
                        )[:3]
                    ]
                }
            )

        prompt = f"""
You are a single-agent ecommerce recommendation system.

You must perform all tasks yourself:

1. Understand the customer request.
2. Check product type and brand.
3. Check budget when one is provided.
4. Evaluate requested features.
5. Use product metadata and customer reviews.
6. Reject accessories when the customer requested a main product.
7. Rank the valid products.
8. Select the best recommendation.

Customer query:

{user_query}

Retrieved candidates:

{json.dumps(
    compact_candidates,
    default=str
)}

Rules:

- Use only the supplied candidate evidence.
- Do not use outside product knowledge.
- Do not invent specifications.
- Do not recommend accessories as phones, laptops, headphones,
  earbuds or other main products.
- When a budget is stated, do not recommend a product with an
  unavailable or over-budget price.
- Missing reviews indicate limited evidence, not poor quality.
- Return no recommendation if no candidate satisfies the main
  product type or brand requirement.
- Rank at most five products.
- Keep reasons concise.
- Confidence must be exactly one of:
  high, medium, low.
"""

        return self.structured_llm.invoke(
            prompt
        )

In [8]:
single_agent = SingleRecommendationAgent(
    llm=llm
)

In [9]:
def run_single_agent_system(
    user_query: str,
    retrieval_k: int = 10,
    max_reviews: int = 3,
    verbose: bool = True
) -> dict:

    if not user_query or not user_query.strip():
        raise ValueError(
            "User query cannot be empty."
        )

    start_time = time.perf_counter()

    retrieval_start = time.perf_counter()

    candidates = retrieve_single_agent_candidates(
        user_query=user_query,
        k=retrieval_k
    )

    retrieval_latency = (
        time.perf_counter()
        - retrieval_start
    )

    enrichment_start = time.perf_counter()

    enriched_candidates = (
        enrich_single_agent_candidates(
            candidates=candidates,
            max_reviews=max_reviews
        )
    )

    enrichment_latency = (
        time.perf_counter()
        - enrichment_start
    )

    agent_start = time.perf_counter()

    output = single_agent.recommend(
        user_query=user_query,
        candidates=enriched_candidates
    )

    agent_latency = (
        time.perf_counter()
        - agent_start
    )

    total_latency = (
        time.perf_counter()
        - start_time
    )

    if verbose:

        print("=" * 100)
        print("SINGLE-AGENT SYSTEM")
        print("=" * 100)

        print("User query:")
        print(user_query)
        print()

        print(
            "Retrieved candidates:",
            len(candidates)
        )

        print()

        for product in output.products:

            print(
                f"{product.rank}. "
                f"{product.title}"
            )

            print(
                "Reason:",
                product.reason
            )

            print()

        print(
            "Recommended product:",
            output.recommended_product_title
        )

        print(
            "Confidence:",
            output.confidence
        )

        print(
            "Summary:",
            output.summary
        )

        print(
            "Total latency:",
            round(
                total_latency,
                2
            ),
            "seconds"
        )

    return {
        "system": "single_agent",
        "user_query": user_query,
        "candidates": candidates,
        "enriched_candidates": (
            enriched_candidates
        ),
        "output": output,
        "latency": {
            "retrieval": round(
                retrieval_latency,
                4
            ),
            "review_enrichment": round(
                enrichment_latency,
                4
            ),
            "single_agent": round(
                agent_latency,
                4
            ),
            "total": round(
                total_latency,
                4
            )
        }
    }

In [10]:
single_result = run_single_agent_system(
    user_query=(
        "Recommend a Samsung phone with a good "
        "camera and long battery life."
    ),
    retrieval_k=10,
    max_reviews=3,
    verbose=True
)

====================================================================================================
SINGLE-AGENT SYSTEM
====================================================================================================
User query:
Recommend a Samsung phone with a good camera and long battery life.

Retrieved candidates: 10

1. Samsung Galaxy S22 Ultra 256GB Unlocked ATT TMobile Verizon 100% batt! 7548400
Reason: High average rating (4.7) and good camera features.

2. SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Black - Unlocked (Renewed Premium)
Reason: High average rating (4.2) and excellent camera capabilities.

3. SAMSUNG Galaxy S21 FE 5G SM-G990U 256GB Factory Unlocked Smartphone (Renewed) (Olive)
Reason: Good average rating (4.7) and features a triple-lens camera.

4. Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 256GB, 8K Camera & Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom White (Renewed)
Reason: Good average rating (4.1) and strong camera performance.

5. Samsung Galaxy A52 (5G) 128GB A526U 6.5" Display Quad Camera Smartphone - Black (Renewed) (AT&T Unlocked)
Reason: Good average rating (4.2) and decent camera features.

Recommended product: Samsung Galaxy S22 Ultra 256GB Unlocked ATT TMobile Verizon 100% batt! 7548400
Confidence: high
Summary: The Samsung Galaxy S22 Ultra is the top recommendation due to its high rating and excellent camera features.
Total latency: 9.79 seconds

In [11]:
# =====================================================
# FINAL SINGLE-AGENT RUN
# 60 QUERIES + TOKENS + LATENCY
# =====================================================

from langchain_community.callbacks.manager import (
    get_openai_callback
)

import pandas as pd


FINAL_FOLDER = (
    PROJECT_ROOT
    / "Results"
    / "Final"
)


benchmark_df = pd.read_csv(
    FINAL_FOLDER
    / "final_60_query_benchmark.csv"
)


single_final_rows = []


for _, test_case in benchmark_df.iterrows():

    test_id = int(
        test_case["test_id"]
    )

    user_query = str(
        test_case["user_query"]
    )

    print(
        "Single Agent:",
        test_id
    )


    try:

        with get_openai_callback() as cb:

            result = run_single_agent_system(
                user_query=user_query,
                retrieval_k=10,
                max_reviews=3,
                verbose=False
            )


        output = result[
            "output"
        ]


        top_5_asins = [
            product.parent_asin
            for product
            in output.products[:5]
            if product.parent_asin
        ]


        top_5_titles = [
            product.title
            for product
            in output.products[:5]
            if product.title
        ]


        single_final_rows.append({

            "test_id":
                test_id,

            "category":
                test_case["category"],

            "user_query":
                user_query,

            "recommended_product":
                output.recommended_product_title,

            "recommended_asin":
                output.recommended_product_asin,

            "confidence":
                output.confidence,

            "top_5_asins":
                "|".join(
                    top_5_asins
                ),

            "top_5_titles":
                " || ".join(
                    top_5_titles
                ),

            "total_latency":
                result[
                    "latency"
                ][
                    "total"
                ],

            "prompt_tokens":
                int(
                    cb.prompt_tokens
                ),

            "completion_tokens":
                int(
                    cb.completion_tokens
                ),

            "total_tokens":
                int(
                    cb.total_tokens
                ),

            "estimated_cost_usd":
                float(
                    cb.total_cost
                ),

            "error":
                None
        })


    except Exception as error:

        single_final_rows.append({

            "test_id":
                test_id,

            "category":
                test_case["category"],

            "user_query":
                user_query,

            "recommended_product":
                None,

            "recommended_asin":
                None,

            "confidence":
                "low",

            "top_5_asins":
                "",

            "top_5_titles":
                "",

            "total_latency":
                0,

            "prompt_tokens":
                0,

            "completion_tokens":
                0,

            "total_tokens":
                0,

            "estimated_cost_usd":
                0,

            "error":
                str(error)
        })


single_final_df = pd.DataFrame(
    single_final_rows
)


display(
    single_final_df
)


single_final_df.to_csv(
    FINAL_FOLDER
    / "final_single_agent_results.csv",
    index=False
)


print(
    "Final Single Agent complete."
)

Single Agent: 1
Single Agent: 2
Single Agent: 3
Single Agent: 4
Single Agent: 5
Single Agent: 6
Single Agent: 7
Single Agent: 8
Single Agent: 9
Single Agent: 10
Single Agent: 11
Single Agent: 12
Single Agent: 13
Single Agent: 14
Single Agent: 15
Single Agent: 16
Single Agent: 17
Single Agent: 18
Single Agent: 19
Single Agent: 20
Single Agent: 21
Single Agent: 22
Single Agent: 23
Single Agent: 24
Single Agent: 25
Single Agent: 26
Single Agent: 27
Single Agent: 28
Single Agent: 29
Single Agent: 30
Single Agent: 31
Single Agent: 32
Single Agent: 33
Single Agent: 34
Single Agent: 35
Single Agent: 36
Single Agent: 37
Single Agent: 38
Single Agent: 39
Single Agent: 40
Single Agent: 41
Single Agent: 42
Single Agent: 43
Single Agent: 44
Single Agent: 45
Single Agent: 46
Single Agent: 47
Single Agent: 48
Single Agent: 49
Single Agent: 50
Single Agent: 51
Single Agent: 52
Single Agent: 53
Single Agent: 54
Single Agent: 55
Single Agent: 56
Single Agent: 57
Single Agent: 58
Single Agent: 59
Single Agent: 60

,test_id,category,user_query,recommended_product,recommended_asin,confidence,top_5_asins,top_5_titles,total_latency,prompt_tokens,completion_tokens,total_tokens,estimated_cost_usd,error
0,1,Brand Only,Recommend a Samsung phone.,"Samsung Galaxy A52 (5G) 128GB A526U 6.5"" Displ...",B09C6N8P6Y,medium,B09C6N8P6Y|B09S6VKCLX|B0BF1FZTLQ|B09WT8N5X7|B0...,"Samsung Galaxy A52 (5G) 128GB A526U 6.5"" Displ...",8.4858,3128,408,3536,0.000714,None
1,2,Brand Only,Recommend an Apple phone.,Apple iPhone 5 - 16GB (Black) Factory Unlocked,B00CX0OZHY,medium,B00CX0OZHY|B00BUYRQG6|B07DWFTVKL|B00EELONEU|B0...,Apple iPhone 5 - 16GB (Black) Factory Unlocked...,5.9017,2821,314,3135,0.000612,None
2,3,Brand Only,Suggest a Motorola smartphone.,Motorola DROID A855 Android Phone (Verizon Wir...,B002VRO83K,medium,B002VRO83K|B004AZ4FHA|B006P82YC8|B004P551BE|B0...,Motorola DROID A855 Android Phone (Verizon Wir...,4.7732,2451,322,2773,0.000561,None
3,4,Brand Only,Recommend a Nokia phone.,Nokia E5-00 Unlocked GSM Phone with Easy Email...,B003X26SLM,high,B003X26SLM|B00BIQXW1O|B00P5AVL0I|B07VP8P1Z1|B0...,Nokia E5-00 Unlocked GSM Phone with Easy Email...,6.3362,2743,394,3137,0.000648,None
4,5,Brand Only,Suggest a Google phone.,Google Pixel 6a Phone - Charcoal Pixel 6a Case...,B0B6PV17MC,high,B0B6PV17MC|B09NP4C1MF|B08BXBT8MD|B01M27MVQI|B0...,Google Pixel 6a Phone - Charcoal Pixel 6a Case...,5.3562,2793,335,3128,0.000620,None
5,6,Brand + Feature,Recommend a Samsung phone with a good camera.,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",B09S6VKCLX,high,B09S6VKCLX|B09WT8N5X7|B08Y973HW1|B07QH32PCY,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",4.9867,3089,338,3427,0.000666,None
6,7,Brand + Feature,Recommend a Samsung phone with long battery life.,"Samsung Galaxy S22 Smartphone, Factory Unlocke...",B09WT8N5X7,high,B09WT8N5X7|B09S6VKCLX,"Samsung Galaxy S22 Smartphone, Factory Unlocke...",4.1569,3097,221,3318,0.000597,None
7,8,Brand + Feature,Recommend an Apple phone with a good camera.,Apple iPhone 7 - 256GB - GSM Unlocked - Red (R...,B078WZX9LD,medium,B078WZX9LD|B00CX0OZHY,Apple iPhone 7 - 256GB - GSM Unlocked - Red (R...,2.6330,3010,157,3167,0.000546,None
8,9,Brand + Feature,Suggest a Motorola phone with a good camera.,Motorola Verizon Motorola Droid Razr M 4G Smar...,B004P551BE,high,B004P551BE|B002VRO83K|B006P82YC8|B004AZ4FHA|B0...,Motorola Verizon Motorola Droid Razr M 4G Smar...,5.9571,2555,351,2906,0.000594,None
9,10,Brand + Feature,Recommend a Samsung phone with fast performance.,"Samsung Galaxy S22 Smartphone, Factory Unlocke...",B09WT8N5X7,high,B09WT8N5X7|B09S6VKCLX|B0BF1FZTLQ|B09X9FC88M|B0...,"Samsung Galaxy S22 Smartphone, Factory Unlocke...",5.8461,2986,430,3416,0.000706,None
10,11,Brand + Feature,Recommend a Samsung phone for photography.,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",B09S6VKCLX,high,B09S6VKCLX|B07QH32PCY|B09WT8N5X7|B078JRHXXT|B0...,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",6.3686,2959,373,3332,0.000668,None
11,12,Brand + Feature,Suggest a Samsung smartphone for gaming.,SAMSUNG Galaxy S21 FE 5G SM-G990U 256GB Factor...,B0BF1FZTLQ,high,B0BF1FZTLQ|B09C6N8P6Y|B09S6VKCLX|B071JQG9GQ|B0...,SAMSUNG Galaxy S21 FE 5G SM-G990U 256GB Factor...,5.8911,3021,389,3410,0.000687,None
12,13,Brand + Feature,Recommend a Nokia phone with a good camera.,Nokia E5-00 Unlocked GSM Phone with Easy Email...,B003X26SLM,high,B003X26SLM|B00BIQXW1O|B00P5AVL0I|B00UYAE1K6|B0...,Nokia E5-00 Unlocked GSM Phone with Easy Email...,6.7452,2779,371,3150,0.000639,None
13,14,Budget,Recommend a smartphone under 200.,"POSH Revel S500a - 5.0"", 4G, Android 4.4 Kit K...",B00O3PAN1E,medium,B00O3PAN1E|B00F3SJJRO|B00NHPQDQ0|B003Y3BM0W|B0...,"POSH Revel S500a - 5.0"", 4G, Android 4.4 Kit K...",9.2553,3269,386,3655,0.000722,None
14,15,Budget,Recommend a smartphone under 250.,"ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inc...",B01LZ8516T,medium,B01LZ8516T|B00P5AVL0I|B00O3PAN1E|B00K874HD6|B0...,"ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inc...",5.4982,3098,366,3464,0.000684,None
15,16,Budget,Recommend a phone under 300.,"ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inc...",B01LZ8516T,medium,B01LZ8516T|B00F3SJJRO|B00P5AVL0I|B00O3PAN1E|B0...,"ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inc...",6.1510,3046,369,3415,0.000678,None
16,17,Budget,Suggest a smartphone under 400.,Huawei U8833/Y300 Android 4.1 Dual Core 1.0GHz...,B00F3SJJRO,medium,B00NHPQDQ0|B00F3SJJRO|B00P5AVL0I|B07K9PR1H5|B0...,Sudroid Z18 2.45 Inches Unlocked 3G Mini Phone...,5.8518,3205,373,3578,0.000705,None
17,18,Budget,Recommend a Samsung phone under 300.,Samsung Galaxy S3 Mini G730a 8GB Unlocked GSM ...,B00LMJDP1Y,high,B00LMJDP1Y|B00SNMU4QW|B00CGIULGC,Samsung Galaxy S3 Mini G730a 8GB Unlocked GSM ...,4.2875,3245,235,3480,0.000628,None
18,19,Budget,Recommend an Apple phone under 500.,Apple iPhone 5 - 16GB (Black) Factory Unlocked,B00CX0OZHY,medium,B00CX0OZHY|B00BUYRQG6,Apple iPhone 5 - 16GB (Black) Factory Unlocked...,22.0511,2828,174,3002,0.000529,None
19,20,Budget,Recommend a Motorola phone under 300.,Motorola Adventure V750 Camera 3G Cell Phone S...,B001COKAT4,medium,B001COKAT4|B006P82YC8|B002VRO83K|B004AZ4FHA|B0...,Motorola Adventure V750 Camera 3G Cell Phone S...,10.6648,2404,274,2678,0.000525,None
20,21,Feature Only,Recommend a phone with a great camera.,"ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inc...",B01LZ8516T,high,B01LZ8516T|B07QYTKZMT|B07F6ZM9QJ|B00ZAJB9C4|B0...,"ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inc...",32.6219,3015,474,3489,0.000737,None
21,22,Feature Only,Recommend a phone with long battery life.,OUKITEL 8000mAh Large Battery 18W Flash Charge...,B0995SX8X8,high,B0995SX8X8|B01LZ8516T,OUKITEL 8000mAh Large Battery 18W Flash Charge...,4.3009,3432,263,3695,0.000673,None
22,23,Feature Only,Suggest a smartphone for gaming.,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",B09L4QQCN2,high,B09L4QQCN2|B07F4BSXMQ,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",5.5903,2971,301,3272,0.000626,None
23,24,Feature Only,I need a phone for photography.,"Aureday 62"" Phone Tripod&Camera Stand, Selfie ...",B0BTYKDN5L,high,B0BTYKDN5L|B0B5GW3R1X|B08QSFBXC7|B07QYTKZMT|B0...,"Aureday 62"" Phone Tripod&Camera Stand, Selfie ...",6.7571,3220,483,3703,0.000773,None
24,25,Feature Only,Recommend a smartphone with fast performance.,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",B09L4QQCN2,high,B09L4QQCN2|B07K9PR1H5|B00O3PAN1E|B07RB4ZH83|B0...,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",7.0901,3035,529,3564,0.000773,None
25,26,Feature Only,Recommend a phone with fast charging.,None,None,low,,,1.9052,3439,37,3476,0.000538,None
26,27,Feature Only,Recommend a smartphone with good sound quality.,LG Electronics V20 - Factory Unlocked GSM Phon...,B078K4JQXC,high,B078K4JQXC|B00NO80S3E,LG Electronics V20 - Factory Unlocked GSM Phon...,3.2511,2915,172,3087,0.000540,None
27,28,Feature Only,Recommend a phone with large storage.,OUKITEL 8000mAh Large Battery 18W Flash Charge...,B0995SX8X8,high,B0995SX8X8|B0BLHCXZ8K|B07K9PR1H5|B07RB4ZH83|B0...,OUKITEL 8000mAh Large Battery 18W Flash Charge...,7.3698,3039,494,3533,0.000752,None
28,29,Multiple Features,Recommend a phone with a good camera and long ...,Moto G30 XT2129-2 4G LTE 128GB + 4GB GSM Globa...,B09L9T73NZ,high,B09L9T73NZ|B01LZ8516T|B0995SX8X8|B07RB4ZH83|B0...,Moto G30 XT2129-2 4G LTE 128GB + 4GB GSM Globa...,6.5360,3209,509,3718,0.000787,None
29,30,Multiple Features,Recommend a smartphone with a good camera and ...,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",B09L4QQCN2,high,B09L4QQCN2|B09MD8Z51Y|B09L9T73NZ|B07RB4ZH83|B0...,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",7.6190,3164,518,3682,0.000785,None
30,31,Multiple Features,Recommend a phone with long battery life and f...,None,None,medium,B07YXTYRPL|B09MD5JTXF|B082M1WWBY,"Solar Power Bank 36000mAh, Qi Wireless Charger...",4.7937,3232,310,3542,0.000671,None
31,32,Multiple Features,Recommend a phone for gaming with long battery...,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",B09L4QQCN2,high,B09L4QQCN2|B01LZ8516T|B0995SX8X8,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",5.0624,3283,362,3645,0.000710,None
32,33,Multiple Features,Recommend a phone for photography with large s...,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",B09S6VKCLX,high,B09S6VKCLX|B07QH32PCY|B01LZ8516T|B0995SX8X8|B0...,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",5.8687,3239,432,3671,0.000745,None
33,34,Multiple Features,"Recommend a smartphone with a good camera, lon...",Moto G30 XT2129-2 4G LTE 128GB + 4GB GSM Globa...,B09L9T73NZ,high,B09L9T73NZ|B09S6VKCLX|B08JPBCVBL|B09WT8N5X7|B0...,Moto G30 XT2129-2 4G LTE 128GB + 4GB GSM Globa...,17.5373,3107,515,3622,0.000775,None
34,35,Multiple Features,Recommend a phone with good sound quality and ...,OUKITEL 8000mAh Large Battery 18W Flash Charge...,B0995SX8X8,high,B0995SX8X8|B09M7514S7,OUKITEL 8000mAh Large Battery 18W Flash Charge...,4.2594,3112,272,3384,0.000630,None
35,36,Multiple Features,Suggest a phone with fast charging and a good ...,None,None,low,,,1.5116,3461,41,3502,0.000544,None
36,37,Complex,Recommend a Samsung phone under 300 with a goo...,SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G L...,B07QH32PCY,high,B07QH32PCY|B00LMJDP1Y|B00CGIULGC|B00K8CS822,SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G L...,4.3723,3112,295,3407,0.000644,None
37,38,Complex,Recommend a Samsung phone under 400 with long ...,Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked ...,B00CGIULGC,medium,B00CGIULGC|B09WT8N5X7,Samsung Galaxy Rugby Pro 4G LTE I547 Unlocked ...,3.1721,3007,198,3205,0.000570,None
38,39,Complex,Recommend an Apple phone under 500 with a good...,Apple iPhone 5 - 16GB (Black) Factory Unlocked,B00CX0OZHY,medium,B00CX0OZHY|B0097BED6K,Apple iPhone 5 - 16GB (Black) Factory Unlocked...,2.7540,3086,145,3231,0.000550,None
39,40,Complex,Recommend a Motorola phone under 300 with long...,Motorola PEBL Green Phone (T-Mobile),B000H1US68,medium,B000H1US68|B001COKAT4|B006P82YC8|B002VRO83K|B0...,Motorola PEBL Green Phone (T-Mobile) || Motoro...,3.6804,2638,259,2897,0.000551,None
40,41,Complex,Recommend a Samsung phone under 500 with a goo...,"Samsung Galaxy S22 Smartphone, Factory Unlocke...",B09WT8N5X7,high,B09WT8N5X7|B0BF1FZTLQ|B07QH32PCY|B09C6N8P6Y,"Samsung Galaxy S22 Smartphone, Factory Unlocke...",6.6927,3094,364,3458,0.000682,None
41,42,Complex,Recommend a Samsung phone under 500 with a goo...,"Samsung Galaxy S22 Smartphone, Factory Unlocke...",B09WT8N5X7,high,B09WT8N5X7|B07S6VKCLX|B09C6N8P6Y,"Samsung Galaxy S22 Smartphone, Factory Unlocke...",4.2815,3271,311,3582,0.000677,None
42,43,Ambiguous,Recommend the best Samsung phone.,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",B09S6VKCLX,medium,B09S6VKCLX|B09X9FC88M|B09WT8N5X7|B0BF1FZTLQ|B0...,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",5.5799,3134,391,3525,0.000705,None
43,44,Ambiguous,I need something good for photography.,"Aureday 62"" Phone Tripod&Camera Stand, Selfie ...",B0BTYKDN5L,high,B0BTYKDN5L|B07RWGG35H|B01LMUZRPE|B018LSGXDA|B0...,"Aureday 62"" Phone Tripod&Camera Stand, Selfie ...",5.9320,3335,475,3810,0.000785,None
44,45,Ambiguous,I need a phone that performs well.,"Ulefone Armor 15 Unlocked Rugged Phone, Built-...",B0BBRBXPGC,high,B0BBRBXPGC|B07RB4ZH83|B08KVYR2D1|B01N1WRJWA|B0...,"Ulefone Armor 15 Unlocked Rugged Phone, Built-...",6.8861,3166,515,3681,0.000784,None
45,46,Ambiguous,Suggest a good phone for travelling.,CUBOT Quest 5.5-inch Android 9.0 Pie Rugged Sm...,B07RB4ZH83,high,B07RB4ZH83|B01N1WRJWA|B00XM28BQ8|B004RZ2HWS|B0...,CUBOT Quest 5.5-inch Android 9.0 Pie Rugged Sm...,6.0570,3050,443,3493,0.000723,None
46,47,Ambiguous,I want a good all-round smartphone.,OUKITEL-WP8-Pro Smartphone Fingerprint Rugged ...,B08KVYR2D1,medium,B08KVYR2D1|B07RB4ZH83|B00F3SJJRO|B01N1WRJWA|B0...,OUKITEL-WP8-Pro Smartphone Fingerprint Rugged ...,7.4647,3132,459,3591,0.000745,None
47,48,Unsupported,Recommend an Apple phone with stylus support.,None,None,low,,,1.8493,3163,39,3202,0.000498,None
48,49,Unsupported,Recommend a Samsung phone with a removable bat...,SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G L...,B07QH32PCY,medium,B07QH32PCY|B09X9FC88M|B09WT8N5X7|B00D93LOY6|B0...,SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G L...,4.9632,3116,397,3513,0.000706,None
49,50,Unsupported,Recommend an Apple phone with a removable batt...,Apple iPhone 5 - 16GB (Black) Factory Unlocked,B00CX0OZHY,medium,B00CX0OZHY|B0097BED6K,Apple iPhone 5 - 16GB (Black) Factory Unlocked...,2.8164,3125,161,3286,0.000565,None
50,51,Unsupported,Recommend a Samsung phone with stylus support ...,None,None,low,,,1.5785,3107,40,3147,0.000490,None
51,52,Unsupported,Recommend a Google phone with a removable batt...,None,None,low,B01M27MVQI|B08BXBT8MD,"Google Pixel XL 128GB - 5.5"" Android GSM 4G LT...",3.1652,3195,187,3382,0.000591,None
52,53,Unsupported,Recommend an Apple phone with wireless chargin...,None,None,low,,,1.4620,3835,44,3879,0.000602,None
53,54,No Match,Recommend a Nokia phone with an 8K camera and ...,None,None,low,B00P5AVL0I|B00BIQXW1O|B003X26SLM|B07VP8P1Z1|B0...,"Nokia Lumia 530 RM-1018, 4GB, Single Sim (Unlo...",4.3962,2955,356,3311,0.000657,None
54,55,No Match,Recommend an Apple phone under 50.,Apple iPhone 5 - 16GB (Black) Factory Unlocked,B00CX0OZHY,medium,B00CX0OZHY|B00BUYRQG6,Apple iPhone 5 - 16GB (Black) Factory Unlocked...,2.5167,3094,162,3256,0.000561,None
55,56,No Match,Recommend a Samsung phone under 20 with a grea...,None,None,low,,,2.2419,2796,35,2831,0.000440,None
56,57,No Match,Recommend a Motorola phone with 1TB storage an...,None,None,low,B09L9T73NZ|B094XGTNGN|B004P551BE|B003Y3BM0W|B0...,Moto G30 XT2129-2 4G LTE 128GB + 4GB GSM Globa...,4.1972,2926,364,3290,0.000657,None
57,58,No Match,Recommend a Google phone under 50 with long ba...,"Google Pixel 3A XL (64GB, 4GB) 6.0"" Display GS...",B08BXBT8MD,low,B08BXBT8MD|B09NP4C1MF,"Google Pixel 3A XL (64GB, 4GB) 6.0"" Display GS...",3.3314,2898,219,3117,0.000566,None
58,59,No Match,Recommend an Apple phone with an 8K camera and...,Product A1006,B0097BED6K,medium,B0097BED6K,Product A1006,9.4781,3215,79,3294,0.000530,None
59,60,No Match,Recommend a Samsung phone under 10 with 1TB st...,None,None,low,B00LMJDP1Y|B071JQG9GQ|B08225GDLL|B09C6N8P6Y|B0...,Samsung Galaxy S3 Mini G730a 8GB Unlocked GSM ...,18.0917,3044,351,3395,0.000667,None

Final Single Agent complete.

In [11]:
from langchain_community.callbacks.manager import get_openai_callback
import pandas as pd

# Load the same 15 test queries
test_queries_df = pd.read_csv(
    PROJECT_ROOT
    / "Results"
    / "coordinated_pipeline_test_results.csv"
)[["test_id", "user_query"]].drop_duplicates(
    subset=["test_id"]
).sort_values("test_id")


single_token_rows = []

print("Queries loaded:", len(test_queries_df))


for _, row in test_queries_df.iterrows():

    test_id = int(row["test_id"])
    user_query = str(row["user_query"])

    print("Running Single Agent:", test_id)

    with get_openai_callback() as cb:

        result = run_single_agent_system(
            user_query=user_query,
            retrieval_k=10,
            max_reviews=3,
            verbose=False
        )

    single_token_rows.append({
        "test_id": test_id,
        "system": "Single Agent",
        "user_query": user_query,
        "prompt_tokens": int(cb.prompt_tokens),
        "completion_tokens": int(cb.completion_tokens),
        "total_tokens": int(cb.total_tokens),
        "estimated_cost_usd": float(cb.total_cost)
    })


single_token_df = pd.DataFrame(single_token_rows)

display(single_token_df)


single_token_df.to_csv(
    PROJECT_ROOT
    / "Results"
    / "single_agent_token_usage.csv",
    index=False
)

print("Saved Single Agent token results.")

Queries loaded: 15
Running Single Agent: 1
Running Single Agent: 2
Running Single Agent: 3
Running Single Agent: 4
Running Single Agent: 5
Running Single Agent: 6
Running Single Agent: 7
Running Single Agent: 8
Running Single Agent: 9
Running Single Agent: 10
Running Single Agent: 11
Running Single Agent: 12
Running Single Agent: 13
Running Single Agent: 14
Running Single Agent: 15

,test_id,system,user_query,prompt_tokens,completion_tokens,total_tokens,estimated_cost_usd
0,1,Single Agent,Recommend a Samsung phone with a good camera a...,3014,418,3432,0.000703
1,2,Single Agent,I want an Apple phone with excellent camera qu...,2939,212,3151,0.000568
2,3,Single Agent,Suggest a Google phone with fast performance.,2981,285,3266,0.000618
3,4,Single Agent,Recommend a Samsung phone under 300 with a goo...,3112,237,3349,0.000609
4,5,Single Agent,Recommend a smartphone under 250 with long bat...,3369,497,3866,0.000804
5,6,Single Agent,Recommend a phone with a great camera.,3015,220,3235,0.000584
6,7,Single Agent,Recommend a phone with long battery life.,3432,267,3699,0.000675
7,8,Single Agent,Suggest a smartphone for gaming.,2971,301,3272,0.000626
8,9,Single Agent,"Recommend a Samsung phone with a good camera, ...",3110,419,3529,0.000718
9,10,Single Agent,Recommend an Apple phone with a good camera an...,3008,277,3285,0.000617
10,11,Single Agent,Recommend the best Samsung phone.,3134,392,3526,0.000705
11,12,Single Agent,I need something good for photography.,3335,478,3813,0.000787
12,13,Single Agent,Recommend an Apple phone with stylus support.,3163,39,3202,0.000498
13,14,Single Agent,Recommend a Samsung phone with a removable bat...,3116,396,3512,0.000705
14,15,Single Agent,Recommend a Nokia phone with an 8K camera and ...,2955,44,2999,0.000470

Saved Single Agent token results.

### TESTING

In [11]:
# =====================================================
# TEST QUERIES FOR SINGLE-AGENT PIPELINE
# =====================================================

test_queries = [

    # -----------------------------------------
    # Brand + Feature Queries
    # -----------------------------------------

    {
        "test_id": 1,
        "category": "Brand + Features",
        "query": (
            "Recommend a Samsung phone with a good camera "
            "and long battery life."
        )
    },

    {
        "test_id": 2,
        "category": "Brand + Features",
        "query": (
            "I want an Apple phone with excellent camera quality."
        )
    },

    {
        "test_id": 3,
        "category": "Brand + Features",
        "query": (
            "Suggest a Google phone with fast performance."
        )
    },

    # -----------------------------------------
    # Budget Queries
    # -----------------------------------------

    {
        "test_id": 4,
        "category": "Budget",
        "query": (
            "Recommend a Samsung phone under 300 "
            "with a good camera."
        )
    },

    {
        "test_id": 5,
        "category": "Budget",
        "query": (
            "Recommend a smartphone under 250 "
            "with long battery life."
        )
    },

    # -----------------------------------------
    # Feature Only Queries
    # -----------------------------------------

    {
        "test_id": 6,
        "category": "Feature Only",
        "query": (
            "Recommend a phone with a great camera."
        )
    },

    {
        "test_id": 7,
        "category": "Feature Only",
        "query": (
            "Recommend a phone with long battery life."
        )
    },

    {
        "test_id": 8,
        "category": "Feature Only",
        "query": (
            "Suggest a smartphone for gaming."
        )
    },

    # -----------------------------------------
    # Multiple Feature Queries
    # -----------------------------------------

    {
        "test_id": 9,
        "category": "Multiple Features",
        "query": (
            "Recommend a Samsung phone with a good camera, "
            "long battery life and fast performance."
        )
    },

    {
        "test_id": 10,
        "category": "Multiple Features",
        "query": (
            "Recommend an Apple phone with a good camera "
            "and large storage."
        )
    },

    # -----------------------------------------
    # Ambiguous Queries
    # -----------------------------------------

    {
        "test_id": 11,
        "category": "Ambiguous",
        "query": (
            "Recommend the best Samsung phone."
        )
    },

    {
        "test_id": 12,
        "category": "Ambiguous",
        "query": (
            "I need something good for photography."
        )
    },

    # -----------------------------------------
    # Negative Queries
    # -----------------------------------------

    {
        "test_id": 13,
        "category": "Negative",
        "query": (
            "Recommend an Apple phone with stylus support."
        )
    },

    {
        "test_id": 14,
        "category": "Negative",
        "query": (
            "Recommend a Samsung phone with a removable battery "
            "and an excellent camera."
        )
    },

    # -----------------------------------------
    # No Match Query
    # -----------------------------------------

    {
        "test_id": 15,
        "category": "No Match",
        "query": (
            "Recommend a Nokia phone with an 8K camera "
            "and 1TB storage."
        )
    }

]

In [12]:
test_case = test_queries[0]

In [13]:
result = run_single_agent_system(
    user_query=test_case["query"],
    retrieval_k=10,
    max_reviews=3,
    verbose=False
)

In [14]:
# =====================================================
# RUN ALL TEST QUERIES - SINGLE AGENT
# =====================================================

import time
import pandas as pd

test_results = []

for test_case in test_queries:

    print("=" * 100)
    print(
        f"TEST {test_case['test_id']} | {test_case['category']}"
    )
    print("=" * 100)
    print(test_case["query"])
    print()

    try:

        start_time = time.perf_counter()

        result = run_single_agent_system(
            user_query=test_case["query"],
            retrieval_k=10,
            max_reviews=3,
            verbose=False
        )

        execution_time = (
            time.perf_counter()
            - start_time
        )

        output = result["output"]

        top_5_asins = [
                product.parent_asin
                for product in output.products[:5]
                if product.parent_asin
            ]

        top_5_titles = [
                product.title
                for product in output.products[:5]
                if product.title
            ]

        test_results.append({

            "test_id": test_case["test_id"],

            "category": test_case["category"],

            "user_query": test_case["query"],

            "retrieved_count": len(
                result["candidates"]
            ),

            "ranked_count": len(
                output.products
            ),

            "recommended_product":
                output.recommended_product_title,

            "recommended_asin":
                output.recommended_product_asin,

            "confidence":
                output.confidence,

            "summary":
                output.summary,

            "retrieval_latency":
                result["latency"]["retrieval"],

            "review_latency":
                result["latency"]["review_enrichment"],

            "single_agent_latency":
                result["latency"]["single_agent"],

            "total_latency":
                result["latency"]["total"],

            "top_5_asins": "|".join(top_5_asins),

            "top_5_titles": " || ".join(top_5_titles),

            "error": None

        })

        print(
            "Recommended:",
            output.recommended_product_title
        )

        print(
            "Confidence:",
            output.confidence
        )

        print(
            "Latency:",
            round(execution_time,2),
            "seconds"
        )

    except Exception as error:

        print(
            "Test failed:",
            type(error).__name__,
            str(error)
        )

        test_results.append({

            "test_id": test_case["test_id"],

            "category": test_case["category"],

            "user_query": test_case["query"],

            "retrieved_count":0,

            "ranked_count":0,

            "recommended_product":None,

            "recommended_asin":None,

            "confidence":"low",

            "summary":None,

            "retrieval_latency":0,

            "review_latency":0,

            "single_agent_latency":0,

            "total_latency":0,

            "top_5_asins": "",
            
            "top_5_titles": "",

            "error":str(error)

        })

====================================================================================================
TEST 1 | Brand + Features
====================================================================================================
Recommend a Samsung phone with a good camera and long battery life.

Recommended: Samsung Galaxy S22 Ultra 256GB Unlocked ATT TMobile Verizon 100% batt! 7548400
Confidence: high
Latency: 6.49 seconds
====================================================================================================
TEST 2 | Brand + Features
====================================================================================================
I want an Apple phone with excellent camera quality.

Recommended: Apple iPhone 7 - 256GB - GSM Unlocked - Red (Renewed)
Confidence: medium
Latency: 3.41 seconds
====================================================================================================
TEST 3 | Brand + Features
====================================================================================================
Suggest a Google phone with fast performance.

Recommended: Google Pixel 4a 5G UW Just Black-Verizon (Renewed)
Confidence: high
Latency: 5.24 seconds
====================================================================================================
TEST 4 | Budget
====================================================================================================
Recommend a Samsung phone under 300 with a good camera.

Recommended: SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G LTE Phone w/ 12MP Camera - Midnight Black
Confidence: high
Latency: 4.38 seconds
====================================================================================================
TEST 5 | Budget
====================================================================================================
Recommend a smartphone under 250 with long battery life.

Recommended: OUKITEL 8000mAh Large Battery 18W Flash Charge Outdoor Phone Android 10 4G 6+128GB Dual SIM Smartphone WP7 IP68 Rugged Cell Phone 6.56" FHD+ Display Unlocked Phone NFC OTG GPS Mobile Phone (Orange)
Confidence: high
Latency: 6.56 seconds
====================================================================================================
TEST 6 | Feature Only
====================================================================================================
Recommend a phone with a great camera.

Recommended: ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inch, 16GB (Glacier Silver)
Confidence: medium
Latency: 5.52 seconds
====================================================================================================
TEST 7 | Feature Only
====================================================================================================
Recommend a phone with long battery life.

Recommended: OUKITEL 8000mAh Large Battery 18W Flash Charge Outdoor Phone Android 10 4G 6+128GB Dual SIM Smartphone WP7 IP68 Rugged Cell Phone 6.56" FHD+ Display Unlocked Phone NFC OTG GPS Mobile Phone (Orange)
Confidence: high
Latency: 4.07 seconds
====================================================================================================
TEST 8 | Feature Only
====================================================================================================
Suggest a smartphone for gaming.

Recommended: Black Shark 4 Unlocked Phone, 5G Gaming Phone, Fast Charging 120W Cell Phone 12+256GB, 144Hz Snapdragon 870 Android Phone, 6.67" 48MP 4500mAh NFC Mobile Phone Global Version -Frost Grey
Confidence: high
Latency: 4.03 seconds
====================================================================================================
TEST 9 | Multiple Features
====================================================================================================
Recommend a Samsung phone with a good camera, long battery life and fast performance.

Recommended: Samsung Galaxy S22 Ultra 256GB Unlocked ATT TMobile Verizon 100% batt! 7548400
Confidence: high
Latency: 5.1 seconds
====================================================================================================
TEST 10 | Multiple Features
====================================================================================================
Recommend an Apple phone with a good camera and large storage.

Recommended: Apple iPhone 7 - 256GB - GSM Unlocked - Red (Renewed)
Confidence: high
Latency: 3.38 seconds
====================================================================================================
TEST 11 | Ambiguous
====================================================================================================
Recommend the best Samsung phone.

Recommended: SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Black - Unlocked (Renewed Premium)
Confidence: high
Latency: 5.83 seconds
====================================================================================================
TEST 12 | Ambiguous
====================================================================================================
I need something good for photography.

Recommended: Aureday 62" Phone Tripod&Camera Stand, Selfie Stick Tripod with Remote and Phone Holder, Perfect for Selfies/Video Recording/Vlogging/Live Streaming
Confidence: high
Latency: 7.99 seconds
====================================================================================================
TEST 13 | Negative
====================================================================================================
Recommend an Apple phone with stylus support.

Recommended: None
Confidence: low
Latency: 2.55 seconds
====================================================================================================
TEST 14 | Negative
====================================================================================================
Recommend a Samsung phone with a removable battery and an excellent camera.

Recommended: SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G LTE Phone w/ 12MP Camera - Midnight Black
Confidence: medium
Latency: 5.01 seconds
====================================================================================================
TEST 15 | No Match
====================================================================================================
Recommend a Nokia phone with an 8K camera and 1TB storage.

Recommended: None
Confidence: low
Latency: 1.88 seconds

In [15]:
# =====================================================
# CREATE RESULTS DATAFRAME
# =====================================================

single_agent_results_df = pd.DataFrame(
    test_results
)

display(
    single_agent_results_df
)

,test_id,category,user_query,retrieved_count,ranked_count,recommended_product,recommended_asin,confidence,summary,retrieval_latency,review_latency,single_agent_latency,total_latency,top_5_asins,top_5_titles,error
0,1,Brand + Features,Recommend a Samsung phone with a good camera a...,10,5,Samsung Galaxy S22 Ultra 256GB Unlocked ATT TM...,B09X9FC88M,high,The Samsung Galaxy S22 Ultra is the best recom...,0.8235,0.0498,5.6213,6.4946,B09X9FC88M|B09S6VKCLX|B0BF1FZTLQ|B09WT8N5X7|B0...,Samsung Galaxy S22 Ultra 256GB Unlocked ATT TM...,None
1,2,Brand + Features,I want an Apple phone with excellent camera qu...,10,3,Apple iPhone 7 - 256GB - GSM Unlocked - Red (R...,B078WZX9LD,medium,"The best recommendation is the Apple iPhone 7,...",0.3757,0.0953,2.9352,3.4062,B078WZX9LD|B00CX0OZHY|B00BUYRQG6,Apple iPhone 7 - 256GB - GSM Unlocked - Red (R...,None
2,3,Brand + Features,Suggest a Google phone with fast performance.,10,3,Google Pixel 4a 5G UW Just Black-Verizon (Rene...,B09NP4C1MF,high,The Google Pixel 4a 5G offers fast performance...,0.2835,0.0836,4.8763,5.2435,B09NP4C1MF|B08BXBT8MD|B01M27MVQI,Google Pixel 4a 5G UW Just Black-Verizon (Rene...,None
3,4,Budget,Recommend a Samsung phone under 300 with a goo...,10,3,SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G L...,B07QH32PCY,high,The Samsung Galaxy S9 is the best recommendati...,0.3885,0.0864,3.9052,4.3800,B07QH32PCY|B00LMJDP1Y|B00CGIULGC,SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G L...,None
4,5,Budget,Recommend a smartphone under 250 with long bat...,10,5,OUKITEL 8000mAh Large Battery 18W Flash Charge...,B0995SX8X8,high,Recommended the OUKITEL smartphone for its hig...,0.4487,0.1030,6.0048,6.5566,B0995SX8X8|B01LZ8516T|B07B944RHF|B07RB4ZH83|B0...,OUKITEL 8000mAh Large Battery 18W Flash Charge...,None
5,6,Feature Only,Recommend a phone with a great camera.,10,5,"ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inc...",B01LZ8516T,medium,The ASUS ZenFone 3 MAX is recommended for its ...,0.5903,0.0853,4.8483,5.5239,B01LZ8516T|B07QYTKZMT|B07F6ZM9QJ|B00ZAJB9C4|B0...,"ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inc...",None
6,7,Feature Only,Recommend a phone with long battery life.,10,2,OUKITEL 8000mAh Large Battery 18W Flash Charge...,B0995SX8X8,high,Recommended the OUKITEL phone for its exceptio...,0.4400,0.0922,3.5375,4.0696,B0995SX8X8|B01LZ8516T,OUKITEL 8000mAh Large Battery 18W Flash Charge...,None
7,8,Feature Only,Suggest a smartphone for gaming.,10,2,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",B09L4QQCN2,high,The Black Shark 4 is the best option for gamin...,0.4289,0.0952,3.5065,4.0306,B09L4QQCN2|B07F4BSXMQ,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",None
8,9,Multiple Features,"Recommend a Samsung phone with a good camera, ...",10,5,Samsung Galaxy S22 Ultra 256GB Unlocked ATT TM...,B09X9FC88M,high,The Samsung Galaxy S22 Ultra is the best recom...,0.2837,0.1000,4.7208,5.1046,B09X9FC88M|B09S6VKCLX|B0BF1FZTLQ|B0B1QXHB7L|B0...,Samsung Galaxy S22 Ultra 256GB Unlocked ATT TM...,None
9,10,Multiple Features,Recommend an Apple phone with a good camera an...,10,4,Apple iPhone 7 - 256GB - GSM Unlocked - Red (R...,B078WZX9LD,high,The best recommendation is the Apple iPhone 7 ...,0.3220,0.0512,3.0051,3.3782,B078WZX9LD|B00CX0OZHY|B00BUYRQG6|B07DWFTVKL,Apple iPhone 7 - 256GB - GSM Unlocked - Red (R...,None
10,11,Ambiguous,Recommend the best Samsung phone.,10,5,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",B09S6VKCLX,high,The best recommendation is the Samsung Galaxy ...,0.3188,0.0964,5.4164,5.8317,B09S6VKCLX|B09WT8N5X7|B0BF1FZTLQ|B07QH32PCY|B0...,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",None
11,12,Ambiguous,I need something good for photography.,10,5,"Aureday 62"" Phone Tripod&Camera Stand, Selfie ...",B0BTYKDN5L,high,"The best recommendation is the Aureday 62"" Pho...",1.6511,0.0944,6.2491,7.9947,B0BTYKDN5L|B07RWGG35H|B01LMUZRPE|B018LSGXDA|B0...,"Aureday 62"" Phone Tripod&Camera Stand, Selfie ...",None
12,13,Negative,Recommend an Apple phone with stylus support.,10,0,None,None,low,No valid Apple phone candidates found that mee...,0.7454,0.1081,1.6985,2.5520,,,None
13,14,Negative,Recommend a Samsung phone with a removable bat...,10,5,SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G L...,B07QH32PCY,medium,Recommended the Samsung Galaxy S9 for its exce...,0.4195,0.0962,4.4920,5.0078,B07QH32PCY|B09X9FC88M|B09WT8N5X7|B00D93LOY6|B0...,SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G L...,None
14,15,No Match,Recommend a Nokia phone with an 8K camera and ...,10,0,None,None,low,No Nokia phones with an 8K camera and 1TB stor...,0.4592,0.0914,1.3342,1.8848,,,None

In [16]:
# =====================================================
# DISPLAY SUMMARY TABLE
# =====================================================

summary_columns = [
    "test_id",
    "category",
    "user_query",

    "retrieved_count",
    "ranked_count",

    "recommended_product",
    "recommended_asin",

    "top_5_asins",
    "top_5_titles",

    "confidence",

    "total_latency",

    "error"
]

display(
    single_agent_results_df[
        summary_columns
    ]
)

,test_id,category,user_query,retrieved_count,ranked_count,recommended_product,recommended_asin,top_5_asins,top_5_titles,confidence,total_latency,error
0,1,Brand + Features,Recommend a Samsung phone with a good camera a...,10,5,Samsung Galaxy S22 Ultra 256GB Unlocked ATT TM...,B09X9FC88M,B09X9FC88M|B09S6VKCLX|B0BF1FZTLQ|B09WT8N5X7|B0...,Samsung Galaxy S22 Ultra 256GB Unlocked ATT TM...,high,6.4946,None
1,2,Brand + Features,I want an Apple phone with excellent camera qu...,10,3,Apple iPhone 7 - 256GB - GSM Unlocked - Red (R...,B078WZX9LD,B078WZX9LD|B00CX0OZHY|B00BUYRQG6,Apple iPhone 7 - 256GB - GSM Unlocked - Red (R...,medium,3.4062,None
2,3,Brand + Features,Suggest a Google phone with fast performance.,10,3,Google Pixel 4a 5G UW Just Black-Verizon (Rene...,B09NP4C1MF,B09NP4C1MF|B08BXBT8MD|B01M27MVQI,Google Pixel 4a 5G UW Just Black-Verizon (Rene...,high,5.2435,None
3,4,Budget,Recommend a Samsung phone under 300 with a goo...,10,3,SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G L...,B07QH32PCY,B07QH32PCY|B00LMJDP1Y|B00CGIULGC,SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G L...,high,4.3800,None
4,5,Budget,Recommend a smartphone under 250 with long bat...,10,5,OUKITEL 8000mAh Large Battery 18W Flash Charge...,B0995SX8X8,B0995SX8X8|B01LZ8516T|B07B944RHF|B07RB4ZH83|B0...,OUKITEL 8000mAh Large Battery 18W Flash Charge...,high,6.5566,None
5,6,Feature Only,Recommend a phone with a great camera.,10,5,"ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inc...",B01LZ8516T,B01LZ8516T|B07QYTKZMT|B07F6ZM9QJ|B00ZAJB9C4|B0...,"ASUS ZenFone 3 MAX ZC520TL Smartphone, 5.2-inc...",medium,5.5239,None
6,7,Feature Only,Recommend a phone with long battery life.,10,2,OUKITEL 8000mAh Large Battery 18W Flash Charge...,B0995SX8X8,B0995SX8X8|B01LZ8516T,OUKITEL 8000mAh Large Battery 18W Flash Charge...,high,4.0696,None
7,8,Feature Only,Suggest a smartphone for gaming.,10,2,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",B09L4QQCN2,B09L4QQCN2|B07F4BSXMQ,"Black Shark 4 Unlocked Phone, 5G Gaming Phone,...",high,4.0306,None
8,9,Multiple Features,"Recommend a Samsung phone with a good camera, ...",10,5,Samsung Galaxy S22 Ultra 256GB Unlocked ATT TM...,B09X9FC88M,B09X9FC88M|B09S6VKCLX|B0BF1FZTLQ|B0B1QXHB7L|B0...,Samsung Galaxy S22 Ultra 256GB Unlocked ATT TM...,high,5.1046,None
9,10,Multiple Features,Recommend an Apple phone with a good camera an...,10,4,Apple iPhone 7 - 256GB - GSM Unlocked - Red (R...,B078WZX9LD,B078WZX9LD|B00CX0OZHY|B00BUYRQG6|B07DWFTVKL,Apple iPhone 7 - 256GB - GSM Unlocked - Red (R...,high,3.3782,None
10,11,Ambiguous,Recommend the best Samsung phone.,10,5,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",B09S6VKCLX,B09S6VKCLX|B09WT8N5X7|B0BF1FZTLQ|B07QH32PCY|B0...,"SAMSUNG Galaxy S21 Ultra 5G, 128GB, Phantom Bl...",high,5.8317,None
11,12,Ambiguous,I need something good for photography.,10,5,"Aureday 62"" Phone Tripod&Camera Stand, Selfie ...",B0BTYKDN5L,B0BTYKDN5L|B07RWGG35H|B01LMUZRPE|B018LSGXDA|B0...,"Aureday 62"" Phone Tripod&Camera Stand, Selfie ...",high,7.9947,None
12,13,Negative,Recommend an Apple phone with stylus support.,10,0,None,None,,,low,2.5520,None
13,14,Negative,Recommend a Samsung phone with a removable bat...,10,5,SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G L...,B07QH32PCY,B07QH32PCY|B09X9FC88M|B09WT8N5X7|B00D93LOY6|B0...,SAMSUNG Galaxy S9 G960U 64GB Unlocked GSM 4G L...,medium,5.0078,None
14,15,No Match,Recommend a Nokia phone with an 8K camera and ...,10,0,None,None,,,low,1.8848,None

In [17]:
# =====================================================
# SAVE SINGLE-AGENT RESULTS
# =====================================================

from pathlib import Path

results_folder = (
    PROJECT_ROOT
    / "Results" 
)

results_folder.mkdir(
    parents=True,
    exist_ok=True
)

output_path = (
    results_folder
    / "single_agent_test_results.csv"
)

single_agent_results_df.to_csv(
    output_path,
    index=False
)

print(
    "Single-agent results saved to:",
    output_path
)

Single-agent results saved to: C:\Users\srush\Desktop\Multi agent coordination\Results\single_agent_test_results.csv

In [18]:
# =====================================================
# BASIC LATENCY SUMMARY
# =====================================================

successful_results = single_agent_results_df[
    single_agent_results_df["error"].isna()
]

print(
    "Successful tests:",
    len(successful_results)
)

print(
    "Failed tests:",
    single_agent_results_df["error"]
    .notna()
    .sum()
)

print(
    "Average total latency:",
    round(
        successful_results[
            "total_latency"
        ].mean(),
        4
    ),
    "seconds"
)

print(
    "Median total latency:",
    round(
        successful_results[
            "total_latency"
        ].median(),
        4
    ),
    "seconds"
)

Successful tests: 15
Failed tests: 0
Average total latency: 4.7639 seconds
Median total latency: 5.0078 seconds